/**
 * Fulfillment Admin Page
 * Auto-generated by HEADLESS API Generator
 *
 * Features:
 * - Full CRUD operations
 * - Dummy data generation
 * - Table view with actions
 *
 * Add to App.tsx:
 *   import { FulfillmentAdminPage } from './pages/admin/entities/FulfillmentAdminPage'
 *   <Route path="/admin/fulfillments" element={<FulfillmentAdminPage />} />
 */

import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../../components/ui/card'
import { Button } from '../../../components/ui/button'
import { Input } from '../../../components/ui/input'
import { Textarea } from '../../../components/ui/textarea'
import { Badge } from '../../../components/ui/badge'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '../../../components/ui/table'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '../../../components/ui/dialog'
import { useFulfillments } from '../../../hooks/useFulfillments'
import type { Fulfillment } from '../../../models/Fulfillment'

// Dummy data templates - customize these for your entity
const DUMMY_DATA_TEMPLATES = [
  {
    orderItemId: null,
    fulfillmentType: 'Sample FulfillmentType 1',
    status: 'pending' as const,
    result: null,
    errorMessage: 'Sample ErrorMessage 1',
    completedAt: null,
  },
  {
    orderItemId: null,
    fulfillmentType: 'Sample FulfillmentType 2',
    status: 'pending' as const,
    result: null,
    errorMessage: 'Sample ErrorMessage 2',
    completedAt: null,
  },
  {
    orderItemId: null,
    fulfillmentType: 'Sample FulfillmentType 3',
    status: 'pending' as const,
    result: null,
    errorMessage: 'Sample ErrorMessage 3',
    completedAt: null,
  },
]

export function FulfillmentAdminPage() {
  const [isCreateOpen, setIsCreateOpen] = useState(false)
  const [isEditOpen, setIsEditOpen] = useState(false)
  const [editingItem, setEditingItem] = useState<Fulfillment | null>(null)
  const [isGenerating, setIsGenerating] = useState(false)

  // Form state
  const [orderItemId, setOrderItemId] = useState<string>(null)
  const [fulfillmentType, setFulfillmentType] = useState<string>('')
  const [status, setStatus] = useState<'pending' | 'completed' | 'failed'>('pending')
  const [result, setResult] = useState<Record<string, any>>(null)
  const [errorMessage, setErrorMessage] = useState<string>(null)
  const [completedAt, setCompletedAt] = useState<string>(null)

  const {
    fulfillments,
    isLoading,
    createFulfillment,
    isCreating,
    updateFulfillment,
    isUpdating,
    deleteFulfillment,
    isDeleting,
    setStatusCompleted,
    setStatusPending,
  } = useFulfillments({ mine: true })

  const resetForm = () => {
    setOrderItemId(null)
    setFulfillmentType('')
    setStatus('pending')
    setResult(null)
    setErrorMessage(null)
    setCompletedAt(null)
  }

  const handleCreate = () => {
    createFulfillment({
      orderItemId,
      fulfillmentType,
      status,
      result,
      errorMessage,
      completedAt,
    })
    resetForm()
    setIsCreateOpen(false)
  }

  const handleEdit = (item: Fulfillment) => {
    setEditingItem(item)
    setOrderItemId(item.orderItemId)
    setFulfillmentType(item.fulfillmentType)
    setStatus(item.status)
    setResult(item.result ?? null)
    setErrorMessage(item.errorMessage ?? null)
    setCompletedAt(item.completedAt ?? null)
    setIsEditOpen(true)
  }

  const handleUpdate = () => {
    if (!editingItem?.id) return
    updateFulfillment(editingItem.id, {
      orderItemId,
      fulfillmentType,
      status,
      result,
      errorMessage,
      completedAt,
    })
    resetForm()
    setEditingItem(null)
    setIsEditOpen(false)
  }

  const handleDelete = (id: string) => {
    if (confirm('Are you sure you want to delete this fulfillment?')) {
      deleteFulfillment(id)
    }
  }

  const handleGenerateDummyData = async () => {
    setIsGenerating(true)
    try {
      for (const template of DUMMY_DATA_TEMPLATES) {
        await new Promise<void>((resolve) => {
          createFulfillment(template as any)
          setTimeout(resolve, 300)
        })
      }
    } finally {
      setIsGenerating(false)
    }
  }

  const totalCount = fulfillments?.length ?? 0

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold">Fulfillment Management</h1>
          <p className="text-gray-500">Manage fulfillments in the system</p>
        </div>
        <div className="flex gap-2">
          <Button
            variant="outline"
            onClick={handleGenerateDummyData}
            disabled={isGenerating}
          >
            {isGenerating ? '🔄 Generating...' : '🎲 Generate Dummy Data'}
          </Button>
          <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
            <DialogTrigger asChild>
              <Button>➕ Create Fulfillment</Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Create New Fulfillment</DialogTitle>
                <DialogDescription>
                  Fill in the details to create a new fulfillment.
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-4 py-4">
                <div>
                  <label className="text-sm font-medium">FulfillmentType</label>
                  <Input
                    value={ fulfillmentType ?? ''}
                    onChange={(e) => setFulfillmentType(e.target.value)}
                    placeholder="Enter fulfillmentType"
                  />
                </div>
                <div>
                  <label className="text-sm font-medium">Status</label>
                  <select
                    className="w-full border rounded-md p-2"
                    value={ status ?? ''}
                    onChange={(e) => setStatus(e.target.value as any)}
                  >
                    <option value="pending">pending</option>
                    <option value="completed">completed</option>
                    <option value="failed">failed</option>
                  </select>
                </div>
                <div>
                  <label className="text-sm font-medium">ErrorMessage</label>
                  <Input
                    value={ errorMessage ?? ''}
                    onChange={(e) => setErrorMessage(e.target.value)}
                    placeholder="Enter errorMessage"
                  />
                </div>
              </div>
              <DialogFooter>
                <Button variant="outline" onClick={() => setIsCreateOpen(false)}>
                  Cancel
                </Button>
                <Button onClick={handleCreate} disabled={isCreating}>
                  {isCreating ? 'Creating...' : 'Create'}
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      </div>

      {/* Stats Card */}
      <Card>
        <CardHeader>
          <CardTitle>📊 Statistics</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="bg-blue-50 p-4 rounded-lg">
              <p className="text-2xl font-bold">{totalCount}</p>
              <p className="text-sm text-gray-500">Total Fulfillments</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Table */}
      <Card>
        <CardHeader>
          <CardTitle>📋 Fulfillment List</CardTitle>
          <CardDescription>
            All fulfillments in the system
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <p className="text-center py-8 text-gray-500">Loading...</p>
          ) : totalCount === 0 ? (
            <p className="text-center py-8 text-gray-500">
              No fulfillments yet. Create one or generate dummy data!
            </p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>OrderItemId</TableHead>
                  <TableHead>FulfillmentType</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>Result</TableHead>
                  <TableHead>Created</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                { fulfillments?.map((item) => (
                  <TableRow key={item.id}>
                    <TableCell className="max-w-xs truncate">{item.orderItemId}</TableCell>
                    <TableCell className="max-w-xs truncate">{item.fulfillmentType}</TableCell>
                    <TableCell>
                      <Badge variant="secondary">
                        {item.status}
                      </Badge>
                    </TableCell>
                    <TableCell className="max-w-xs truncate">{item.result}</TableCell>
                    <TableCell className="text-sm text-gray-500">
                      {item.createdAt ? new Date(item.createdAt).toLocaleDateString() : '-'}
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-2">
                        <Button size="sm" variant="outline" onClick={() => handleEdit(item)}>
                          Edit
                        </Button>
                        <Button
                          size="sm"
                          variant="secondary"
                          onClick={() => {
                            if (item.status === 'pending') {
                              setStatusCompleted(item.id!)
                            } else {
                              setStatusPending(item.id!)
                            }
                          }}
                        >
                          Toggle Status
                        </Button>
                        <Button
                          size="sm"
                          variant="destructive"
                          onClick={() => handleDelete(item.id!)}
                          disabled={isDeleting}
                        >
                          Delete
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {/* Edit Dialog */}
      <Dialog open={isEditOpen} onOpenChange={setIsEditOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Edit Fulfillment</DialogTitle>
            <DialogDescription>
              Update the fulfillment details.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div>
              <label className="text-sm font-medium">FulfillmentType</label>
              <Input
                value={ fulfillmentType ?? ''}
                onChange={(e) => setFulfillmentType(e.target.value)}
                placeholder="Enter fulfillmentType"
              />
            </div>
            <div>
              <label className="text-sm font-medium">Status</label>
              <select
                className="w-full border rounded-md p-2"
                value={ status ?? ''}
                onChange={(e) => setStatus(e.target.value as any)}
              >
                <option value="pending">pending</option>
                <option value="completed">completed</option>
                <option value="failed">failed</option>
              </select>
            </div>
            <div>
              <label className="text-sm font-medium">ErrorMessage</label>
              <Input
                value={ errorMessage ?? ''}
                onChange={(e) => setErrorMessage(e.target.value)}
                placeholder="Enter errorMessage"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsEditOpen(false)}>
              Cancel
            </Button>
            <Button onClick={handleUpdate} disabled={isUpdating}>
              {isUpdating ? 'Updating...' : 'Update'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}