/**
 * OrderItem Admin Page
 * Auto-generated by HEADLESS API Generator
 *
 * Features:
 * - Full CRUD operations
 * - Dummy data generation
 * - Table view with actions
 *
 * Add to App.tsx:
 *   import { OrderItemAdminPage } from './pages/admin/entities/OrderItemAdminPage'
 *   <Route path="/admin/orderitems" element={<OrderItemAdminPage />} />
 */

import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../../components/ui/card'
import { Button } from '../../../components/ui/button'
import { Input } from '../../../components/ui/input'
import { Textarea } from '../../../components/ui/textarea'
import { Badge } from '../../../components/ui/badge'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '../../../components/ui/table'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '../../../components/ui/dialog'
import { useOrderItems } from '../../../hooks/useOrderItems'
import type { OrderItem } from '../../../models/OrderItem'

// Dummy data templates - customize these for your entity
const DUMMY_DATA_TEMPLATES = [
  {
    orderId: null,
    productId: null,
    variantId: null,
    productName: 'Sample ProductName 1',
    variantName: 'Sample VariantName 1',
    quantity: 1,
    unitPrice: 1,
    subtotal: 1,
    productType: 'Sample ProductType 1',
    productMetadata: null,
  },
  {
    orderId: null,
    productId: null,
    variantId: null,
    productName: 'Sample ProductName 2',
    variantName: 'Sample VariantName 2',
    quantity: 2,
    unitPrice: 2,
    subtotal: 2,
    productType: 'Sample ProductType 2',
    productMetadata: null,
  },
  {
    orderId: null,
    productId: null,
    variantId: null,
    productName: 'Sample ProductName 3',
    variantName: 'Sample VariantName 3',
    quantity: 3,
    unitPrice: 3,
    subtotal: 3,
    productType: 'Sample ProductType 3',
    productMetadata: null,
  },
]

export function OrderItemAdminPage() {
  const [isCreateOpen, setIsCreateOpen] = useState(false)
  const [isEditOpen, setIsEditOpen] = useState(false)
  const [editingItem, setEditingItem] = useState<OrderItem | null>(null)
  const [isGenerating, setIsGenerating] = useState(false)

  // Form state
  const [orderId, setOrderId] = useState<string>(null)
  const [productId, setProductId] = useState<string>(null)
  const [variantId, setVariantId] = useState<string>(null)
  const [productName, setProductName] = useState<string>('')
  const [variantName, setVariantName] = useState<string>(null)
  const [quantity, setQuantity] = useState<number>(0)
  const [unitPrice, setUnitPrice] = useState<number>(0)
  const [subtotal, setSubtotal] = useState<number>(0)
  const [productType, setProductType] = useState<string>('')
  const [productMetadata, setProductMetadata] = useState<Record<string, any>>(null)

  const {
    orderitems,
    isLoading,
    createOrderItem,
    isCreating,
    updateOrderItem,
    isUpdating,
    deleteOrderItem,
    isDeleting,
  } = useOrderItems({ mine: true })

  const resetForm = () => {
    setOrderId(null)
    setProductId(null)
    setVariantId(null)
    setProductName('')
    setVariantName(null)
    setQuantity(0)
    setUnitPrice(0)
    setSubtotal(0)
    setProductType('')
    setProductMetadata(null)
  }

  const handleCreate = () => {
    createOrderItem({
      orderId,
      productId,
      variantId,
      productName,
      variantName,
      quantity,
      unitPrice,
      subtotal,
      productType,
      productMetadata,
    })
    resetForm()
    setIsCreateOpen(false)
  }

  const handleEdit = (item: OrderItem) => {
    setEditingItem(item)
    setOrderId(item.orderId)
    setProductId(item.productId ?? null)
    setVariantId(item.variantId ?? null)
    setProductName(item.productName)
    setVariantName(item.variantName ?? null)
    setQuantity(item.quantity)
    setUnitPrice(item.unitPrice)
    setSubtotal(item.subtotal)
    setProductType(item.productType)
    setProductMetadata(item.productMetadata ?? null)
    setIsEditOpen(true)
  }

  const handleUpdate = () => {
    if (!editingItem?.id) return
    updateOrderItem(editingItem.id, {
      orderId,
      productId,
      variantId,
      productName,
      variantName,
      quantity,
      unitPrice,
      subtotal,
      productType,
      productMetadata,
    })
    resetForm()
    setEditingItem(null)
    setIsEditOpen(false)
  }

  const handleDelete = (id: string) => {
    if (confirm('Are you sure you want to delete this orderitem?')) {
      deleteOrderItem(id)
    }
  }

  const handleGenerateDummyData = async () => {
    setIsGenerating(true)
    try {
      for (const template of DUMMY_DATA_TEMPLATES) {
        await new Promise<void>((resolve) => {
          createOrderItem(template as any)
          setTimeout(resolve, 300)
        })
      }
    } finally {
      setIsGenerating(false)
    }
  }

  const totalCount = orderitems?.length ?? 0

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold">OrderItem Management</h1>
          <p className="text-gray-500">Manage orderitems in the system</p>
        </div>
        <div className="flex gap-2">
          <Button
            variant="outline"
            onClick={handleGenerateDummyData}
            disabled={isGenerating}
          >
            {isGenerating ? '🔄 Generating...' : '🎲 Generate Dummy Data'}
          </Button>
          <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
            <DialogTrigger asChild>
              <Button>➕ Create OrderItem</Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Create New OrderItem</DialogTitle>
                <DialogDescription>
                  Fill in the details to create a new orderitem.
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-4 py-4">
                <div>
                  <label className="text-sm font-medium">ProductName</label>
                  <Input
                    value={ productName ?? ''}
                    onChange={(e) => setProductName(e.target.value)}
                    placeholder="Enter productName"
                  />
                </div>
                <div>
                  <label className="text-sm font-medium">VariantName</label>
                  <Input
                    value={ variantName ?? ''}
                    onChange={(e) => setVariantName(e.target.value)}
                    placeholder="Enter variantName"
                  />
                </div>
                <div>
                  <label className="text-sm font-medium">ProductType</label>
                  <Input
                    value={ productType ?? ''}
                    onChange={(e) => setProductType(e.target.value)}
                    placeholder="Enter productType"
                  />
                </div>
              </div>
              <DialogFooter>
                <Button variant="outline" onClick={() => setIsCreateOpen(false)}>
                  Cancel
                </Button>
                <Button onClick={handleCreate} disabled={isCreating}>
                  {isCreating ? 'Creating...' : 'Create'}
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      </div>

      {/* Stats Card */}
      <Card>
        <CardHeader>
          <CardTitle>📊 Statistics</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="bg-blue-50 p-4 rounded-lg">
              <p className="text-2xl font-bold">{totalCount}</p>
              <p className="text-sm text-gray-500">Total OrderItems</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Table */}
      <Card>
        <CardHeader>
          <CardTitle>📋 OrderItem List</CardTitle>
          <CardDescription>
            All orderitems in the system
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <p className="text-center py-8 text-gray-500">Loading...</p>
          ) : totalCount === 0 ? (
            <p className="text-center py-8 text-gray-500">
              No orderitems yet. Create one or generate dummy data!
            </p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>OrderId</TableHead>
                  <TableHead>ProductId</TableHead>
                  <TableHead>VariantId</TableHead>
                  <TableHead>ProductName</TableHead>
                  <TableHead>Created</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                { orderitems?.map((item) => (
                  <TableRow key={item.id}>
                    <TableCell className="max-w-xs truncate">{item.orderId}</TableCell>
                    <TableCell className="max-w-xs truncate">{item.productId}</TableCell>
                    <TableCell className="max-w-xs truncate">{item.variantId}</TableCell>
                    <TableCell className="max-w-xs truncate">{item.productName}</TableCell>
                    <TableCell className="text-sm text-gray-500">
                      {item.createdAt ? new Date(item.createdAt).toLocaleDateString() : '-'}
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-2">
                        <Button size="sm" variant="outline" onClick={() => handleEdit(item)}>
                          Edit
                        </Button>
                        <Button
                          size="sm"
                          variant="destructive"
                          onClick={() => handleDelete(item.id!)}
                          disabled={isDeleting}
                        >
                          Delete
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {/* Edit Dialog */}
      <Dialog open={isEditOpen} onOpenChange={setIsEditOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Edit OrderItem</DialogTitle>
            <DialogDescription>
              Update the orderitem details.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div>
              <label className="text-sm font-medium">ProductName</label>
              <Input
                value={ productName ?? ''}
                onChange={(e) => setProductName(e.target.value)}
                placeholder="Enter productName"
              />
            </div>
            <div>
              <label className="text-sm font-medium">VariantName</label>
              <Input
                value={ variantName ?? ''}
                onChange={(e) => setVariantName(e.target.value)}
                placeholder="Enter variantName"
              />
            </div>
            <div>
              <label className="text-sm font-medium">ProductType</label>
              <Input
                value={ productType ?? ''}
                onChange={(e) => setProductType(e.target.value)}
                placeholder="Enter productType"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsEditOpen(false)}>
              Cancel
            </Button>
            <Button onClick={handleUpdate} disabled={isUpdating}>
              {isUpdating ? 'Updating...' : 'Update'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}