/**
 * Order Admin Page
 * Auto-generated by HEADLESS API Generator
 *
 * Features:
 * - Full CRUD operations
 * - Dummy data generation
 * - Table view with actions
 *
 * Add to App.tsx:
 *   import { OrderAdminPage } from './pages/admin/entities/OrderAdminPage'
 *   <Route path="/admin/orders" element={<OrderAdminPage />} />
 */

import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../../components/ui/card'
import { Button } from '../../../components/ui/button'
import { Input } from '../../../components/ui/input'
import { Textarea } from '../../../components/ui/textarea'
import { Badge } from '../../../components/ui/badge'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '../../../components/ui/table'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '../../../components/ui/dialog'
import { useOrders } from '../../../hooks/useOrders'
import type { Order } from '../../../models/Order'

// Dummy data templates - customize these for your entity
const DUMMY_DATA_TEMPLATES = [
  {
    stripeCheckoutSessionId: 'Sample StripeCheckoutSessionId 1',
    stripePaymentIntentId: 'Sample StripePaymentIntentId 1',
    status: 'pending' as const,
    totalAmount: 1,
    currency: 'Sample Currency 1',
    metadata: null,
    fulfilledAt: null,
  },
  {
    stripeCheckoutSessionId: 'Sample StripeCheckoutSessionId 2',
    stripePaymentIntentId: 'Sample StripePaymentIntentId 2',
    status: 'pending' as const,
    totalAmount: 2,
    currency: 'Sample Currency 2',
    metadata: null,
    fulfilledAt: null,
  },
  {
    stripeCheckoutSessionId: 'Sample StripeCheckoutSessionId 3',
    stripePaymentIntentId: 'Sample StripePaymentIntentId 3',
    status: 'pending' as const,
    totalAmount: 3,
    currency: 'Sample Currency 3',
    metadata: null,
    fulfilledAt: null,
  },
]

export function OrderAdminPage() {
  const [isCreateOpen, setIsCreateOpen] = useState(false)
  const [isEditOpen, setIsEditOpen] = useState(false)
  const [editingItem, setEditingItem] = useState<Order | null>(null)
  const [isGenerating, setIsGenerating] = useState(false)

  // Form state
  const [stripeCheckoutSessionId, setStripeCheckoutSessionId] = useState<string>(null)
  const [stripePaymentIntentId, setStripePaymentIntentId] = useState<string>(null)
  const [status, setStatus] = useState<'pending' | 'paid' | 'fulfilled' | 'cancelled' | 'refunded'>('pending')
  const [totalAmount, setTotalAmount] = useState<number>(0)
  const [currency, setCurrency] = useState<string>('')
  const [metadata, setMetadata] = useState<Record<string, any>>(null)
  const [fulfilledAt, setFulfilledAt] = useState<string>(null)

  const {
    orders,
    isLoading,
    createOrder,
    isCreating,
    updateOrder,
    isUpdating,
    deleteOrder,
    isDeleting,
    setStatusPaid,
    setStatusPending,
  } = useOrders({ mine: true })

  const resetForm = () => {
    setStripeCheckoutSessionId(null)
    setStripePaymentIntentId(null)
    setStatus('pending')
    setTotalAmount(0)
    setCurrency('')
    setMetadata(null)
    setFulfilledAt(null)
  }

  const handleCreate = () => {
    createOrder({
      stripeCheckoutSessionId,
      stripePaymentIntentId,
      status,
      totalAmount,
      currency,
      metadata,
      fulfilledAt,
    })
    resetForm()
    setIsCreateOpen(false)
  }

  const handleEdit = (item: Order) => {
    setEditingItem(item)
    setStripeCheckoutSessionId(item.stripeCheckoutSessionId ?? null)
    setStripePaymentIntentId(item.stripePaymentIntentId ?? null)
    setStatus(item.status)
    setTotalAmount(item.totalAmount)
    setCurrency(item.currency)
    setMetadata(item.metadata ?? null)
    setFulfilledAt(item.fulfilledAt ?? null)
    setIsEditOpen(true)
  }

  const handleUpdate = () => {
    if (!editingItem?.id) return
    updateOrder(editingItem.id, {
      stripeCheckoutSessionId,
      stripePaymentIntentId,
      status,
      totalAmount,
      currency,
      metadata,
      fulfilledAt,
    })
    resetForm()
    setEditingItem(null)
    setIsEditOpen(false)
  }

  const handleDelete = (id: string) => {
    if (confirm('Are you sure you want to delete this order?')) {
      deleteOrder(id)
    }
  }

  const handleGenerateDummyData = async () => {
    setIsGenerating(true)
    try {
      for (const template of DUMMY_DATA_TEMPLATES) {
        await new Promise<void>((resolve) => {
          createOrder(template as any)
          setTimeout(resolve, 300)
        })
      }
    } finally {
      setIsGenerating(false)
    }
  }

  const totalCount = orders?.length ?? 0

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold">Order Management</h1>
          <p className="text-gray-500">Manage orders in the system</p>
        </div>
        <div className="flex gap-2">
          <Button
            variant="outline"
            onClick={handleGenerateDummyData}
            disabled={isGenerating}
          >
            {isGenerating ? '🔄 Generating...' : '🎲 Generate Dummy Data'}
          </Button>
          <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
            <DialogTrigger asChild>
              <Button>➕ Create Order</Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Create New Order</DialogTitle>
                <DialogDescription>
                  Fill in the details to create a new order.
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-4 py-4">
                <div>
                  <label className="text-sm font-medium">StripeCheckoutSessionId</label>
                  <Input
                    value={ stripeCheckoutSessionId ?? ''}
                    onChange={(e) => setStripeCheckoutSessionId(e.target.value)}
                    placeholder="Enter stripeCheckoutSessionId"
                  />
                </div>
                <div>
                  <label className="text-sm font-medium">StripePaymentIntentId</label>
                  <Input
                    value={ stripePaymentIntentId ?? ''}
                    onChange={(e) => setStripePaymentIntentId(e.target.value)}
                    placeholder="Enter stripePaymentIntentId"
                  />
                </div>
                <div>
                  <label className="text-sm font-medium">Status</label>
                  <select
                    className="w-full border rounded-md p-2"
                    value={ status ?? ''}
                    onChange={(e) => setStatus(e.target.value as any)}
                  >
                    <option value="pending">pending</option>
                    <option value="paid">paid</option>
                    <option value="fulfilled">fulfilled</option>
                    <option value="cancelled">cancelled</option>
                    <option value="refunded">refunded</option>
                  </select>
                </div>
                <div>
                  <label className="text-sm font-medium">Currency</label>
                  <Input
                    value={ currency ?? ''}
                    onChange={(e) => setCurrency(e.target.value)}
                    placeholder="Enter currency"
                  />
                </div>
              </div>
              <DialogFooter>
                <Button variant="outline" onClick={() => setIsCreateOpen(false)}>
                  Cancel
                </Button>
                <Button onClick={handleCreate} disabled={isCreating}>
                  {isCreating ? 'Creating...' : 'Create'}
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      </div>

      {/* Stats Card */}
      <Card>
        <CardHeader>
          <CardTitle>📊 Statistics</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="bg-blue-50 p-4 rounded-lg">
              <p className="text-2xl font-bold">{totalCount}</p>
              <p className="text-sm text-gray-500">Total Orders</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Table */}
      <Card>
        <CardHeader>
          <CardTitle>📋 Order List</CardTitle>
          <CardDescription>
            All orders in the system
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <p className="text-center py-8 text-gray-500">Loading...</p>
          ) : totalCount === 0 ? (
            <p className="text-center py-8 text-gray-500">
              No orders yet. Create one or generate dummy data!
            </p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>StripeCheckoutSessionId</TableHead>
                  <TableHead>StripePaymentIntentId</TableHead>
                  <TableHead>Status</TableHead>
                  <TableHead>TotalAmount</TableHead>
                  <TableHead>Created</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                { orders?.map((item) => (
                  <TableRow key={item.id}>
                    <TableCell className="max-w-xs truncate">{item.stripeCheckoutSessionId}</TableCell>
                    <TableCell className="max-w-xs truncate">{item.stripePaymentIntentId}</TableCell>
                    <TableCell>
                      <Badge variant="secondary">
                        {item.status}
                      </Badge>
                    </TableCell>
                    <TableCell className="max-w-xs truncate">{item.totalAmount}</TableCell>
                    <TableCell className="text-sm text-gray-500">
                      {item.createdAt ? new Date(item.createdAt).toLocaleDateString() : '-'}
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-2">
                        <Button size="sm" variant="outline" onClick={() => handleEdit(item)}>
                          Edit
                        </Button>
                        <Button
                          size="sm"
                          variant="secondary"
                          onClick={() => {
                            if (item.status === 'pending') {
                              setStatusPaid(item.id!)
                            } else {
                              setStatusPending(item.id!)
                            }
                          }}
                        >
                          Toggle Status
                        </Button>
                        <Button
                          size="sm"
                          variant="destructive"
                          onClick={() => handleDelete(item.id!)}
                          disabled={isDeleting}
                        >
                          Delete
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {/* Edit Dialog */}
      <Dialog open={isEditOpen} onOpenChange={setIsEditOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Edit Order</DialogTitle>
            <DialogDescription>
              Update the order details.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div>
              <label className="text-sm font-medium">StripeCheckoutSessionId</label>
              <Input
                value={ stripeCheckoutSessionId ?? ''}
                onChange={(e) => setStripeCheckoutSessionId(e.target.value)}
                placeholder="Enter stripeCheckoutSessionId"
              />
            </div>
            <div>
              <label className="text-sm font-medium">StripePaymentIntentId</label>
              <Input
                value={ stripePaymentIntentId ?? ''}
                onChange={(e) => setStripePaymentIntentId(e.target.value)}
                placeholder="Enter stripePaymentIntentId"
              />
            </div>
            <div>
              <label className="text-sm font-medium">Status</label>
              <select
                className="w-full border rounded-md p-2"
                value={ status ?? ''}
                onChange={(e) => setStatus(e.target.value as any)}
              >
                <option value="pending">pending</option>
                <option value="paid">paid</option>
                <option value="fulfilled">fulfilled</option>
                <option value="cancelled">cancelled</option>
                <option value="refunded">refunded</option>
              </select>
            </div>
            <div>
              <label className="text-sm font-medium">Currency</label>
              <Input
                value={ currency ?? ''}
                onChange={(e) => setCurrency(e.target.value)}
                placeholder="Enter currency"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsEditOpen(false)}>
              Cancel
            </Button>
            <Button onClick={handleUpdate} disabled={isUpdating}>
              {isUpdating ? 'Updating...' : 'Update'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}