/**
 * ProductVariant Admin Page
 * Auto-generated by HEADLESS API Generator
 *
 * Features:
 * - Full CRUD operations
 * - Dummy data generation
 * - Table view with actions
 *
 * Add to App.tsx:
 *   import { ProductVariantAdminPage } from './pages/admin/entities/ProductVariantAdminPage'
 *   <Route path="/admin/productvariants" element={<ProductVariantAdminPage />} />
 */

import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../../components/ui/card'
import { Button } from '../../../components/ui/button'
import { Input } from '../../../components/ui/input'
import { Textarea } from '../../../components/ui/textarea'
import { Badge } from '../../../components/ui/badge'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '../../../components/ui/table'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '../../../components/ui/dialog'
import { useProductVariants } from '../../../hooks/useProductVariants'
import type { ProductVariant } from '../../../models/ProductVariant'

// Dummy data templates - customize these for your entity
const DUMMY_DATA_TEMPLATES = [
  {
    productId: null,
    name: 'Sample Name 1',
    priceAmount: 1,
    currency: 'Sample Currency 1',
    stripePriceId: 'Sample StripePriceId 1',
    metadata: null,
    isDefault: true,
    isActive: true,
    displayOrder: 1,
  },
  {
    productId: null,
    name: 'Sample Name 2',
    priceAmount: 2,
    currency: 'Sample Currency 2',
    stripePriceId: 'Sample StripePriceId 2',
    metadata: null,
    isDefault: true,
    isActive: true,
    displayOrder: 2,
  },
  {
    productId: null,
    name: 'Sample Name 3',
    priceAmount: 3,
    currency: 'Sample Currency 3',
    stripePriceId: 'Sample StripePriceId 3',
    metadata: null,
    isDefault: true,
    isActive: true,
    displayOrder: 3,
  },
]

export function ProductVariantAdminPage() {
  const [isCreateOpen, setIsCreateOpen] = useState(false)
  const [isEditOpen, setIsEditOpen] = useState(false)
  const [editingItem, setEditingItem] = useState<ProductVariant | null>(null)
  const [isGenerating, setIsGenerating] = useState(false)

  // Form state
  const [productId, setProductId] = useState<string>(null)
  const [name, setName] = useState<string>('')
  const [priceAmount, setPriceAmount] = useState<number>(0)
  const [currency, setCurrency] = useState<string>('')
  const [stripePriceId, setStripePriceId] = useState<string>(null)
  const [metadata, setMetadata] = useState<Record<string, any>>(null)
  const [isDefault, setIsDefault] = useState<boolean>(false)
  const [isActive, setIsActive] = useState<boolean>(false)
  const [displayOrder, setDisplayOrder] = useState<number>(null)

  const {
    productvariants,
    isLoading,
    createProductVariant,
    isCreating,
    updateProductVariant,
    isUpdating,
    deleteProductVariant,
    isDeleting,
  } = useProductVariants({ mine: true })

  const resetForm = () => {
    setProductId(null)
    setName('')
    setPriceAmount(0)
    setCurrency('')
    setStripePriceId(null)
    setMetadata(null)
    setIsDefault(false)
    setIsActive(false)
    setDisplayOrder(null)
  }

  const handleCreate = () => {
    createProductVariant({
      productId,
      name,
      priceAmount,
      currency,
      stripePriceId,
      metadata,
      isDefault,
      isActive,
      displayOrder,
    })
    resetForm()
    setIsCreateOpen(false)
  }

  const handleEdit = (item: ProductVariant) => {
    setEditingItem(item)
    setProductId(item.productId)
    setName(item.name)
    setPriceAmount(item.priceAmount)
    setCurrency(item.currency)
    setStripePriceId(item.stripePriceId ?? null)
    setMetadata(item.metadata ?? null)
    setIsDefault(item.isDefault)
    setIsActive(item.isActive)
    setDisplayOrder(item.displayOrder ?? null)
    setIsEditOpen(true)
  }

  const handleUpdate = () => {
    if (!editingItem?.id) return
    updateProductVariant(editingItem.id, {
      productId,
      name,
      priceAmount,
      currency,
      stripePriceId,
      metadata,
      isDefault,
      isActive,
      displayOrder,
    })
    resetForm()
    setEditingItem(null)
    setIsEditOpen(false)
  }

  const handleDelete = (id: string) => {
    if (confirm('Are you sure you want to delete this productvariant?')) {
      deleteProductVariant(id)
    }
  }

  const handleGenerateDummyData = async () => {
    setIsGenerating(true)
    try {
      for (const template of DUMMY_DATA_TEMPLATES) {
        await new Promise<void>((resolve) => {
          createProductVariant(template as any)
          setTimeout(resolve, 300)
        })
      }
    } finally {
      setIsGenerating(false)
    }
  }

  const totalCount = productvariants?.length ?? 0

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold">ProductVariant Management</h1>
          <p className="text-gray-500">Manage productvariants in the system</p>
        </div>
        <div className="flex gap-2">
          <Button
            variant="outline"
            onClick={handleGenerateDummyData}
            disabled={isGenerating}
          >
            {isGenerating ? '🔄 Generating...' : '🎲 Generate Dummy Data'}
          </Button>
          <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
            <DialogTrigger asChild>
              <Button>➕ Create ProductVariant</Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Create New ProductVariant</DialogTitle>
                <DialogDescription>
                  Fill in the details to create a new productvariant.
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-4 py-4">
                <div>
                  <label className="text-sm font-medium">Name</label>
                  <Input
                    value={ name ?? ''}
                    onChange={(e) => setName(e.target.value)}
                    placeholder="Enter name"
                  />
                </div>
                <div>
                  <label className="text-sm font-medium">Currency</label>
                  <Input
                    value={ currency ?? ''}
                    onChange={(e) => setCurrency(e.target.value)}
                    placeholder="Enter currency"
                  />
                </div>
                <div>
                  <label className="text-sm font-medium">StripePriceId</label>
                  <Input
                    value={ stripePriceId ?? ''}
                    onChange={(e) => setStripePriceId(e.target.value)}
                    placeholder="Enter stripePriceId"
                  />
                </div>
              </div>
              <DialogFooter>
                <Button variant="outline" onClick={() => setIsCreateOpen(false)}>
                  Cancel
                </Button>
                <Button onClick={handleCreate} disabled={isCreating}>
                  {isCreating ? 'Creating...' : 'Create'}
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      </div>

      {/* Stats Card */}
      <Card>
        <CardHeader>
          <CardTitle>📊 Statistics</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="bg-blue-50 p-4 rounded-lg">
              <p className="text-2xl font-bold">{totalCount}</p>
              <p className="text-sm text-gray-500">Total ProductVariants</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Table */}
      <Card>
        <CardHeader>
          <CardTitle>📋 ProductVariant List</CardTitle>
          <CardDescription>
            All productvariants in the system
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <p className="text-center py-8 text-gray-500">Loading...</p>
          ) : totalCount === 0 ? (
            <p className="text-center py-8 text-gray-500">
              No productvariants yet. Create one or generate dummy data!
            </p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>ProductId</TableHead>
                  <TableHead>Name</TableHead>
                  <TableHead>PriceAmount</TableHead>
                  <TableHead>Currency</TableHead>
                  <TableHead>Created</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                { productvariants?.map((item) => (
                  <TableRow key={item.id}>
                    <TableCell className="max-w-xs truncate">{item.productId}</TableCell>
                    <TableCell className="max-w-xs truncate">{item.name}</TableCell>
                    <TableCell className="max-w-xs truncate">{item.priceAmount}</TableCell>
                    <TableCell className="max-w-xs truncate">{item.currency}</TableCell>
                    <TableCell className="text-sm text-gray-500">
                      {item.createdAt ? new Date(item.createdAt).toLocaleDateString() : '-'}
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-2">
                        <Button size="sm" variant="outline" onClick={() => handleEdit(item)}>
                          Edit
                        </Button>
                        <Button
                          size="sm"
                          variant="destructive"
                          onClick={() => handleDelete(item.id!)}
                          disabled={isDeleting}
                        >
                          Delete
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {/* Edit Dialog */}
      <Dialog open={isEditOpen} onOpenChange={setIsEditOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Edit ProductVariant</DialogTitle>
            <DialogDescription>
              Update the productvariant details.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div>
              <label className="text-sm font-medium">Name</label>
              <Input
                value={ name ?? ''}
                onChange={(e) => setName(e.target.value)}
                placeholder="Enter name"
              />
            </div>
            <div>
              <label className="text-sm font-medium">Currency</label>
              <Input
                value={ currency ?? ''}
                onChange={(e) => setCurrency(e.target.value)}
                placeholder="Enter currency"
              />
            </div>
            <div>
              <label className="text-sm font-medium">StripePriceId</label>
              <Input
                value={ stripePriceId ?? ''}
                onChange={(e) => setStripePriceId(e.target.value)}
                placeholder="Enter stripePriceId"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsEditOpen(false)}>
              Cancel
            </Button>
            <Button onClick={handleUpdate} disabled={isUpdating}>
              {isUpdating ? 'Updating...' : 'Update'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}