/**
 * Product Admin Page
 * Auto-generated by HEADLESS API Generator
 *
 * Features:
 * - Full CRUD operations
 * - Dummy data generation
 * - Table view with actions
 *
 * Add to App.tsx:
 *   import { ProductAdminPage } from './pages/admin/entities/ProductAdminPage'
 *   <Route path="/admin/products" element={<ProductAdminPage />} />
 */

import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../../components/ui/card'
import { Button } from '../../../components/ui/button'
import { Input } from '../../../components/ui/input'
import { Textarea } from '../../../components/ui/textarea'
import { Badge } from '../../../components/ui/badge'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '../../../components/ui/table'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '../../../components/ui/dialog'
import { useProducts } from '../../../hooks/useProducts'
import type { Product } from '../../../models/Product'

// Dummy data templates - customize these for your entity
const DUMMY_DATA_TEMPLATES = [
  {
    name: 'Sample Name 1',
    description: 'Sample Description 1',
    productType: 'token_pack' as const,
    stripeProductId: 'Sample StripeProductId 1',
    metadata: null,
    imageUrl: 'Sample ImageUrl 1',
    displayOrder: 1,
    isActive: true,
  },
  {
    name: 'Sample Name 2',
    description: 'Sample Description 2',
    productType: 'token_pack' as const,
    stripeProductId: 'Sample StripeProductId 2',
    metadata: null,
    imageUrl: 'Sample ImageUrl 2',
    displayOrder: 2,
    isActive: true,
  },
  {
    name: 'Sample Name 3',
    description: 'Sample Description 3',
    productType: 'token_pack' as const,
    stripeProductId: 'Sample StripeProductId 3',
    metadata: null,
    imageUrl: 'Sample ImageUrl 3',
    displayOrder: 3,
    isActive: true,
  },
]

export function ProductAdminPage() {
  const [isCreateOpen, setIsCreateOpen] = useState(false)
  const [isEditOpen, setIsEditOpen] = useState(false)
  const [editingItem, setEditingItem] = useState<Product | null>(null)
  const [isGenerating, setIsGenerating] = useState(false)

  // Form state
  const [name, setName] = useState<string>('')
  const [description, setDescription] = useState<string>(null)
  const [productType, setProductType] = useState<'token_pack' | 'digital' | 'feature' | 'physical'>('token_pack')
  const [stripeProductId, setStripeProductId] = useState<string>(null)
  const [metadata, setMetadata] = useState<Record<string, any>>(null)
  const [imageUrl, setImageUrl] = useState<string>(null)
  const [displayOrder, setDisplayOrder] = useState<number>(null)
  const [isActive, setIsActive] = useState<boolean>(false)

  const {
    products,
    isLoading,
    createProduct,
    isCreating,
    updateProduct,
    isUpdating,
    deleteProduct,
    isDeleting,
    setProductTypeDigital,
    setProductTypeTokenPack,
  } = useProducts({ mine: true })

  const resetForm = () => {
    setName('')
    setDescription(null)
    setProductType('token_pack')
    setStripeProductId(null)
    setMetadata(null)
    setImageUrl(null)
    setDisplayOrder(null)
    setIsActive(false)
  }

  const handleCreate = () => {
    createProduct({
      name,
      description,
      productType,
      stripeProductId,
      metadata,
      imageUrl,
      displayOrder,
      isActive,
    })
    resetForm()
    setIsCreateOpen(false)
  }

  const handleEdit = (item: Product) => {
    setEditingItem(item)
    setName(item.name)
    setDescription(item.description ?? null)
    setProductType(item.productType)
    setStripeProductId(item.stripeProductId ?? null)
    setMetadata(item.metadata ?? null)
    setImageUrl(item.imageUrl ?? null)
    setDisplayOrder(item.displayOrder ?? null)
    setIsActive(item.isActive)
    setIsEditOpen(true)
  }

  const handleUpdate = () => {
    if (!editingItem?.id) return
    updateProduct(editingItem.id, {
      name,
      description,
      productType,
      stripeProductId,
      metadata,
      imageUrl,
      displayOrder,
      isActive,
    })
    resetForm()
    setEditingItem(null)
    setIsEditOpen(false)
  }

  const handleDelete = (id: string) => {
    if (confirm('Are you sure you want to delete this product?')) {
      deleteProduct(id)
    }
  }

  const handleGenerateDummyData = async () => {
    setIsGenerating(true)
    try {
      for (const template of DUMMY_DATA_TEMPLATES) {
        await new Promise<void>((resolve) => {
          createProduct(template as any)
          setTimeout(resolve, 300)
        })
      }
    } finally {
      setIsGenerating(false)
    }
  }

  const totalCount = products?.length ?? 0

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold">Product Management</h1>
          <p className="text-gray-500">Manage products in the system</p>
        </div>
        <div className="flex gap-2">
          <Button
            variant="outline"
            onClick={handleGenerateDummyData}
            disabled={isGenerating}
          >
            {isGenerating ? '🔄 Generating...' : '🎲 Generate Dummy Data'}
          </Button>
          <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
            <DialogTrigger asChild>
              <Button>➕ Create Product</Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Create New Product</DialogTitle>
                <DialogDescription>
                  Fill in the details to create a new product.
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-4 py-4">
                <div>
                  <label className="text-sm font-medium">Name</label>
                  <Input
                    value={ name ?? ''}
                    onChange={(e) => setName(e.target.value)}
                    placeholder="Enter name"
                  />
                </div>
                <div>
                  <label className="text-sm font-medium">Description</label>
                  <Input
                    value={ description ?? ''}
                    onChange={(e) => setDescription(e.target.value)}
                    placeholder="Enter description"
                  />
                </div>
                <div>
                  <label className="text-sm font-medium">ProductType</label>
                  <select
                    className="w-full border rounded-md p-2"
                    value={ productType ?? ''}
                    onChange={(e) => setProductType(e.target.value as any)}
                  >
                    <option value="token_pack">token_pack</option>
                    <option value="digital">digital</option>
                    <option value="feature">feature</option>
                    <option value="physical">physical</option>
                  </select>
                </div>
                <div>
                  <label className="text-sm font-medium">StripeProductId</label>
                  <Input
                    value={ stripeProductId ?? ''}
                    onChange={(e) => setStripeProductId(e.target.value)}
                    placeholder="Enter stripeProductId"
                  />
                </div>
                <div>
                  <label className="text-sm font-medium">ImageUrl</label>
                  <Input
                    value={ imageUrl ?? ''}
                    onChange={(e) => setImageUrl(e.target.value)}
                    placeholder="Enter imageUrl"
                  />
                </div>
              </div>
              <DialogFooter>
                <Button variant="outline" onClick={() => setIsCreateOpen(false)}>
                  Cancel
                </Button>
                <Button onClick={handleCreate} disabled={isCreating}>
                  {isCreating ? 'Creating...' : 'Create'}
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      </div>

      {/* Stats Card */}
      <Card>
        <CardHeader>
          <CardTitle>📊 Statistics</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="bg-blue-50 p-4 rounded-lg">
              <p className="text-2xl font-bold">{totalCount}</p>
              <p className="text-sm text-gray-500">Total Products</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Table */}
      <Card>
        <CardHeader>
          <CardTitle>📋 Product List</CardTitle>
          <CardDescription>
            All products in the system
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <p className="text-center py-8 text-gray-500">Loading...</p>
          ) : totalCount === 0 ? (
            <p className="text-center py-8 text-gray-500">
              No products yet. Create one or generate dummy data!
            </p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
                  <TableHead>Name</TableHead>
                  <TableHead>Description</TableHead>
                  <TableHead>ProductType</TableHead>
                  <TableHead>StripeProductId</TableHead>
                  <TableHead>Created</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                { products?.map((item) => (
                  <TableRow key={item.id}>
                    <TableCell className="max-w-xs truncate">{item.name}</TableCell>
                    <TableCell className="max-w-xs truncate">{item.description}</TableCell>
                    <TableCell>
                      <Badge variant="secondary">
                        {item.productType}
                      </Badge>
                    </TableCell>
                    <TableCell className="max-w-xs truncate">{item.stripeProductId}</TableCell>
                    <TableCell className="text-sm text-gray-500">
                      {item.createdAt ? new Date(item.createdAt).toLocaleDateString() : '-'}
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-2">
                        <Button size="sm" variant="outline" onClick={() => handleEdit(item)}>
                          Edit
                        </Button>
                        <Button
                          size="sm"
                          variant="secondary"
                          onClick={() => {
                            if (item.productType === 'token_pack') {
                              setProductTypeDigital(item.id!)
                            } else {
                              setProductTypeTokenPack(item.id!)
                            }
                          }}
                        >
                          Toggle ProductType
                        </Button>
                        <Button
                          size="sm"
                          variant="destructive"
                          onClick={() => handleDelete(item.id!)}
                          disabled={isDeleting}
                        >
                          Delete
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {/* Edit Dialog */}
      <Dialog open={isEditOpen} onOpenChange={setIsEditOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Edit Product</DialogTitle>
            <DialogDescription>
              Update the product details.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
            <div>
              <label className="text-sm font-medium">Name</label>
              <Input
                value={ name ?? ''}
                onChange={(e) => setName(e.target.value)}
                placeholder="Enter name"
              />
            </div>
            <div>
              <label className="text-sm font-medium">Description</label>
              <Input
                value={ description ?? ''}
                onChange={(e) => setDescription(e.target.value)}
                placeholder="Enter description"
              />
            </div>
            <div>
              <label className="text-sm font-medium">ProductType</label>
              <select
                className="w-full border rounded-md p-2"
                value={ productType ?? ''}
                onChange={(e) => setProductType(e.target.value as any)}
              >
                <option value="token_pack">token_pack</option>
                <option value="digital">digital</option>
                <option value="feature">feature</option>
                <option value="physical">physical</option>
              </select>
            </div>
            <div>
              <label className="text-sm font-medium">StripeProductId</label>
              <Input
                value={ stripeProductId ?? ''}
                onChange={(e) => setStripeProductId(e.target.value)}
                placeholder="Enter stripeProductId"
              />
            </div>
            <div>
              <label className="text-sm font-medium">ImageUrl</label>
              <Input
                value={ imageUrl ?? ''}
                onChange={(e) => setImageUrl(e.target.value)}
                placeholder="Enter imageUrl"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsEditOpen(false)}>
              Cancel
            </Button>
            <Button onClick={handleUpdate} disabled={isUpdating}>
              {isUpdating ? 'Updating...' : 'Update'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}