/**
 * Products Demo Card
 * Auto-generated by HEADLESS API Generator
 *
 * Usage in ExamplesPage.tsx:
 *   import { ProductsDemo } from '../components/features/products/ProductsDemo'
 *   <ProductsDemo />
 */

import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../ui/card'
import { Button } from '../../ui/button'
import { Input } from '../../ui/input'
import { Textarea } from '../../ui/textarea'
import { Badge } from '../../ui/badge'
import { useProducts } from '../../../hooks/useProducts'
import type { Product } from '../../../models/Product'

export function ProductsDemo() {
  const [name, setName] = useState<string>('')
  const [description, setDescription] = useState<string>(null)
  const [productType, setProductType] = useState<'token_pack' | 'digital' | 'feature' | 'physical'>('token_pack')
  const [stripeProductId, setStripeProductId] = useState<string>(null)
  const [metadata, setMetadata] = useState<Record<string, any>>(null)
  const [imageUrl, setImageUrl] = useState<string>(null)
  const [displayOrder, setDisplayOrder] = useState<number>(null)
  const [isActive, setIsActive] = useState<boolean>(false)
  const [editingId, setEditingId] = useState<string | null>(null)

  const {
    products,
    isLoading,
    createProduct,
    isCreating,
    updateProduct,
    isUpdating,
    deleteProduct,
    isDeleting,
    setProductTypeDigital,
    setProductTypeTokenPack,
  } = useProducts({ mine: true })

  const resetForm = () => {
    setName('')
    setDescription(null)
    setProductType('token_pack')
    setStripeProductId(null)
    setMetadata(null)
    setImageUrl(null)
    setDisplayOrder(null)
    setIsActive(false)
    setEditingId(null)
  }

  const handleCreate = () => {
    createProduct({
      name,
      description,
      productType,
      stripeProductId,
      metadata,
      imageUrl,
      displayOrder,
      isActive,
    })
    resetForm()
  }

  const handleEdit = (item: Product) => {
    setEditingId(item.id)
    setName(item.name)
    setDescription(item.description ?? null)
    setProductType(item.productType)
    setStripeProductId(item.stripeProductId ?? null)
    setMetadata(item.metadata ?? null)
    setImageUrl(item.imageUrl ?? null)
    setDisplayOrder(item.displayOrder ?? null)
    setIsActive(item.isActive)
  }

  const handleUpdate = () => {
    if (!editingId) return
    updateProduct(editingId, {
      name,
      description,
      productType,
      stripeProductId,
      metadata,
      imageUrl,
      displayOrder,
      isActive,
    })
    resetForm()
  }

  const itemCount = products?.length ?? 0

  return (
    <Card className="border-green-200 bg-gradient-to-br from-green-50 to-emerald-50">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <span className="text-2xl">📝</span>
          Products CRUD (HEADLESS API)
        </CardTitle>
        <CardDescription>
          Edge Function + React Query - Full CRUD with RLS
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Code Example */}
        <pre className="bg-gray-50 p-3 rounded-lg text-xs font-mono overflow-x-auto">
          <code>{`// Frontend: React Query Hook
const { products, createProduct, updateProduct } = useProducts()
createProduct({ name: '...', description: '...', productType: '...', stripeProductId: '...', metadata: '...', imageUrl: '...', displayOrder: '...', isActive: '...' })`}</code>
        </pre>

        {/* Create/Edit Form */}
        <div className="bg-white p-4 rounded-lg space-y-3">
          <h3 className="font-semibold text-gray-700">
            {editingId ? '✏️ Edit Product' : '➕ Create Product'}
          </h3>

          <Input
            placeholder="Name"
            value={ name ?? ''}
            onChange={(e) => setName(e.target.value)}
          />

          <Input
            placeholder="Description"
            value={ description ?? ''}
            onChange={(e) => setDescription(e.target.value)}
          />

          <select
            className="w-full border rounded-md p-2"
            value={ productType ?? ''}
            onChange={(e) => setProductType(e.target.value as any)}
          >
            <option value="token_pack">token_pack</option>
            <option value="digital">digital</option>
            <option value="feature">feature</option>
            <option value="physical">physical</option>
          </select>

          <Input
            placeholder="StripeProductId"
            value={ stripeProductId ?? ''}
            onChange={(e) => setStripeProductId(e.target.value)}
          />

          <Input
            placeholder="ImageUrl"
            value={ imageUrl ?? ''}
            onChange={(e) => setImageUrl(e.target.value)}
          />

          <div className="flex gap-2">
            {editingId ? (
              <>
                <Button onClick={handleUpdate} disabled={isUpdating}>
                  {isUpdating ? 'Updating...' : 'Update'}
                </Button>
                <Button variant="outline" onClick={resetForm}>
                  Cancel
                </Button>
              </>
            ) : (
              <Button onClick={handleCreate} disabled={isCreating}>
                {isCreating ? 'Creating...' : 'Create Product'}
              </Button>
            )}
          </div>
        </div>

        {/* List */}
        <div className="bg-white p-4 rounded-lg space-y-3">
          <h3 className="font-semibold text-gray-700">📚 Your Products ({itemCount})</h3>

          {isLoading && (
            <p className="text-sm text-gray-500">Loading products...</p>
          )}

          {!isLoading && itemCount === 0 && (
            <p className="text-sm text-gray-500">No products yet. Create your first one!</p>
          )}

          <div className="space-y-2">
            { products?.map((item) => (
              <div
                key={item.id}
                className="border rounded-lg p-3 space-y-2 hover:bg-gray-50 transition-colors"
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="flex-1 min-w-0">
                    <h4 className="font-medium text-gray-900 truncate">
                      {item.name}
                    </h4>
                    <p className="text-sm text-gray-600 line-clamp-2 mt-1">
                      {item.description}
                    </p>
                  </div>
                  <Badge variant={item.productType === 'token_pack' ? 'secondary' : 'default'}>
                    {item.productType}
                  </Badge>
                </div>

                <div className="flex gap-2 flex-wrap">
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => handleEdit(item)}
                  >
                    Edit
                  </Button>

                  <Button
                    size="sm"
                    variant="secondary"
                    onClick={() => {
                      if (item.productType === 'token_pack') {
                        setProductTypeDigital(item.id!)
                      } else {
                        setProductTypeTokenPack(item.id!)
                      }
                    }}
                  >
                    Toggle ProductType
                  </Button>

                  <Button
                    size="sm"
                    variant="destructive"
                    onClick={() => {
                      if (confirm('Delete this product?')) {
                        deleteProduct(item.id!)
                      }
                    }}
                    disabled={isDeleting}
                  >
                    Delete
                  </Button>
                </div>

                {item.createdAt && (
                  <p className="text-xs text-gray-400">
                    Created: {new Date(item.createdAt).toLocaleDateString()}
                  </p>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Info */}
        <div className="bg-blue-50 p-3 rounded-lg text-sm text-gray-700">
          <p className="font-semibold mb-2">🎯 Features:</p>
          <ul className="list-disc list-inside space-y-1 text-xs">
            <li>✅ Full CRUD operations (Create, Read, Update, Delete)</li>
            <li>✅ RLS Security (Row Level Security)</li>
            <li>✅ Edge Function (createAkatsukiHandler)</li>
            <li>✅ React Query (Automatic cache & invalidation)</li>
            <li>✅ Type-safe (TypeScript + Zod)</li>
          </ul>
        </div>
      </CardContent>
    </Card>
  )
}