/// Admin Page Template
///
/// Generates TypeScript Admin Page with:
/// - CRUD operations with Table/Form UI
/// - Dummy data generation button
/// - Powered by generated hooks

pub const ADMIN_PAGE_TEMPLATE: &str = r##"/**
 * {{ name }} Admin Page
 * Auto-generated by HEADLESS API Generator
 *
 * Features:
 * - Full CRUD operations
 * - Dummy data generation
 * - Table view with actions
 *
 * Add to App.tsx:
 *   import { {{ name }}AdminPage } from './pages/admin/entities/{{ name }}AdminPage'
 *   <Route path="/admin/{{ name | lower }}s" element={<{{ name }}AdminPage />} />
 */

import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../../components/ui/card'
import { Button } from '../../../components/ui/button'
import { Input } from '../../../components/ui/input'
import { Textarea } from '../../../components/ui/textarea'
import { Badge } from '../../../components/ui/badge'
import {
  Table,
  TableBody,
  TableCell,
  TableHead,
  TableHeader,
  TableRow,
} from '../../../components/ui/table'
import {
  Dialog,
  DialogContent,
  DialogDescription,
  DialogFooter,
  DialogHeader,
  DialogTitle,
  DialogTrigger,
} from '../../../components/ui/dialog'
import { use{{ name }}s } from '../../../hooks/use{{ name }}s'
import type { {{ name }} } from '../../../models/{{ name }}'

// Dummy data templates - customize these for your entity
const DUMMY_DATA_TEMPLATES = [
{%- for i in range(3) %}
  {
{%- for field in writable_fields %}
{%- if field.name != "userId" %}
{%- if field.field_type == "string" %}
    {{ field.name }}: 'Sample {{ field.name | pascal_case }} {{ i + 1 }}',
{%- elif field.field_type == "number" %}
    {{ field.name }}: {{ i + 1 }},
{%- elif field.field_type == "boolean" %}
    {{ field.name }}: true,
{%- elif field.field_type == "enum" and field.enum_values | length > 0 %}
    {{ field.name }}: '{{ field.enum_values[0] }}' as const,
{%- elif field.field_type == "array" %}
    {{ field.name }}: [],
{%- else %}
    {{ field.name }}: null,
{%- endif %}
{%- endif %}
{%- endfor %}
  },
{%- endfor %}
]

export function {{ name }}AdminPage() {
  const [isCreateOpen, setIsCreateOpen] = useState(false)
  const [isEditOpen, setIsEditOpen] = useState(false)
  const [editingItem, setEditingItem] = useState<{{ name }} | null>(null)
  const [isGenerating, setIsGenerating] = useState(false)

  // Form state
{%- for field in writable_fields %}
{%- if field.name != "userId" %}
  const [{{ field.name }}, set{{ field.name | pascal_case }}] = useState<{{ field.typescript_type }}>({{ field.typescript_default }})
{%- endif %}
{%- endfor %}

  const {
    {{ name | lower }}s,
    isLoading,
    create{{ name }},
    isCreating,
    update{{ name }},
    isUpdating,
    delete{{ name }},
    isDeleting,
{%- for field in enum_fields %}
{%- if field.enum_values | length >= 2 %}
    set{{ field.name | pascal_case }}{{ field.enum_values[1] | pascal_case }},
    set{{ field.name | pascal_case }}{{ field.enum_values[0] | pascal_case }},
{%- endif %}
{%- endfor %}
  } = use{{ name }}s({ mine: true })

  const resetForm = () => {
{%- for field in writable_fields %}
{%- if field.name != "userId" %}
    set{{ field.name | pascal_case }}({{ field.typescript_default }})
{%- endif %}
{%- endfor %}
  }

  const handleCreate = () => {
    create{{ name }}({
{%- for field in writable_fields %}
{%- if field.name != "userId" %}
      {{ field.name }},
{%- endif %}
{%- endfor %}
    })
    resetForm()
    setIsCreateOpen(false)
  }

  const handleEdit = (item: {{ name }}) => {
    setEditingItem(item)
{%- for field in writable_fields %}
{%- if field.name != "userId" %}
    set{{ field.name | pascal_case }}(item.{{ field.name }}{% if not field.required %} ?? {{ field.typescript_default }}{% endif %})
{%- endif %}
{%- endfor %}
    setIsEditOpen(true)
  }

  const handleUpdate = () => {
    if (!editingItem?.id) return
    update{{ name }}(editingItem.id, {
{%- for field in updatable_fields %}
      {{ field.name }},
{%- endfor %}
    })
    resetForm()
    setEditingItem(null)
    setIsEditOpen(false)
  }

  const handleDelete = (id: string) => {
    if (confirm('Are you sure you want to delete this {{ name | lower }}?')) {
      delete{{ name }}(id)
    }
  }

  const handleGenerateDummyData = async () => {
    setIsGenerating(true)
    try {
      for (const template of DUMMY_DATA_TEMPLATES) {
        await new Promise<void>((resolve) => {
          create{{ name }}(template as any)
          setTimeout(resolve, 300)
        })
      }
    } finally {
      setIsGenerating(false)
    }
  }

  const totalCount = {{ name | lower }}s?.length ?? 0

  return (
    <div className="space-y-6">
      {/* Header */}
      <div className="flex justify-between items-center">
        <div>
          <h1 className="text-2xl font-bold">{{ name }} Management</h1>
          <p className="text-gray-500">Manage {{ name | lower }}s in the system</p>
        </div>
        <div className="flex gap-2">
          <Button
            variant="outline"
            onClick={handleGenerateDummyData}
            disabled={isGenerating}
          >
            {isGenerating ? '🔄 Generating...' : '🎲 Generate Dummy Data'}
          </Button>
          <Dialog open={isCreateOpen} onOpenChange={setIsCreateOpen}>
            <DialogTrigger asChild>
              <Button>➕ Create {{ name }}</Button>
            </DialogTrigger>
            <DialogContent>
              <DialogHeader>
                <DialogTitle>Create New {{ name }}</DialogTitle>
                <DialogDescription>
                  Fill in the details to create a new {{ name | lower }}.
                </DialogDescription>
              </DialogHeader>
              <div className="space-y-4 py-4">
{%- for field in writable_fields %}
{%- if field.name != "userId" %}
{%- if field.name == "content" %}
                <div>
                  <label className="text-sm font-medium">{{ field.name | pascal_case }}</label>
                  <Textarea
                    value={ {{ field.name }} ?? ''}
                    onChange={(e) => set{{ field.name | pascal_case }}(e.target.value)}
                    placeholder="Enter {{ field.name }}"
                    rows={4}
                  />
                </div>
{%- elif field.field_type == "string" %}
                <div>
                  <label className="text-sm font-medium">{{ field.name | pascal_case }}</label>
                  <Input
                    value={ {{ field.name }} ?? ''}
                    onChange={(e) => set{{ field.name | pascal_case }}(e.target.value)}
                    placeholder="Enter {{ field.name }}"
                  />
                </div>
{%- elif field.field_type == "enum" and field.enum_values | length > 0 %}
                <div>
                  <label className="text-sm font-medium">{{ field.name | pascal_case }}</label>
                  <select
                    className="w-full border rounded-md p-2"
                    value={ {{ field.name }} ?? ''}
                    onChange={(e) => set{{ field.name | pascal_case }}(e.target.value as any)}
                  >
{%- for val in field.enum_values %}
                    <option value="{{ val }}">{{ val }}</option>
{%- endfor %}
                  </select>
                </div>
{%- endif %}
{%- endif %}
{%- endfor %}
              </div>
              <DialogFooter>
                <Button variant="outline" onClick={() => setIsCreateOpen(false)}>
                  Cancel
                </Button>
                <Button onClick={handleCreate} disabled={isCreating}>
                  {isCreating ? 'Creating...' : 'Create'}
                </Button>
              </DialogFooter>
            </DialogContent>
          </Dialog>
        </div>
      </div>

      {/* Stats Card */}
      <Card>
        <CardHeader>
          <CardTitle>📊 Statistics</CardTitle>
        </CardHeader>
        <CardContent>
          <div className="grid grid-cols-2 md:grid-cols-4 gap-4">
            <div className="bg-blue-50 p-4 rounded-lg">
              <p className="text-2xl font-bold">{totalCount}</p>
              <p className="text-sm text-gray-500">Total {{ name }}s</p>
            </div>
          </div>
        </CardContent>
      </Card>

      {/* Table */}
      <Card>
        <CardHeader>
          <CardTitle>📋 {{ name }} List</CardTitle>
          <CardDescription>
            All {{ name | lower }}s in the system
          </CardDescription>
        </CardHeader>
        <CardContent>
          {isLoading ? (
            <p className="text-center py-8 text-gray-500">Loading...</p>
          ) : totalCount === 0 ? (
            <p className="text-center py-8 text-gray-500">
              No {{ name | lower }}s yet. Create one or generate dummy data!
            </p>
          ) : (
            <Table>
              <TableHeader>
                <TableRow>
{%- for field in display_fields %}
                  <TableHead>{{ field.name | pascal_case }}</TableHead>
{%- endfor %}
                  <TableHead>Created</TableHead>
                  <TableHead className="text-right">Actions</TableHead>
                </TableRow>
              </TableHeader>
              <TableBody>
                { {{ name | lower }}s?.map((item) => (
                  <TableRow key={item.id}>
{%- for field in display_fields %}
{%- if field.field_type == "enum" %}
                    <TableCell>
                      <Badge variant="secondary">
                        {item.{{ field.name }}}
                      </Badge>
                    </TableCell>
{%- else %}
                    <TableCell className="max-w-xs truncate">{item.{{ field.name }}}</TableCell>
{%- endif %}
{%- endfor %}
                    <TableCell className="text-sm text-gray-500">
                      {item.createdAt ? new Date(item.createdAt).toLocaleDateString() : '-'}
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-2">
                        <Button size="sm" variant="outline" onClick={() => handleEdit(item)}>
                          Edit
                        </Button>
{%- for field in enum_fields %}
{%- if field.enum_values | length >= 2 %}
                        <Button
                          size="sm"
                          variant="secondary"
                          onClick={() => {
                            if (item.{{ field.name }} === '{{ field.enum_values[0] }}') {
                              set{{ field.name | pascal_case }}{{ field.enum_values[1] | pascal_case }}(item.id!)
                            } else {
                              set{{ field.name | pascal_case }}{{ field.enum_values[0] | pascal_case }}(item.id!)
                            }
                          }}
                        >
                          Toggle {{ field.name | pascal_case }}
                        </Button>
{%- endif %}
{%- endfor %}
                        <Button
                          size="sm"
                          variant="destructive"
                          onClick={() => handleDelete(item.id!)}
                          disabled={isDeleting}
                        >
                          Delete
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))}
              </TableBody>
            </Table>
          )}
        </CardContent>
      </Card>

      {/* Edit Dialog */}
      <Dialog open={isEditOpen} onOpenChange={setIsEditOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Edit {{ name }}</DialogTitle>
            <DialogDescription>
              Update the {{ name | lower }} details.
            </DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-4">
{%- for field in updatable_fields %}
{%- if field.name == "content" %}
            <div>
              <label className="text-sm font-medium">{{ field.name | pascal_case }}</label>
              <Textarea
                value={ {{ field.name }} ?? ''}
                onChange={(e) => set{{ field.name | pascal_case }}(e.target.value)}
                placeholder="Enter {{ field.name }}"
                rows={4}
              />
            </div>
{%- elif field.field_type == "string" %}
            <div>
              <label className="text-sm font-medium">{{ field.name | pascal_case }}</label>
              <Input
                value={ {{ field.name }} ?? ''}
                onChange={(e) => set{{ field.name | pascal_case }}(e.target.value)}
                placeholder="Enter {{ field.name }}"
              />
            </div>
{%- elif field.field_type == "enum" and field.enum_values | length > 0 %}
            <div>
              <label className="text-sm font-medium">{{ field.name | pascal_case }}</label>
              <select
                className="w-full border rounded-md p-2"
                value={ {{ field.name }} ?? ''}
                onChange={(e) => set{{ field.name | pascal_case }}(e.target.value as any)}
              >
{%- for val in field.enum_values %}
                <option value="{{ val }}">{{ val }}</option>
{%- endfor %}
              </select>
            </div>
{%- endif %}
{%- endfor %}
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setIsEditOpen(false)}>
              Cancel
            </Button>
            <Button onClick={handleUpdate} disabled={isUpdating}>
              {isUpdating ? 'Updating...' : 'Update'}
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}
"##;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_template_syntax() {
        assert!(ADMIN_PAGE_TEMPLATE.contains("{{ name }}AdminPage"));
        assert!(ADMIN_PAGE_TEMPLATE.contains("use{{ name }}s"));
        assert!(ADMIN_PAGE_TEMPLATE.contains("Generate Dummy Data"));
    }
}
