/// CLI Client Template for app-cli (Node.js)
///
/// Generates JavaScript Client class with:
/// - AkatsukiClient wrapper
/// - CRUD operations
/// - Custom operations from schema
/// - JSDoc type hints

pub const CLI_CLIENT_TEMPLATE: &str = r#"/**
 * {{ name }}s API Client (app-cli)
 * Auto-generated by HEADLESS API Generator
 *
 * Convenience wrapper for {{ table_name }}-crud Edge Function
 * - Supabase Auth integrated
 * - AkatsukiResponse parsing
 *
 * Usage:
 * ```javascript
 * import { AkatsukiClient, {{ name }}sClient } from '../client.js'
 *
 * const client = new AkatsukiClient()
 * await client.login(email, password)
 *
 * const {{ name | lower }}sClient = new {{ name }}sClient(client)
 * const {{ name | lower }}s = await {{ name | lower }}sClient.list()
 * ```
 */

/**
 * {{ name }}s API Client
 */
export class {{ name }}sClient {
  /**
   * @param {import('./client.js').AkatsukiClient} akatsukiClient
   */
  constructor(akatsukiClient) {
    this.client = akatsukiClient
  }
{%- for op in operations %}
{%- if op.op_type == "list" %}

  /**
   * Get {{ name | lower }}s with filters
   * @param {Object} [filters] - Optional filters
{%- for filter in op.filters %}
   * @param {string} [filters.{{ filter }}] - Filter by {{ filter }}
{%- endfor %}
   * @param {number} [limit=20] - Max number of results
   * @returns {Promise<Array>} {{ name }}s array
   */
  async list(filters = {}, limit = 20) {
    return this.client.invoke('{{ table_name }}-crud', {
      action: 'list',
      filters,
      limit,
    })
  }
{%- elif op.op_type == "get" %}

  /**
   * Get {{ name | lower }} by ID
   * @param {string} id - {{ name }} UUID
   * @returns {Promise<Object>} {{ name }} object
   */
  async getById(id) {
    return this.client.invoke('{{ table_name }}-crud', {
      action: 'get',
      id,
    })
  }
{%- elif op.op_type == "create" %}

  /**
   * Create {{ name | lower }}
   * @param {Object} data - {{ name }} data
{%- for field in writable_fields %}
{%- if field.name != "userId" %}
   * @param {{ "{" }}{{ field.typescript_type }}{% if not field.required %}={{ "}" }}{% else %}{{ "}" }}{% endif %} data.{{ field.name }} - {{ field.name }}
{%- endif %}
{%- endfor %}
   * @returns {Promise<Object>} Created {{ name | lower }}
   */
  async create(data) {
    return this.client.invoke('{{ table_name }}-crud', {
      action: 'create',
      data,
    })
  }
{%- elif op.op_type == "update" %}

  /**
   * Update {{ name | lower }}
   * @param {string} id - {{ name }} UUID
   * @param {Object} data - Update data
{%- for field in updatable_fields %}
   * @param {{ "{" }}{{ field.typescript_type }}={{ "}" }} data.{{ field.name }} - {{ field.name }}
{%- endfor %}
   * @returns {Promise<Object>} Updated {{ name | lower }}
   */
  async update(id, data) {
    return this.client.invoke('{{ table_name }}-crud', {
      action: 'update',
      id,
      data,
    })
  }
{%- elif op.op_type == "delete" %}

  /**
   * Delete {{ name | lower }}
   * @param {string} id - {{ name }} UUID
   * @returns {Promise<Object>} Delete result
   */
  async delete(id) {
    return this.client.invoke('{{ table_name }}-crud', {
      action: 'delete',
      id,
    })
  }
{%- elif op.op_type == "custom" %}

  /**
   * {{ op.description | default(value="Custom operation: " ~ op.name) }}
   * @param {Object} [filters] - Optional filters
{%- for filter in op.filters %}
   * @param {string} [filters.{{ filter }}] - Filter by {{ filter }}
{%- endfor %}
{%- if op.limit %}
   * @param {number} [limit={{ op.limit }}] - Max number of results
{%- endif %}
   * @returns {Promise<Array>} {{ name }}s array
   */
  async {{ op.name }}({% if op.filters | length > 0 %}filters = {}{% endif %}{% if op.limit %}{% if op.filters | length > 0 %}, {% endif %}limit = {{ op.limit }}{% endif %}) {
    return this.client.invoke('{{ table_name }}-crud', {
      action: '{{ op.name }}',
{%- if op.filters | length > 0 %}
      filters,
{%- endif %}
{%- if op.limit %}
      limit,
{%- endif %}
    })
  }
{%- endif %}
{%- endfor %}
{%- for field in enum_fields %}
{%- if field.enum_values | length >= 2 %}

  /**
   * Set {{ name | lower }} {{ field.name }} to '{{ field.enum_values[1] }}'
   * @param {string} id - {{ name }} UUID
   * @returns {Promise<Object>} Updated {{ name | lower }}
   */
  async {{ field.enum_values[1] }}(id) {
    return this.update(id, { {{ field.name }}: '{{ field.enum_values[1] }}' })
  }

  /**
   * Set {{ name | lower }} {{ field.name }} to '{{ field.enum_values[0] }}'
   * @param {string} id - {{ name }} UUID
   * @returns {Promise<Object>} Updated {{ name | lower }}
   */
  async un{{ field.enum_values[1] }}(id) {
    return this.update(id, { {{ field.name }}: '{{ field.enum_values[0] }}' })
  }
{%- endif %}
{%- endfor %}
}
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_template_syntax() {
        assert!(CLI_CLIENT_TEMPLATE.contains("{{ name }}sClient"));
        assert!(CLI_CLIENT_TEMPLATE.contains("AkatsukiClient"));
    }
}
