/// CLI Client Template for app-cli (TypeScript)
///
/// Generates TypeScript Client class with:
/// - AkatsukiClient wrapper
/// - CRUD operations
/// - Custom operations from schema
/// - Full type safety

pub const CLI_CLIENT_TEMPLATE: &str = r#"/**
 * {{ name }}s API Client (app-cli)
 * Auto-generated by HEADLESS API Generator
 *
 * Convenience wrapper for {{ table_name }}-crud Edge Function
 * - Supabase Auth integrated
 * - AkatsukiResponse parsing
 * - Full TypeScript support
 *
 * Usage:
 * ```typescript
 * import { AkatsukiClient } from '../client.js'
 * import { {{ name }}sClient } from './{{ name }}sClient.js'
 *
 * const client = new AkatsukiClient()
 * await client.login(email, password)
 *
 * const {{ name | lower }}sClient = new {{ name }}sClient(client)
 * const {{ name | lower }}s = await {{ name | lower }}sClient.list()
 * ```
 */

import { AkatsukiClient } from '../client.js'

/**
 * {{ name }} type
 */
export interface {{ name }} {
  id: string
  user_id: string
{%- for field in writable_fields %}
{%- if field.name != "userId" %}
  {{ field.db_name }}: {{ field.typescript_type }}{% if not field.required %} | null{% endif %}
{%- endif %}
{%- endfor %}
  created_at: string
  updated_at: string
}

/**
 * {{ name }} create input
 */
export interface {{ name }}CreateInput {
{%- for field in writable_fields %}
{%- if field.name != "userId" %}
  {{ field.name }}{% if not field.required %}?{% endif %}: {{ field.typescript_type }}
{%- endif %}
{%- endfor %}
}

/**
 * {{ name }} update input
 */
export interface {{ name }}UpdateInput {
{%- for field in updatable_fields %}
  {{ field.name }}?: {{ field.typescript_type }}
{%- endfor %}
}

/**
 * {{ name }}s API Client
 */
export class {{ name }}sClient {
  constructor(private client: AkatsukiClient) {}
{%- for op in operations %}
{%- if op.op_type == "list" %}

  /**
   * Get {{ name | lower }}s with filters
   */
  async list(
    filters: { {% for filter in op.filters %}{{ filter }}?: string{% if not loop.last %}, {% endif %}{% endfor %} } = {},
    limit: number = 20
  ): Promise<{{ name }}[]> {
    return this.client.invoke<{{ name }}[]>('{{ table_name }}-crud', {
      action: 'list',
      filters,
      limit,
    })
  }
{%- elif op.op_type == "get" %}

  /**
   * Get {{ name | lower }} by ID
   */
  async getById(id: string): Promise<{{ name }}> {
    return this.client.invoke<{{ name }}>('{{ table_name }}-crud', {
      action: 'get',
      id,
    })
  }
{%- elif op.op_type == "create" %}

  /**
   * Create {{ name | lower }}
   */
  async create(data: {{ name }}CreateInput): Promise<{{ name }}> {
    return this.client.invoke<{{ name }}>('{{ table_name }}-crud', {
      action: 'create',
      data,
    })
  }
{%- elif op.op_type == "update" %}

  /**
   * Update {{ name | lower }}
   */
  async update(id: string, data: {{ name }}UpdateInput): Promise<{{ name }}> {
    return this.client.invoke<{{ name }}>('{{ table_name }}-crud', {
      action: 'update',
      id,
      data,
    })
  }
{%- elif op.op_type == "delete" %}

  /**
   * Delete {{ name | lower }}
   */
  async delete(id: string): Promise<{ deleted: boolean }> {
    return this.client.invoke<{ deleted: boolean }>('{{ table_name }}-crud', {
      action: 'delete',
      id,
    })
  }
{%- elif op.op_type == "custom" %}

  /**
   * {{ op.description | default(value="Custom operation: " ~ op.name) }}
   */
  async {{ op.name }}({% if op.filters | length > 0 %}filters: { {% for filter in op.filters %}{{ filter }}?: string{% if not loop.last %}, {% endif %}{% endfor %} } = {}{% endif %}{% if op.limit %}{% if op.filters | length > 0 %}, {% endif %}limit: number = {{ op.limit }}{% endif %}): Promise<{{ name }}[]> {
    return this.client.invoke<{{ name }}[]>('{{ table_name }}-crud', {
      action: '{{ op.name }}',
{%- if op.filters | length > 0 %}
      filters,
{%- endif %}
{%- if op.limit %}
      limit,
{%- endif %}
    })
  }
{%- endif %}
{%- endfor %}
{%- for field in enum_fields %}
{%- if field.enum_values | length >= 2 %}

  /**
   * Set {{ name | lower }} {{ field.name }} to '{{ field.enum_values[1] }}'
   */
  async {{ field.enum_values[1] }}(id: string): Promise<{{ name }}> {
    return this.update(id, { {{ field.name }}: '{{ field.enum_values[1] }}' })
  }

  /**
   * Set {{ name | lower }} {{ field.name }} to '{{ field.enum_values[0] }}'
   */
  async un{{ field.enum_values[1] }}(id: string): Promise<{{ name }}> {
    return this.update(id, { {{ field.name }}: '{{ field.enum_values[0] }}' })
  }
{%- endif %}
{%- endfor %}
}
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_template_syntax() {
        assert!(CLI_CLIENT_TEMPLATE.contains("{{ name }}sClient"));
        assert!(CLI_CLIENT_TEMPLATE.contains("AkatsukiClient"));
        assert!(CLI_CLIENT_TEMPLATE.contains("interface {{ name }}"));
    }
}
