/// Demo Component Template for ExamplesPage
///
/// Generates a Card-style demo component showing:
/// - CRUD operations
/// - Code example
/// - Feature list

pub const DEMO_COMPONENT_TEMPLATE: &str = r##"/**
 * {{ name }}s Demo Card
 * Auto-generated by HEADLESS API Generator
 *
 * Usage in ExamplesPage.tsx:
 *   import { {{ name }}sDemo } from '../components/features/{{ table_name }}/{{ name }}sDemo'
 *   <{{ name }}sDemo />
 */

import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../ui/card'
import { Button } from '../../ui/button'
import { Input } from '../../ui/input'
import { Textarea } from '../../ui/textarea'
import { Badge } from '../../ui/badge'
import { use{{ name }}s } from '../../../hooks/use{{ name }}s'
import type { {{ name }} } from '../../../models/{{ name }}'

export function {{ name }}sDemo() {
{%- for field in writable_fields %}
{%- if field.name != "userId" %}
  const [{{ field.name }}, set{{ field.name | pascal_case }}] = useState<{{ field.typescript_type }}>({{ field.typescript_default }})
{%- endif %}
{%- endfor %}
  const [editingId, setEditingId] = useState<string | null>(null)

  const {
    {{ name | lower }}s,
    isLoading,
    create{{ name }},
    isCreating,
    update{{ name }},
    isUpdating,
    delete{{ name }},
    isDeleting,
{%- for field in enum_fields %}
{%- if field.enum_values | length >= 2 %}
    set{{ field.name | pascal_case }}{{ field.enum_values[1] | pascal_case }},
    set{{ field.name | pascal_case }}{{ field.enum_values[0] | pascal_case }},
{%- endif %}
{%- endfor %}
  } = use{{ name }}s({ mine: true })

  const resetForm = () => {
{%- for field in writable_fields %}
{%- if field.name != "userId" %}
    set{{ field.name | pascal_case }}({{ field.typescript_default }})
{%- endif %}
{%- endfor %}
    setEditingId(null)
  }

  const handleCreate = () => {
    create{{ name }}({
{%- for field in writable_fields %}
{%- if field.name != "userId" %}
      {{ field.name }},
{%- endif %}
{%- endfor %}
    })
    resetForm()
  }

  const handleEdit = (item: {{ name }}) => {
    setEditingId(item.id)
{%- for field in writable_fields %}
{%- if field.name != "userId" %}
    set{{ field.name | pascal_case }}(item.{{ field.name }}{% if not field.required %} ?? {{ field.typescript_default }}{% endif %})
{%- endif %}
{%- endfor %}
  }

  const handleUpdate = () => {
    if (!editingId) return
    update{{ name }}(editingId, {
{%- for field in updatable_fields %}
      {{ field.name }},
{%- endfor %}
    })
    resetForm()
  }

  const itemCount = {{ name | lower }}s?.length ?? 0

  return (
    <Card className="border-green-200 bg-gradient-to-br from-green-50 to-emerald-50">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <span className="text-2xl">📝</span>
          {{ name }}s CRUD (HEADLESS API)
        </CardTitle>
        <CardDescription>
          Edge Function + React Query - Full CRUD with RLS
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Code Example */}
        <pre className="bg-gray-50 p-3 rounded-lg text-xs font-mono overflow-x-auto">
          <code>{`// Frontend: React Query Hook
const { {{ name | lower }}s, create{{ name }}, update{{ name }} } = use{{ name }}s()
create{{ name }}({ {% for field in writable_fields %}{% if field.name != "userId" %}{{ field.name }}: '...'{% if not loop.last %}, {% endif %}{% endif %}{% endfor %} })`}</code>
        </pre>

        {/* Create/Edit Form */}
        <div className="bg-white p-4 rounded-lg space-y-3">
          <h3 className="font-semibold text-gray-700">
            {editingId ? '✏️ Edit {{ name }}' : '➕ Create {{ name }}'}
          </h3>
{%- for field in writable_fields %}
{%- if field.name != "userId" %}
{%- if field.name == "content" %}

          <Textarea
            placeholder="{{ field.name | pascal_case }}"
            value={ {{ field.name }} ?? ''}
            onChange={(e) => set{{ field.name | pascal_case }}(e.target.value)}
            rows={4}
          />
{%- elif field.field_type == "string" %}

          <Input
            placeholder="{{ field.name | pascal_case }}"
            value={ {{ field.name }} ?? ''}
            onChange={(e) => set{{ field.name | pascal_case }}(e.target.value)}
          />
{%- elif field.field_type == "enum" and field.enum_values | length > 0 %}

          <select
            className="w-full border rounded-md p-2"
            value={ {{ field.name }} ?? ''}
            onChange={(e) => set{{ field.name | pascal_case }}(e.target.value as any)}
          >
{%- for val in field.enum_values %}
            <option value="{{ val }}">{{ val }}</option>
{%- endfor %}
          </select>
{%- endif %}
{%- endif %}
{%- endfor %}

          <div className="flex gap-2">
            {editingId ? (
              <>
                <Button onClick={handleUpdate} disabled={isUpdating}>
                  {isUpdating ? 'Updating...' : 'Update'}
                </Button>
                <Button variant="outline" onClick={resetForm}>
                  Cancel
                </Button>
              </>
            ) : (
              <Button onClick={handleCreate} disabled={isCreating}>
                {isCreating ? 'Creating...' : 'Create {{ name }}'}
              </Button>
            )}
          </div>
        </div>

        {/* List */}
        <div className="bg-white p-4 rounded-lg space-y-3">
          <h3 className="font-semibold text-gray-700">📚 Your {{ name }}s ({itemCount})</h3>

          {isLoading && (
            <p className="text-sm text-gray-500">Loading {{ name | lower }}s...</p>
          )}

          {!isLoading && itemCount === 0 && (
            <p className="text-sm text-gray-500">No {{ name | lower }}s yet. Create your first one!</p>
          )}

          <div className="space-y-2">
            { {{ name | lower }}s?.map((item) => (
              <div
                key={item.id}
                className="border rounded-lg p-3 space-y-2 hover:bg-gray-50 transition-colors"
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="flex-1 min-w-0">
{%- for field in display_fields %}
{%- if loop.first %}
                    <h4 className="font-medium text-gray-900 truncate">
                      {item.{{ field.name }}}
                    </h4>
{%- elif field.field_type == "string" %}
                    <p className="text-sm text-gray-600 line-clamp-2 mt-1">
                      {item.{{ field.name }}}
                    </p>
{%- endif %}
{%- endfor %}
                  </div>
{%- for field in enum_fields %}
                  <Badge variant={item.{{ field.name }} === '{{ field.enum_values[0] }}' ? 'secondary' : 'default'}>
                    {item.{{ field.name }}}
                  </Badge>
{%- endfor %}
                </div>

                <div className="flex gap-2 flex-wrap">
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => handleEdit(item)}
                  >
                    Edit
                  </Button>
{%- for field in enum_fields %}
{%- if field.enum_values | length >= 2 %}

                  <Button
                    size="sm"
                    variant="secondary"
                    onClick={() => {
                      if (item.{{ field.name }} === '{{ field.enum_values[0] }}') {
                        set{{ field.name | pascal_case }}{{ field.enum_values[1] | pascal_case }}(item.id!)
                      } else {
                        set{{ field.name | pascal_case }}{{ field.enum_values[0] | pascal_case }}(item.id!)
                      }
                    }}
                  >
                    Toggle {{ field.name | pascal_case }}
                  </Button>
{%- endif %}
{%- endfor %}

                  <Button
                    size="sm"
                    variant="destructive"
                    onClick={() => {
                      if (confirm('Delete this {{ name | lower }}?')) {
                        delete{{ name }}(item.id!)
                      }
                    }}
                    disabled={isDeleting}
                  >
                    Delete
                  </Button>
                </div>

                {item.createdAt && (
                  <p className="text-xs text-gray-400">
                    Created: {new Date(item.createdAt).toLocaleDateString()}
                  </p>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Info */}
        <div className="bg-blue-50 p-3 rounded-lg text-sm text-gray-700">
          <p className="font-semibold mb-2">🎯 Features:</p>
          <ul className="list-disc list-inside space-y-1 text-xs">
            <li>✅ Full CRUD operations (Create, Read, Update, Delete)</li>
            <li>✅ RLS Security (Row Level Security)</li>
            <li>✅ Edge Function (createAkatsukiHandler)</li>
            <li>✅ React Query (Automatic cache & invalidation)</li>
            <li>✅ Type-safe (TypeScript + Zod)</li>
          </ul>
        </div>
      </CardContent>
    </Card>
  )
}
"##;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_template_syntax() {
        assert!(DEMO_COMPONENT_TEMPLATE.contains("{{ name }}sDemo"));
        assert!(DEMO_COMPONENT_TEMPLATE.contains("use{{ name }}s"));
    }
}
