/**
 * Edge Function Template (minijinja)
 * Generates TypeScript Edge Function handler
 */

pub const EDGE_FUNCTION_TEMPLATE: &str = r#"/**
 * {{ name }} CRUD Edge Function
 *
 * Auto-generated by HEADLESS API Generator
 * - VibeCoding標準パターン (createAkatsukiHandler)
 * - Zod Validation
 * - Repository DI
 * - RLS対応
 *
 * Supported Actions:
{%- for op in operations %}
 * - {{ op.op_type }}{% if op.name %} ({{ op.name }}){% endif %}{% if op.description %}: {{ op.description }}{% endif %}
{%- endfor %}
 */

import { createAkatsukiHandler } from '../_shared/handler.ts'
import { {{ name }}Repository } from '../_shared/repositories/{{ name }}Repository.ts'
import { {{ name }}CrudSchema, type {{ name }}CrudInput } from './schema.ts'

Deno.serve(async (req) => {
  return createAkatsukiHandler<{{ name }}CrudInput, any>(req, {
    inputSchema: {{ name }}CrudSchema,
    logic: async ({ input, userClient, adminClient, repos }) => {
      // Create Repository with userClient (RLS enabled)
      const {{ table_name|singular }}Repo = new {{ name }}Repository(userClient)

      switch (input.action) {
{%- for op in operations %}
  {%- if op.op_type == "list" %}
        case 'list': {
          // Get {{ table_name }} with filters
          return {{ table_name|singular }}Repo.findAll({
            {%- for filter in op.filters %}
            {{ filter }}: input.filters?.{{ filter }},
            {%- endfor %}
            limit: input.limit || 20,
          })
        }
  {%- elif op.op_type == "get" %}
        case 'get': {
          // Get {{ table_name|singular }} by ID
          const {{ table_name|singular }} = await {{ table_name|singular }}Repo.findById(input.id)
          if (!{{ table_name|singular }}) {
            throw Object.assign(new Error('{{ name }} not found'), {
              status: 404,
              code: '{{ name|snake_case|upper }}_NOT_FOUND',
            })
          }
          return {{ table_name|singular }}
        }
  {%- elif op.op_type == "create" %}
        case 'create': {
          // Create new {{ table_name|singular }}
          const user = await {{ table_name|singular }}Repo.getCurrentUser()
          return {{ table_name|singular }}Repo.create({
            user_id: user.id,
            {%- for field in writable_fields %}
            {%- if field.name != "userId" %}
            {{ field.name }}: input.data.{{ field.name }}{% if not field.required %} || {{ field.typescript_default }}{% endif %},
            {%- endif %}
            {%- endfor %}
          })
        }
  {%- elif op.op_type == "update" %}
        case 'update': {
          // Update {{ table_name|singular }}
          const {{ table_name|singular }} = await {{ table_name|singular }}Repo.findById(input.id)
          if (!{{ table_name|singular }}) {
            throw Object.assign(new Error('{{ name }} not found'), {
              status: 404,
              code: '{{ name|snake_case|upper }}_NOT_FOUND',
            })
          }

          return {{ table_name|singular }}Repo.update(input.id, input.data)
        }
  {%- elif op.op_type == "delete" %}
        case 'delete': {
          // Delete {{ table_name|singular }}
          const {{ table_name|singular }} = await {{ table_name|singular }}Repo.findById(input.id)
          if (!{{ table_name|singular }}) {
            throw Object.assign(new Error('{{ name }} not found'), {
              status: 404,
              code: '{{ name|snake_case|upper }}_NOT_FOUND',
            })
          }

          await {{ table_name|singular }}Repo.delete(input.id)
          return { success: true, message: '{{ name }} deleted' }
        }
  {%- elif op.op_type == "custom" %}
        case '{{ op.name }}': {
          // {{ op.description|default(value=op.name ~ " operation") }}
          return {{ table_name|singular }}Repo.{{ op.name }}(
            {%- if op.filters|length > 0 %}{
              {%- for filter in op.filters %}
              {{ filter }}: input.filters?.{{ filter }},
              {%- endfor %}
            }{% endif %}
          )
        }
  {%- endif %}
{%- endfor %}

        default:
          throw Object.assign(new Error('Invalid action'), {
            status: 400,
            code: 'INVALID_ACTION',
          })
      }
    },
  })
})

/* To invoke locally:

  1. Run `supabase start`
  2. Make an HTTP request:

{%- for op in operations %}
  {%- if op.op_type == "list" %}
  # List {{ table_name }}
  curl -i --location --request POST 'http://127.0.0.1:54321/functions/v1/{{ table_name }}-crud' \
    --header 'Authorization: Bearer YOUR_JWT_TOKEN' \
    --header 'Content-Type: application/json' \
    --data '{"action":"list","limit":10}'
  {%- elif op.op_type == "create" %}

  # Create {{ table_name|singular }}
  curl -i --location --request POST 'http://127.0.0.1:54321/functions/v1/{{ table_name }}-crud' \
    --header 'Authorization: Bearer YOUR_JWT_TOKEN' \
    --header 'Content-Type: application/json' \
    --data '{"action":"create","data":{"title":"Example","content":"Content here"}}'
  {%- elif op.op_type == "custom" and op.name == "my" %}

  # Get my {{ table_name }}
  curl -i --location --request POST 'http://127.0.0.1:54321/functions/v1/{{ table_name }}-crud' \
    --header 'Authorization: Bearer YOUR_JWT_TOKEN' \
    --header 'Content-Type: application/json' \
    --data '{"action":"my"}'
  {%- endif %}
{%- endfor %}

*/
"#;
