/**
 * Migration Template (minijinja)
 * Generates SQL migration file
 */

pub const MIGRATION_TEMPLATE: &str = r#"-- Create {{ table_name }} table
-- Auto-generated by HEADLESS API Generator

-- ============================================================
-- 1. Create {{ table_name }} table
-- ============================================================

CREATE TABLE IF NOT EXISTS public.{{ table_name }} (
{%- for field in fields %}
  {{ field.db_name }} {{ field.sql_type }}
  {%- if field.required %} NOT NULL{% endif %}
  {%- if field.default %} DEFAULT {{ field.default }}{% endif %}
  {%- if field.primary_key %} PRIMARY KEY{% endif %}
  {%- if field.unique %} UNIQUE{% endif %}
  {%- if field.references %} REFERENCES {{ field.references }}{% if field.on_delete %} ON DELETE {{ field.on_delete }}{% endif %}{% endif %}
  {%- if field.enum_values %} CHECK ({{ field.db_name }} IN ({% for val in field.enum_values %}'{{ val }}'{% if not loop.last %}, {% endif %}{% endfor %})){% endif %}
  {%- if not loop.last %},{% endif %}
{%- endfor %}
);

-- ============================================================
-- 2. Create indexes for performance
-- ============================================================
{% for field in indexed_fields %}
{%- if field.index_type == "gin" %}
CREATE INDEX IF NOT EXISTS idx_{{ table_name }}_{{ field.db_name }} ON public.{{ table_name }} USING GIN({{ field.db_name }});
{%- else %}
CREATE INDEX IF NOT EXISTS idx_{{ table_name }}_{{ field.db_name }} ON public.{{ table_name }}({{ field.db_name }});
{%- endif %}
{% endfor %}
-- ============================================================
-- 3. Enable Row Level Security (RLS)
-- ============================================================

ALTER TABLE public.{{ table_name }} ENABLE ROW LEVEL SECURITY;

-- ============================================================
-- 4. RLS Policies
-- ============================================================
{% for policy in rls %}
CREATE POLICY "{{ policy.name }}"
  ON public.{{ table_name }}
  FOR {{ policy.action }}
  {%- if policy.using %}
  USING ({{ policy.using }})
  {%- endif %}
  {%- if policy.with_check %}
  WITH CHECK ({{ policy.with_check }})
  {%- endif %};
{% endfor %}
-- ============================================================
-- 5. Trigger for updated_at
-- ============================================================
{% if has_updated_at %}
CREATE OR REPLACE FUNCTION public.update_{{ table_name }}_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

CREATE TRIGGER update_{{ table_name }}_updated_at_trigger
  BEFORE UPDATE ON public.{{ table_name }}
  FOR EACH ROW
  EXECUTE FUNCTION public.update_{{ table_name }}_updated_at();
{% endif %}
-- ============================================================
-- 6. Comments (Documentation)
-- ============================================================

COMMENT ON TABLE public.{{ table_name }} IS '{{ documentation.description|default(value=name ~ " table") }}';
{%- for field in fields %}
COMMENT ON COLUMN public.{{ table_name }}.{{ field.db_name }} IS '{{ field.name }}';
{%- endfor %}
"#;
