/// Model Template for Frontend
///
/// Generates TypeScript Model class with:
/// - Type definitions (Data interface, DatabaseRecord interface)
/// - Constructor with defaults
/// - fromDatabase() - Convert DB record to Model
/// - toDatabase() - Convert Model to DB record for INSERT
/// - toUpdateDatabase() - Convert Model to DB record for UPDATE
/// - Enum status helpers (if applicable)

pub const MODEL_TEMPLATE: &str = r#"/**
 * {{ name }} Model
 * Auto-generated by HEADLESS API Generator
 *
 * VibeCoding標準パターン:
 * - fromDatabase/toDatabase 変換
 * - RLS対応
 */

{%- for field in enum_fields %}
export type {{ name }}{{ field.name | pascal_case }} = {% for val in field.enum_values %}'{{ val }}'{% if not loop.last %} | {% endif %}{% endfor %}

{% endfor %}

export interface {{ name }}Data {
  id?: string | null
{%- for field in writable_fields %}
  {{ field.name }}{% if not field.required %}?{% endif %}: {{ field.typescript_type }}{% if not field.required %} | null{% endif %}
{%- endfor %}
  createdAt?: string | null
  updatedAt?: string | null
}

export interface {{ name }}DatabaseRecord {
  id: string
{%- for field in fields %}
{%- if field.name != "id" and field.name != "createdAt" and field.name != "updatedAt" %}
  {{ field.db_name }}: {{ field.typescript_type }}
{%- endif %}
{%- endfor %}
  created_at: string
  updated_at: string
}

export class {{ name }} {
  id: string | null
{%- for field in fields %}
{%- if field.name != "id" and field.name != "createdAt" and field.name != "updatedAt" %}
  {{ field.name }}: {{ field.typescript_type }}{% if not field.required %} | null{% endif %}
{%- endif %}
{%- endfor %}
  createdAt: string | null
  updatedAt: string | null

  constructor({
    id = null,
{%- for field in writable_fields %}
    {{ field.name }}{% if not field.required %} = {{ field.typescript_default }}{% endif %},
{%- endfor %}
    createdAt = null,
    updatedAt = null,
  }: {{ name }}Data) {
    this.id = id
{%- for field in writable_fields %}
    this.{{ field.name }} = {{ field.name }}
{%- endfor %}
    this.createdAt = createdAt
    this.updatedAt = updatedAt
  }

  /**
   * Convert database record to Model instance
   */
  static fromDatabase(data: {{ name }}DatabaseRecord): {{ name }} {
    return new {{ name }}({
      id: data.id,
{%- for field in fields %}
{%- if field.name != "id" and field.name != "createdAt" and field.name != "updatedAt" %}
      {{ field.name }}: data.{{ field.db_name }}{% if field.typescript_type == "string[]" %} || []{% endif %},
{%- endif %}
{%- endfor %}
      createdAt: data.created_at,
      updatedAt: data.updated_at,
    })
  }

  /**
   * Convert to database format for INSERT
   */
  toDatabase() {
    return {
{%- for field in writable_fields %}
      {{ field.db_name }}: this.{{ field.name }},
{%- endfor %}
    }
  }

  /**
   * Convert to database format for UPDATE (excludes user_id)
   */
  toUpdateDatabase() {
    return {
{%- for field in updatable_fields %}
      {{ field.db_name }}: this.{{ field.name }},
{%- endfor %}
    }
  }
{%- for field in enum_fields %}

  /**
   * Check if {{ field.name }} is '{{ field.enum_values[0] }}'
   */
  is{{ field.enum_values[0] | pascal_case }}(): boolean {
    return this.{{ field.name }} === '{{ field.enum_values[0] }}'
  }
{%- if field.enum_values | length > 1 %}

  /**
   * Check if {{ field.name }} is '{{ field.enum_values[1] }}'
   */
  is{{ field.enum_values[1] | pascal_case }}(): boolean {
    return this.{{ field.name }} === '{{ field.enum_values[1] }}'
  }
{%- endif %}
{%- endfor %}
}
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_template_syntax() {
        // Basic syntax check
        assert!(MODEL_TEMPLATE.contains("{{ name }}"));
        assert!(MODEL_TEMPLATE.contains("fromDatabase"));
        assert!(MODEL_TEMPLATE.contains("toDatabase"));
    }
}
