/// Service Template for Frontend
///
/// Generates TypeScript Service class with:
/// - EdgeFunctionService wrapper
/// - Type-safe API calls
/// - CRUD operations (list, get, create, update, delete)
/// - Custom operations from schema

pub const SERVICE_TEMPLATE: &str = r#"/**
 * {{ name }} Service
 * Auto-generated by HEADLESS API Generator
 *
 * {{ table_name }}-crud Edge Function の呼び出しを管理
 * - EdgeFunctionService wrapper
 * - Type-safe API calls
 * - AkatsukiResponse対応
 */

import { EdgeFunctionService } from './EdgeFunctionService'
import type { {{ name }}DatabaseRecord } from '../models/{{ name }}'

export class {{ name }}Service {
{%- for op in operations %}
{%- if op.op_type == "get" %}

  /**
   * Get {{ name | lower }} by ID
   */
  static async getById(id: string) {
    return EdgeFunctionService.invoke<{{ name }}DatabaseRecord>('{{ table_name }}-crud', {
      action: 'get',
      id,
    })
  }
{%- elif op.op_type == "list" %}

  /**
   * Get {{ name | lower }}s with filters
   */
  static async list(filters?: {
{%- for filter in op.filters %}
    {{ filter }}?: string
{%- endfor %}
    limit?: number
  }) {
    return EdgeFunctionService.invoke<{{ name }}DatabaseRecord[]>('{{ table_name }}-crud', {
      action: 'list',
      filters,
      limit: filters?.limit,
    })
  }
{%- elif op.op_type == "create" %}

  /**
   * Create new {{ name | lower }}
   */
  static async create(data: {
{%- for field in writable_fields %}
{%- if field.name != "userId" %}
    {{ field.name }}{% if not field.required %}?{% endif %}: {{ field.typescript_type }}
{%- endif %}
{%- endfor %}
  }) {
    return EdgeFunctionService.invoke<{{ name }}DatabaseRecord>('{{ table_name }}-crud', {
      action: 'create',
      data,
    })
  }
{%- elif op.op_type == "update" %}

  /**
   * Update {{ name | lower }}
   */
  static async update(
    id: string,
    data: {
{%- for field in updatable_fields %}
      {{ field.name }}?: {{ field.typescript_type }}
{%- endfor %}
    }
  ) {
    return EdgeFunctionService.invoke<{{ name }}DatabaseRecord>('{{ table_name }}-crud', {
      action: 'update',
      id,
      data,
    })
  }
{%- elif op.op_type == "delete" %}

  /**
   * Delete {{ name | lower }}
   */
  static async delete(id: string) {
    return EdgeFunctionService.invoke<{ success: boolean; message: string }>('{{ table_name }}-crud', {
      action: 'delete',
      id,
    })
  }
{%- elif op.op_type == "custom" %}

  /**
   * {{ op.description | default(value="Custom operation") }}
   */
  static async {{ op.name }}({% if op.filters | length > 0 %}filters?: {
{%- for filter in op.filters %}
    {{ filter }}?: string
{%- endfor %}
  }{% if op.limit %}, limit: number = {{ op.limit }}{% endif %}{% elif op.limit %}limit: number = {{ op.limit }}{% endif %}) {
    return EdgeFunctionService.invoke<{{ name }}DatabaseRecord[]>('{{ table_name }}-crud', {
      action: '{{ op.name }}',
{%- if op.filters | length > 0 %}
      filters,
{%- endif %}
{%- if op.limit %}
      limit,
{%- endif %}
    })
  }
{%- endif %}
{%- endfor %}
{%- for field in enum_fields %}
{%- if field.enum_values | length >= 2 %}

  /**
   * Set {{ name | lower }} {{ field.name }} to '{{ field.enum_values[1] }}'
   */
  static async set{{ field.name | pascal_case }}{{ field.enum_values[1] | pascal_case }}(id: string) {
    return this.update(id, { {{ field.name }}: '{{ field.enum_values[1] }}' })
  }

  /**
   * Set {{ name | lower }} {{ field.name }} to '{{ field.enum_values[0] }}'
   */
  static async set{{ field.name | pascal_case }}{{ field.enum_values[0] | pascal_case }}(id: string) {
    return this.update(id, { {{ field.name }}: '{{ field.enum_values[0] }}' })
  }
{%- endif %}
{%- endfor %}
}
"#;

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_template_syntax() {
        assert!(SERVICE_TEMPLATE.contains("{{ name }}Service"));
        assert!(SERVICE_TEMPLATE.contains("EdgeFunctionService"));
    }
}
