/**
 * Zod Schema Template (minijinja)
 * Generates TypeScript Zod validation schema for Edge Function
 */

pub const ZOD_SCHEMA_TEMPLATE: &str = r#"import { z } from 'https://deno.land/x/zod@v3.23.8/mod.ts'

/**
 * {{ name }} Schema for CRUD operations
 * Auto-generated by HEADLESS API Generator
 */

// Enum schemas
{%- for field in enum_fields %}
export const {{ field.name }}Schema = z.enum([{% for val in field.enum_values %}'{{ val }}'{% if not loop.last %}, {% endif %}{% endfor %}])
{% endfor %}
// {{ name }} object schema
export const {{ name }}Schema = z.object({
{%- for field in fields %}
  {{ field.name }}: {{ field.zod_type }},
{%- endfor %}
})

// Input schemas for each CRUD operation
export const {{ name }}CrudSchema = z.discriminatedUnion('action', [
{%- for op in operations %}
  {%- if op.op_type == "list" %}
  // List {{ table_name }}
  z.object({
    action: z.literal('list'),
    {%- if op.filters|length > 0 %}
    filters: z.object({
      {%- for filter in op.filters %}
      {%- set filter_field = fields|selectattr("name", "equalto", filter)|first %}
      {%- if filter_field %}
      {{ filter }}: {{ filter_field.zod_type }}.optional(),
      {%- else %}
      {{ filter }}: z.string().optional(),
      {%- endif %}
      {%- endfor %}
    }).optional(),
    {%- endif %}
    {%- if op.limit %}
    limit: z.number().int().positive().max({{ op.limit }}).optional(),
    {%- endif %}
  }),
  {%- elif op.op_type == "get" %}
  // Get {{ table_name|singular }} by ID
  z.object({
    action: z.literal('get'),
    id: z.string().uuid(),
  }),
  {%- elif op.op_type == "create" %}
  // Create {{ table_name|singular }}
  z.object({
    action: z.literal('create'),
    data: z.object({
      {%- for field in writable_fields %}
      {{ field.name }}: {{ field.zod_type }}{% if not field.required %}.optional(){% endif %},
      {%- endfor %}
    }),
  }),
  {%- elif op.op_type == "update" %}
  // Update {{ table_name|singular }}
  z.object({
    action: z.literal('update'),
    id: z.string().uuid(),
    data: z.object({
      {%- for field in updatable_fields %}
      {{ field.name }}: {{ field.zod_type }}.optional(),
      {%- endfor %}
    }),
  }),
  {%- elif op.op_type == "delete" %}
  // Delete {{ table_name|singular }}
  z.object({
    action: z.literal('delete'),
    id: z.string().uuid(),
  }),
  {%- elif op.op_type == "custom" %}
  // {{ op.description|default(value=op.name ~ " operation") }}
  z.object({
    action: z.literal('{{ op.name }}'),
    {%- if op.filters|length > 0 %}
    filters: z.object({
      {%- for filter in op.filters %}
      {%- set filter_field = fields|selectattr("name", "equalto", filter)|first %}
      {%- if filter_field %}
      {{ filter }}: {{ filter_field.zod_type }}.optional(),
      {%- else %}
      {{ filter }}: z.string().optional(),
      {%- endif %}
      {%- endfor %}
    }).optional(),
    {%- endif %}
    {%- if op.limit %}
    limit: z.number().int().positive().max({{ op.limit }}).optional(),
    {%- endif %}
  }),
  {%- endif %}
{%- endfor %}
])

export type {{ name }}CrudInput = z.infer<typeof {{ name }}CrudSchema>
{%- for field in enum_fields %}
export type {{ field.name }} = z.infer<typeof {{ field.name }}Schema>
{%- endfor %}
"#;
