/**
 * Order CRUD Edge Function
 *
 * Auto-generated by HEADLESS API Generator
 * - VibeCoding標準パターン (createAkatsukiHandler)
 * - Zod Validation
 * - Repository DI
 * - RLS対応
 *
 * Supported Actions:
 * - list
 * - get
 * - create
 * - update
 * - custom (my): Get current user's orders
 */

import { createAkatsukiHandler } from '../_shared/handler.ts'
import { OrderRepository } from '../_shared/repositories/OrderRepository.ts'
import { OrderCrudSchema, type OrderCrudInput } from './schema.ts'

Deno.serve(async (req) => {
  return createAkatsukiHandler<OrderCrudInput, any>(req, {
    inputSchema: OrderCrudSchema,
    logic: async ({ input, userClient, adminClient, repos }) => {
      // Create Repository with userClient (RLS enabled)
      const orderRepo = new OrderRepository(userClient)

      switch (input.action) {
        case 'list': {
          // Get orders with filters
          return orderRepo.findAll({
            status: input.filters?.status,
            userId: input.filters?.userId,
            limit: input.limit || 20,
          })
        }
        case 'get': {
          // Get order by ID
          const order = await orderRepo.findById(input.id)
          if (!order) {
            throw Object.assign(new Error('Order not found'), {
              status: 404,
              code: 'ORDER_NOT_FOUND',
            })
          }
          return order
        }
        case 'create': {
          // Create new order
          const user = await orderRepo.getCurrentUser()
          return orderRepo.create({
            user_id: user.id,
            stripe_checkout_session_id: input.data.stripeCheckoutSessionId || null,
            stripe_payment_intent_id: input.data.stripePaymentIntentId || null,
            status: input.data.status,
            total_amount: input.data.totalAmount,
            currency: input.data.currency,
            metadata: input.data.metadata || null,
            fulfilled_at: input.data.fulfilledAt || null,
          })
        }
        case 'update': {
          // Update order
          const order = await orderRepo.findById(input.id)
          if (!order) {
            throw Object.assign(new Error('Order not found'), {
              status: 404,
              code: 'ORDER_NOT_FOUND',
            })
          }

          return orderRepo.update(input.id, input.data)
        }
        case 'my': {
          // Get current user's orders
          return orderRepo.my({
              status: input.filters?.status,
            }
          )
        }

        default:
          throw Object.assign(new Error('Invalid action'), {
            status: 400,
            code: 'INVALID_ACTION',
          })
      }
    },
  })
})

/* To invoke locally:

  1. Run `supabase start`
  2. Make an HTTP request:
  # List orders
  curl -i --location --request POST 'http://127.0.0.1:54321/functions/v1/orders-crud' \
    --header 'Authorization: Bearer YOUR_JWT_TOKEN' \
    --header 'Content-Type: application/json' \
    --data '{"action":"list","limit":10}'

  # Create order
  curl -i --location --request POST 'http://127.0.0.1:54321/functions/v1/orders-crud' \
    --header 'Authorization: Bearer YOUR_JWT_TOKEN' \
    --header 'Content-Type: application/json' \
    --data '{"action":"create","data":{"title":"Example","content":"Content here"}}'

  # Get my orders
  curl -i --location --request POST 'http://127.0.0.1:54321/functions/v1/orders-crud' \
    --header 'Authorization: Bearer YOUR_JWT_TOKEN' \
    --header 'Content-Type: application/json' \
    --data '{"action":"my"}'

*/