import { z } from 'https://deno.land/x/zod@v3.23.8/mod.ts'

/**
 * Order Schema for CRUD operations
 * Auto-generated by HEADLESS API Generator
 */

// Enum schemas
export const statusSchema = z.enum(['pending', 'paid', 'fulfilled', 'cancelled', 'refunded'])

// Order object schema
export const OrderSchema = z.object({
  id: z.string().uuid(),
  userId: z.string().uuid(),
  createdAt: z.string(),
  updatedAt: z.string(),
  stripeCheckoutSessionId: z.string(),
  stripePaymentIntentId: z.string(),
  status: z.enum(['pending', 'paid', 'fulfilled', 'cancelled', 'refunded']),
  totalAmount: z.number(),
  currency: z.string(),
  metadata: z.record(z.any()),
  fulfilledAt: z.string(),
})

// Input schemas for each CRUD operation
export const OrderCrudSchema = z.discriminatedUnion('action', [
  // List orders
  z.object({
    action: z.literal('list'),
    filters: z.object({
      userId: z.string().uuid().optional(),
    }).optional(),
    limit: z.number().int().positive().max(100).optional(),
  }),
  // Get order by ID
  z.object({
    action: z.literal('get'),
    id: z.string().uuid(),
  }),
  // Create order
  z.object({
    action: z.literal('create'),
    data: z.object({
      userId: z.string().uuid().optional(),
      stripeCheckoutSessionId: z.string().optional(),
      stripePaymentIntentId: z.string().optional(),
      status: z.enum(['pending', 'paid', 'fulfilled', 'cancelled', 'refunded']),
      totalAmount: z.number(),
      currency: z.string(),
      metadata: z.record(z.any()).optional(),
      fulfilledAt: z.string().optional(),
    }),
  }),
  // Update order
  z.object({
    action: z.literal('update'),
    id: z.string().uuid(),
    data: z.object({
      stripeCheckoutSessionId: z.string().optional(),
      stripePaymentIntentId: z.string().optional(),
      status: z.enum(['pending', 'paid', 'fulfilled', 'cancelled', 'refunded']).optional(),
      totalAmount: z.number().optional(),
      currency: z.string().optional(),
      metadata: z.record(z.any()).optional(),
      fulfilledAt: z.string().optional(),
    }),
  }),
  // Get current user's orders
  z.object({
    action: z.literal('my'),
  }),
])

export type OrderCrudInput = z.infer<typeof OrderCrudSchema>
export type status = z.infer<typeof statusSchema>