# Homebrew Formula for Akatsuki CLI
# Auto-generated by GitHub Actions

class Akatsuki < Formula
  desc "VibeCoding Development CLI for Akatsuki projects"
  homepage "https://github.com/ynishi/akatsuki"
  version "0.1.0"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/ynishi/akatsuki/releases/download/cli-v#{version}/akatsuki-aarch64-apple-darwin.tar.gz"
      sha256 "af2c81c798193540cc612ba08e1d993fb04f6a3dccac5484df0b92b23e613197"
    end
    on_intel do
      url "https://github.com/ynishi/akatsuki/releases/download/cli-v#{version}/akatsuki-x86_64-apple-darwin.tar.gz"
      sha256 "1a729c9642dcad59bad554e0e1a5b89dc22617bdeae258edf72249669673c7ae"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/ynishi/akatsuki/releases/download/cli-v#{version}/akatsuki-x86_64-unknown-linux-gnu.tar.gz"
      sha256 "2249f56a6e2866db16b8ac4c9f0f4c2547de33c032caf4dc98aa8298d7ccc4ff"
    end
  end

  def install
    bin.install "akatsuki"
  end

  test do
    system "#{bin}/akatsuki", "--version"
  end
end
