/**
 * Fulfillment Model
 * Auto-generated by HEADLESS API Generator
 *
 * VibeCoding標準パターン:
 * - fromDatabase/toDatabase 変換
 * - RLS対応
 */
export type FulfillmentStatus = 'pending' | 'completed' | 'failed'



export interface FulfillmentData {
  id?: string | null
  orderItemId: string
  fulfillmentType: string
  status: 'pending' | 'completed' | 'failed'
  result?: Record<string, any> | null
  errorMessage?: string | null
  completedAt?: string | null
  createdAt?: string | null
  updatedAt?: string | null
}

export interface FulfillmentDatabaseRecord {
  id: string
  order_item_id: string
  fulfillment_type: string
  status: 'pending' | 'completed' | 'failed'
  result: Record<string, any> | null
  error_message: string | null
  completed_at: string | null
  created_at: string
  updated_at: string
}

export class Fulfillment {
  id: string | null
  orderItemId: string
  fulfillmentType: string
  status: 'pending' | 'completed' | 'failed'
  result: Record<string, any> | null
  errorMessage: string | null
  completedAt: string | null
  createdAt: string | null
  updatedAt: string | null

  constructor({
    id = null,
    orderItemId,
    fulfillmentType,
    status,
    result = null,
    errorMessage = null,
    completedAt = null,
    createdAt = null,
    updatedAt = null,
  }: FulfillmentData) {
    this.id = id
    this.orderItemId = orderItemId
    this.fulfillmentType = fulfillmentType
    this.status = status
    this.result = result
    this.errorMessage = errorMessage
    this.completedAt = completedAt
    this.createdAt = createdAt
    this.updatedAt = updatedAt
  }

  /**
   * Convert database record to Model instance
   */
  static fromDatabase(data: FulfillmentDatabaseRecord): Fulfillment {
    return new Fulfillment({
      id: data.id,
      orderItemId: data.order_item_id,
      fulfillmentType: data.fulfillment_type,
      status: data.status,
      result: data.result,
      errorMessage: data.error_message,
      completedAt: data.completed_at,
      createdAt: data.created_at,
      updatedAt: data.updated_at,
    })
  }

  /**
   * Convert to database format for INSERT
   */
  toDatabase() {
    return {
      order_item_id: this.orderItemId,
      fulfillment_type: this.fulfillmentType,
      status: this.status,
      result: this.result,
      error_message: this.errorMessage,
      completed_at: this.completedAt,
    }
  }

  /**
   * Convert to database format for UPDATE (excludes user_id)
   */
  toUpdateDatabase() {
    return {
      order_item_id: this.orderItemId,
      fulfillment_type: this.fulfillmentType,
      status: this.status,
      result: this.result,
      error_message: this.errorMessage,
      completed_at: this.completedAt,
    }
  }

  /**
   * Check if status is 'pending'
   */
  isPending(): boolean {
    return this.status === 'pending'
  }

  /**
   * Check if status is 'completed'
   */
  isCompleted(): boolean {
    return this.status === 'completed'
  }
}