/**
 * OrderItem Model
 * Auto-generated by HEADLESS API Generator
 *
 * VibeCoding標準パターン:
 * - fromDatabase/toDatabase 変換
 * - RLS対応
 */

export interface OrderItemData {
  id?: string | null
  orderId: string
  productId?: string | null
  variantId?: string | null
  productName: string
  variantName?: string | null
  quantity: number
  unitPrice: number
  subtotal: number
  productType: string
  productMetadata?: Record<string, any> | null
  createdAt?: string | null
  updatedAt?: string | null
}

export interface OrderItemDatabaseRecord {
  id: string
  order_id: string
  product_id: string | null
  variant_id: string | null
  product_name: string
  variant_name: string | null
  quantity: number
  unit_price: number
  subtotal: number
  product_type: string
  product_metadata: Record<string, any> | null
  created_at: string
  updated_at: string
}

export class OrderItem {
  id: string | null
  orderId: string
  productId: string | null
  variantId: string | null
  productName: string
  variantName: string | null
  quantity: number
  unitPrice: number
  subtotal: number
  productType: string
  productMetadata: Record<string, any> | null
  createdAt: string | null
  updatedAt: string | null

  constructor({
    id = null,
    orderId,
    productId = null,
    variantId = null,
    productName,
    variantName = null,
    quantity,
    unitPrice,
    subtotal,
    productType,
    productMetadata = null,
    createdAt = null,
    updatedAt = null,
  }: OrderItemData) {
    this.id = id
    this.orderId = orderId
    this.productId = productId
    this.variantId = variantId
    this.productName = productName
    this.variantName = variantName
    this.quantity = quantity
    this.unitPrice = unitPrice
    this.subtotal = subtotal
    this.productType = productType
    this.productMetadata = productMetadata
    this.createdAt = createdAt
    this.updatedAt = updatedAt
  }

  /**
   * Convert database record to Model instance
   */
  static fromDatabase(data: OrderItemDatabaseRecord): OrderItem {
    return new OrderItem({
      id: data.id,
      orderId: data.order_id,
      productId: data.product_id,
      variantId: data.variant_id,
      productName: data.product_name,
      variantName: data.variant_name,
      quantity: data.quantity,
      unitPrice: data.unit_price,
      subtotal: data.subtotal,
      productType: data.product_type,
      productMetadata: data.product_metadata,
      createdAt: data.created_at,
      updatedAt: data.updated_at,
    })
  }

  /**
   * Convert to database format for INSERT
   */
  toDatabase() {
    return {
      order_id: this.orderId,
      product_id: this.productId,
      variant_id: this.variantId,
      product_name: this.productName,
      variant_name: this.variantName,
      quantity: this.quantity,
      unit_price: this.unitPrice,
      subtotal: this.subtotal,
      product_type: this.productType,
      product_metadata: this.productMetadata,
    }
  }

  /**
   * Convert to database format for UPDATE (excludes user_id)
   */
  toUpdateDatabase() {
    return {
      order_id: this.orderId,
      product_id: this.productId,
      variant_id: this.variantId,
      product_name: this.productName,
      variant_name: this.variantName,
      quantity: this.quantity,
      unit_price: this.unitPrice,
      subtotal: this.subtotal,
      product_type: this.productType,
      product_metadata: this.productMetadata,
    }
  }
}