/**
 * Order Model
 * Auto-generated by HEADLESS API Generator
 *
 * VibeCoding標準パターン:
 * - fromDatabase/toDatabase 変換
 * - RLS対応
 */
export type OrderStatus = 'pending' | 'paid' | 'fulfilled' | 'cancelled' | 'refunded'



export interface OrderData {
  id?: string | null
  userId?: string | null
  stripeCheckoutSessionId?: string | null
  stripePaymentIntentId?: string | null
  status: 'pending' | 'paid' | 'fulfilled' | 'cancelled' | 'refunded'
  totalAmount: number
  currency: string
  metadata?: Record<string, any> | null
  fulfilledAt?: string | null
  createdAt?: string | null
  updatedAt?: string | null
}

export interface OrderDatabaseRecord {
  id: string
  user_id: string | null
  stripe_checkout_session_id: string | null
  stripe_payment_intent_id: string | null
  status: 'pending' | 'paid' | 'fulfilled' | 'cancelled' | 'refunded'
  total_amount: number
  currency: string
  metadata: Record<string, any> | null
  fulfilled_at: string | null
  created_at: string
  updated_at: string
}

export class Order {
  id: string | null
  userId: string | null
  stripeCheckoutSessionId: string | null
  stripePaymentIntentId: string | null
  status: 'pending' | 'paid' | 'fulfilled' | 'cancelled' | 'refunded'
  totalAmount: number
  currency: string
  metadata: Record<string, any> | null
  fulfilledAt: string | null
  createdAt: string | null
  updatedAt: string | null

  constructor({
    id = null,
    userId = null,
    stripeCheckoutSessionId = null,
    stripePaymentIntentId = null,
    status,
    totalAmount,
    currency,
    metadata = null,
    fulfilledAt = null,
    createdAt = null,
    updatedAt = null,
  }: OrderData) {
    this.id = id
    this.userId = userId
    this.stripeCheckoutSessionId = stripeCheckoutSessionId
    this.stripePaymentIntentId = stripePaymentIntentId
    this.status = status
    this.totalAmount = totalAmount
    this.currency = currency
    this.metadata = metadata
    this.fulfilledAt = fulfilledAt
    this.createdAt = createdAt
    this.updatedAt = updatedAt
  }

  /**
   * Convert database record to Model instance
   */
  static fromDatabase(data: OrderDatabaseRecord): Order {
    return new Order({
      id: data.id,
      userId: data.user_id,
      stripeCheckoutSessionId: data.stripe_checkout_session_id,
      stripePaymentIntentId: data.stripe_payment_intent_id,
      status: data.status,
      totalAmount: data.total_amount,
      currency: data.currency,
      metadata: data.metadata,
      fulfilledAt: data.fulfilled_at,
      createdAt: data.created_at,
      updatedAt: data.updated_at,
    })
  }

  /**
   * Convert to database format for INSERT
   */
  toDatabase() {
    return {
      user_id: this.userId,
      stripe_checkout_session_id: this.stripeCheckoutSessionId,
      stripe_payment_intent_id: this.stripePaymentIntentId,
      status: this.status,
      total_amount: this.totalAmount,
      currency: this.currency,
      metadata: this.metadata,
      fulfilled_at: this.fulfilledAt,
    }
  }

  /**
   * Convert to database format for UPDATE (excludes user_id)
   */
  toUpdateDatabase() {
    return {
      stripe_checkout_session_id: this.stripeCheckoutSessionId,
      stripe_payment_intent_id: this.stripePaymentIntentId,
      status: this.status,
      total_amount: this.totalAmount,
      currency: this.currency,
      metadata: this.metadata,
      fulfilled_at: this.fulfilledAt,
    }
  }

  /**
   * Check if status is 'pending'
   */
  isPending(): boolean {
    return this.status === 'pending'
  }

  /**
   * Check if status is 'paid'
   */
  isPaid(): boolean {
    return this.status === 'paid'
  }
}