/**
 * ProductVariant Model
 * Auto-generated by HEADLESS API Generator
 *
 * VibeCoding標準パターン:
 * - fromDatabase/toDatabase 変換
 * - RLS対応
 */

export interface ProductVariantData {
  id?: string | null
  productId: string
  name: string
  priceAmount: number
  currency: string
  stripePriceId?: string | null
  metadata?: Record<string, any> | null
  isDefault: boolean
  isActive: boolean
  displayOrder?: number | null
  createdAt?: string | null
  updatedAt?: string | null
}

export interface ProductVariantDatabaseRecord {
  id: string
  product_id: string
  name: string
  price_amount: number
  currency: string
  stripe_price_id: string | null
  metadata: Record<string, any> | null
  is_default: boolean
  is_active: boolean
  display_order: number | null
  created_at: string
  updated_at: string
}

export class ProductVariant {
  id: string | null
  productId: string
  name: string
  priceAmount: number
  currency: string
  stripePriceId: string | null
  metadata: Record<string, any> | null
  isDefault: boolean
  isActive: boolean
  displayOrder: number | null
  createdAt: string | null
  updatedAt: string | null

  constructor({
    id = null,
    productId,
    name,
    priceAmount,
    currency,
    stripePriceId = null,
    metadata = null,
    isDefault,
    isActive,
    displayOrder = null,
    createdAt = null,
    updatedAt = null,
  }: ProductVariantData) {
    this.id = id
    this.productId = productId
    this.name = name
    this.priceAmount = priceAmount
    this.currency = currency
    this.stripePriceId = stripePriceId
    this.metadata = metadata
    this.isDefault = isDefault
    this.isActive = isActive
    this.displayOrder = displayOrder
    this.createdAt = createdAt
    this.updatedAt = updatedAt
  }

  /**
   * Convert database record to Model instance
   */
  static fromDatabase(data: ProductVariantDatabaseRecord): ProductVariant {
    return new ProductVariant({
      id: data.id,
      productId: data.product_id,
      name: data.name,
      priceAmount: data.price_amount,
      currency: data.currency,
      stripePriceId: data.stripe_price_id,
      metadata: data.metadata,
      isDefault: data.is_default,
      isActive: data.is_active,
      displayOrder: data.display_order,
      createdAt: data.created_at,
      updatedAt: data.updated_at,
    })
  }

  /**
   * Convert to database format for INSERT
   */
  toDatabase() {
    return {
      product_id: this.productId,
      name: this.name,
      price_amount: this.priceAmount,
      currency: this.currency,
      stripe_price_id: this.stripePriceId,
      metadata: this.metadata,
      is_default: this.isDefault,
      is_active: this.isActive,
      display_order: this.displayOrder,
    }
  }

  /**
   * Convert to database format for UPDATE (excludes user_id)
   */
  toUpdateDatabase() {
    return {
      product_id: this.productId,
      name: this.name,
      price_amount: this.priceAmount,
      currency: this.currency,
      stripe_price_id: this.stripePriceId,
      metadata: this.metadata,
      is_default: this.isDefault,
      is_active: this.isActive,
      display_order: this.displayOrder,
    }
  }
}