/**
 * Product Model
 * Auto-generated by HEADLESS API Generator
 *
 * VibeCoding標準パターン:
 * - fromDatabase/toDatabase 変換
 * - RLS対応
 */
export type ProductProductType = 'token_pack' | 'digital' | 'feature' | 'physical'



export interface ProductData {
  id?: string | null
  name: string
  description?: string | null
  productType: 'token_pack' | 'digital' | 'feature' | 'physical'
  stripeProductId?: string | null
  metadata?: Record<string, any> | null
  imageUrl?: string | null
  displayOrder?: number | null
  isActive: boolean
  createdAt?: string | null
  updatedAt?: string | null
}

export interface ProductDatabaseRecord {
  id: string
  name: string
  description: string | null
  product_type: 'token_pack' | 'digital' | 'feature' | 'physical'
  stripe_product_id: string | null
  metadata: Record<string, any> | null
  image_url: string | null
  display_order: number | null
  is_active: boolean
  created_at: string
  updated_at: string
}

export class Product {
  id: string | null
  name: string
  description: string | null
  productType: 'token_pack' | 'digital' | 'feature' | 'physical'
  stripeProductId: string | null
  metadata: Record<string, any> | null
  imageUrl: string | null
  displayOrder: number | null
  isActive: boolean
  createdAt: string | null
  updatedAt: string | null

  constructor({
    id = null,
    name,
    description = null,
    productType,
    stripeProductId = null,
    metadata = null,
    imageUrl = null,
    displayOrder = null,
    isActive,
    createdAt = null,
    updatedAt = null,
  }: ProductData) {
    this.id = id
    this.name = name
    this.description = description
    this.productType = productType
    this.stripeProductId = stripeProductId
    this.metadata = metadata
    this.imageUrl = imageUrl
    this.displayOrder = displayOrder
    this.isActive = isActive
    this.createdAt = createdAt
    this.updatedAt = updatedAt
  }

  /**
   * Convert database record to Model instance
   */
  static fromDatabase(data: ProductDatabaseRecord): Product {
    return new Product({
      id: data.id,
      name: data.name,
      description: data.description,
      productType: data.product_type,
      stripeProductId: data.stripe_product_id,
      metadata: data.metadata,
      imageUrl: data.image_url,
      displayOrder: data.display_order,
      isActive: data.is_active,
      createdAt: data.created_at,
      updatedAt: data.updated_at,
    })
  }

  /**
   * Convert to database format for INSERT
   */
  toDatabase() {
    return {
      name: this.name,
      description: this.description,
      product_type: this.productType,
      stripe_product_id: this.stripeProductId,
      metadata: this.metadata,
      image_url: this.imageUrl,
      display_order: this.displayOrder,
      is_active: this.isActive,
    }
  }

  /**
   * Convert to database format for UPDATE (excludes user_id)
   */
  toUpdateDatabase() {
    return {
      name: this.name,
      description: this.description,
      product_type: this.productType,
      stripe_product_id: this.stripeProductId,
      metadata: this.metadata,
      image_url: this.imageUrl,
      display_order: this.displayOrder,
      is_active: this.isActive,
    }
  }

  /**
   * Check if productType is 'token_pack'
   */
  isTokenPack(): boolean {
    return this.productType === 'token_pack'
  }

  /**
   * Check if productType is 'digital'
   */
  isDigital(): boolean {
    return this.productType === 'digital'
  }
}