/**
 * ProductVariants Demo Card
 * Auto-generated by HEADLESS API Generator
 *
 * Usage in ExamplesPage.tsx:
 *   import { ProductVariantsDemo } from '../components/features/product_variants/ProductVariantsDemo'
 *   <ProductVariantsDemo />
 */

import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../ui/card'
import { Button } from '../../ui/button'
import { Input } from '../../ui/input'
import { Textarea } from '../../ui/textarea'
import { Badge } from '../../ui/badge'
import { useProductVariants } from '../../../hooks/useProductVariants'
import type { ProductVariant } from '../../../models/ProductVariant'

export function ProductVariantsDemo() {
  const [productId, setProductId] = useState<string>(null)
  const [name, setName] = useState<string>('')
  const [priceAmount, setPriceAmount] = useState<number>(0)
  const [currency, setCurrency] = useState<string>('')
  const [stripePriceId, setStripePriceId] = useState<string>(null)
  const [metadata, setMetadata] = useState<Record<string, any>>(null)
  const [isDefault, setIsDefault] = useState<boolean>(false)
  const [isActive, setIsActive] = useState<boolean>(false)
  const [displayOrder, setDisplayOrder] = useState<number>(null)
  const [editingId, setEditingId] = useState<string | null>(null)

  const {
    productvariants,
    isLoading,
    createProductVariant,
    isCreating,
    updateProductVariant,
    isUpdating,
    deleteProductVariant,
    isDeleting,
  } = useProductVariants({ mine: true })

  const resetForm = () => {
    setProductId(null)
    setName('')
    setPriceAmount(0)
    setCurrency('')
    setStripePriceId(null)
    setMetadata(null)
    setIsDefault(false)
    setIsActive(false)
    setDisplayOrder(null)
    setEditingId(null)
  }

  const handleCreate = () => {
    createProductVariant({
      productId,
      name,
      priceAmount,
      currency,
      stripePriceId,
      metadata,
      isDefault,
      isActive,
      displayOrder,
    })
    resetForm()
  }

  const handleEdit = (item: ProductVariant) => {
    setEditingId(item.id)
    setProductId(item.productId)
    setName(item.name)
    setPriceAmount(item.priceAmount)
    setCurrency(item.currency)
    setStripePriceId(item.stripePriceId ?? null)
    setMetadata(item.metadata ?? null)
    setIsDefault(item.isDefault)
    setIsActive(item.isActive)
    setDisplayOrder(item.displayOrder ?? null)
  }

  const handleUpdate = () => {
    if (!editingId) return
    updateProductVariant(editingId, {
      productId,
      name,
      priceAmount,
      currency,
      stripePriceId,
      metadata,
      isDefault,
      isActive,
      displayOrder,
    })
    resetForm()
  }

  const itemCount = productvariants?.length ?? 0

  return (
    <Card className="border-green-200 bg-gradient-to-br from-green-50 to-emerald-50">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <span className="text-2xl">📝</span>
          ProductVariants CRUD (HEADLESS API)
        </CardTitle>
        <CardDescription>
          Edge Function + React Query - Full CRUD with RLS
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Code Example */}
        <pre className="bg-gray-50 p-3 rounded-lg text-xs font-mono overflow-x-auto">
          <code>{`// Frontend: React Query Hook
const { productvariants, createProductVariant, updateProductVariant } = useProductVariants()
createProductVariant({ productId: '...', name: '...', priceAmount: '...', currency: '...', stripePriceId: '...', metadata: '...', isDefault: '...', isActive: '...', displayOrder: '...' })`}</code>
        </pre>

        {/* Create/Edit Form */}
        <div className="bg-white p-4 rounded-lg space-y-3">
          <h3 className="font-semibold text-gray-700">
            {editingId ? '✏️ Edit ProductVariant' : '➕ Create ProductVariant'}
          </h3>

          <Input
            placeholder="Name"
            value={ name ?? ''}
            onChange={(e) => setName(e.target.value)}
          />

          <Input
            placeholder="Currency"
            value={ currency ?? ''}
            onChange={(e) => setCurrency(e.target.value)}
          />

          <Input
            placeholder="StripePriceId"
            value={ stripePriceId ?? ''}
            onChange={(e) => setStripePriceId(e.target.value)}
          />

          <div className="flex gap-2">
            {editingId ? (
              <>
                <Button onClick={handleUpdate} disabled={isUpdating}>
                  {isUpdating ? 'Updating...' : 'Update'}
                </Button>
                <Button variant="outline" onClick={resetForm}>
                  Cancel
                </Button>
              </>
            ) : (
              <Button onClick={handleCreate} disabled={isCreating}>
                {isCreating ? 'Creating...' : 'Create ProductVariant'}
              </Button>
            )}
          </div>
        </div>

        {/* List */}
        <div className="bg-white p-4 rounded-lg space-y-3">
          <h3 className="font-semibold text-gray-700">📚 Your ProductVariants ({itemCount})</h3>

          {isLoading && (
            <p className="text-sm text-gray-500">Loading productvariants...</p>
          )}

          {!isLoading && itemCount === 0 && (
            <p className="text-sm text-gray-500">No productvariants yet. Create your first one!</p>
          )}

          <div className="space-y-2">
            { productvariants?.map((item) => (
              <div
                key={item.id}
                className="border rounded-lg p-3 space-y-2 hover:bg-gray-50 transition-colors"
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="flex-1 min-w-0">
                    <h4 className="font-medium text-gray-900 truncate">
                      {item.productId}
                    </h4>
                    <p className="text-sm text-gray-600 line-clamp-2 mt-1">
                      {item.name}
                    </p>
                  </div>
                </div>

                <div className="flex gap-2 flex-wrap">
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => handleEdit(item)}
                  >
                    Edit
                  </Button>

                  <Button
                    size="sm"
                    variant="destructive"
                    onClick={() => {
                      if (confirm('Delete this productvariant?')) {
                        deleteProductVariant(item.id!)
                      }
                    }}
                    disabled={isDeleting}
                  >
                    Delete
                  </Button>
                </div>

                {item.createdAt && (
                  <p className="text-xs text-gray-400">
                    Created: {new Date(item.createdAt).toLocaleDateString()}
                  </p>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Info */}
        <div className="bg-blue-50 p-3 rounded-lg text-sm text-gray-700">
          <p className="font-semibold mb-2">🎯 Features:</p>
          <ul className="list-disc list-inside space-y-1 text-xs">
            <li>✅ Full CRUD operations (Create, Read, Update, Delete)</li>
            <li>✅ RLS Security (Row Level Security)</li>
            <li>✅ Edge Function (createAkatsukiHandler)</li>
            <li>✅ React Query (Automatic cache & invalidation)</li>
            <li>✅ Type-safe (TypeScript + Zod)</li>
          </ul>
        </div>
      </CardContent>
    </Card>
  )
}