/**
 * Fulfillment CRUD Edge Function
 *
 * Auto-generated by HEADLESS API Generator
 * - VibeCoding標準パターン (createAkatsukiHandler)
 * - Zod Validation
 * - Repository DI
 * - RLS対応
 *
 * Supported Actions:
 * - list
 * - get
 * - create
 * - update
 */

import { createAkatsukiHandler } from '../_shared/handler.ts'
import { FulfillmentRepository } from '../_shared/repositories/FulfillmentRepository.ts'
import { FulfillmentCrudSchema, type FulfillmentCrudInput } from './schema.ts'

Deno.serve(async (req) => {
  return createAkatsukiHandler<FulfillmentCrudInput, any>(req, {
    inputSchema: FulfillmentCrudSchema,
    logic: async ({ input, userClient, adminClient, repos }) => {
      // Create Repository with userClient (RLS enabled)
      const fulfillmentRepo = new FulfillmentRepository(userClient)

      switch (input.action) {
        case 'list': {
          // Get fulfillments with filters
          return fulfillmentRepo.findAll({
            status: input.filters?.status,
            fulfillmentType: input.filters?.fulfillmentType,
            limit: input.limit || 20,
          })
        }
        case 'get': {
          // Get fulfillment by ID
          const fulfillment = await fulfillmentRepo.findById(input.id)
          if (!fulfillment) {
            throw Object.assign(new Error('Fulfillment not found'), {
              status: 404,
              code: 'FULFILLMENT_NOT_FOUND',
            })
          }
          return fulfillment
        }
        case 'create': {
          // Create new fulfillment
          const user = await fulfillmentRepo.getCurrentUser()
          return fulfillmentRepo.create({
            user_id: user.id,
            order_item_id: input.data.orderItemId,
            fulfillment_type: input.data.fulfillmentType,
            status: input.data.status,
            result: input.data.result || null,
            error_message: input.data.errorMessage || null,
            completed_at: input.data.completedAt || null,
          })
        }
        case 'update': {
          // Update fulfillment
          const fulfillment = await fulfillmentRepo.findById(input.id)
          if (!fulfillment) {
            throw Object.assign(new Error('Fulfillment not found'), {
              status: 404,
              code: 'FULFILLMENT_NOT_FOUND',
            })
          }

          return fulfillmentRepo.update(input.id, input.data)
        }

        default:
          throw Object.assign(new Error('Invalid action'), {
            status: 400,
            code: 'INVALID_ACTION',
          })
      }
    },
  })
})

/* To invoke locally:

  1. Run `supabase start`
  2. Make an HTTP request:
  # List fulfillments
  curl -i --location --request POST 'http://127.0.0.1:54321/functions/v1/fulfillments-crud' \
    --header 'Authorization: Bearer YOUR_JWT_TOKEN' \
    --header 'Content-Type: application/json' \
    --data '{"action":"list","limit":10}'

  # Create fulfillment
  curl -i --location --request POST 'http://127.0.0.1:54321/functions/v1/fulfillments-crud' \
    --header 'Authorization: Bearer YOUR_JWT_TOKEN' \
    --header 'Content-Type: application/json' \
    --data '{"action":"create","data":{"title":"Example","content":"Content here"}}'

*/