import { z } from 'https://deno.land/x/zod@v3.23.8/mod.ts'

/**
 * Fulfillment Schema for CRUD operations
 * Auto-generated by HEADLESS API Generator
 */

// Enum schemas
export const statusSchema = z.enum(['pending', 'completed', 'failed'])

// Fulfillment object schema
export const FulfillmentSchema = z.object({
  id: z.string().uuid(),
  orderItemId: z.string().uuid(),
  createdAt: z.string(),
  fulfillmentType: z.string(),
  status: z.enum(['pending', 'completed', 'failed']),
  result: z.record(z.any()),
  errorMessage: z.string(),
  completedAt: z.string(),
})

// Input schemas for each CRUD operation
export const FulfillmentCrudSchema = z.discriminatedUnion('action', [
  // List fulfillments
  z.object({
    action: z.literal('list'),
    filters: z.object({
      fulfillmentType: z.string().optional(),
    }).optional(),
    limit: z.number().int().positive().max(100).optional(),
  }),
  // Get fulfillment by ID
  z.object({
    action: z.literal('get'),
    id: z.string().uuid(),
  }),
  // Create fulfillment
  z.object({
    action: z.literal('create'),
    data: z.object({
      orderItemId: z.string().uuid(),
      fulfillmentType: z.string(),
      status: z.enum(['pending', 'completed', 'failed']),
      result: z.record(z.any()).optional(),
      errorMessage: z.string().optional(),
      completedAt: z.string().optional(),
    }),
  }),
  // Update fulfillment
  z.object({
    action: z.literal('update'),
    id: z.string().uuid(),
    data: z.object({
      orderItemId: z.string().uuid().optional(),
      fulfillmentType: z.string().optional(),
      status: z.enum(['pending', 'completed', 'failed']).optional(),
      result: z.record(z.any()).optional(),
      errorMessage: z.string().optional(),
      completedAt: z.string().optional(),
    }),
  }),
])

export type FulfillmentCrudInput = z.infer<typeof FulfillmentCrudSchema>
export type status = z.infer<typeof statusSchema>