/**
 * OrderItem CRUD Edge Function
 *
 * Auto-generated by HEADLESS API Generator
 * - VibeCoding標準パターン (createAkatsukiHandler)
 * - Zod Validation
 * - Repository DI
 * - RLS対応
 *
 * Supported Actions:
 * - list
 * - get
 * - create
 */

import { createAkatsukiHandler } from '../_shared/handler.ts'
import { OrderItemRepository } from '../_shared/repositories/OrderItemRepository.ts'
import { OrderItemCrudSchema, type OrderItemCrudInput } from './schema.ts'

Deno.serve(async (req) => {
  return createAkatsukiHandler<OrderItemCrudInput, any>(req, {
    inputSchema: OrderItemCrudSchema,
    logic: async ({ input, userClient, adminClient, repos }) => {
      // Create Repository with userClient (RLS enabled)
      const order_itemRepo = new OrderItemRepository(userClient)

      switch (input.action) {
        case 'list': {
          // Get order_items with filters
          return order_itemRepo.findAll({
            orderId: input.filters?.orderId,
            limit: input.limit || 20,
          })
        }
        case 'get': {
          // Get order_item by ID
          const order_item = await order_itemRepo.findById(input.id)
          if (!order_item) {
            throw Object.assign(new Error('OrderItem not found'), {
              status: 404,
              code: 'ORDER_ITEM_NOT_FOUND',
            })
          }
          return order_item
        }
        case 'create': {
          // Create new order_item
          const user = await order_itemRepo.getCurrentUser()
          return order_itemRepo.create({
            user_id: user.id,
            order_id: input.data.orderId,
            product_id: input.data.productId || null,
            variant_id: input.data.variantId || null,
            product_name: input.data.productName,
            variant_name: input.data.variantName || null,
            quantity: input.data.quantity,
            unit_price: input.data.unitPrice,
            subtotal: input.data.subtotal,
            product_type: input.data.productType,
            product_metadata: input.data.productMetadata || null,
          })
        }

        default:
          throw Object.assign(new Error('Invalid action'), {
            status: 400,
            code: 'INVALID_ACTION',
          })
      }
    },
  })
})

/* To invoke locally:

  1. Run `supabase start`
  2. Make an HTTP request:
  # List order_items
  curl -i --location --request POST 'http://127.0.0.1:54321/functions/v1/order_items-crud' \
    --header 'Authorization: Bearer YOUR_JWT_TOKEN' \
    --header 'Content-Type: application/json' \
    --data '{"action":"list","limit":10}'

  # Create order_item
  curl -i --location --request POST 'http://127.0.0.1:54321/functions/v1/order_items-crud' \
    --header 'Authorization: Bearer YOUR_JWT_TOKEN' \
    --header 'Content-Type: application/json' \
    --data '{"action":"create","data":{"title":"Example","content":"Content here"}}'

*/