import { z } from 'https://deno.land/x/zod@v3.23.8/mod.ts'

/**
 * OrderItem Schema for CRUD operations
 * Auto-generated by HEADLESS API Generator
 */

// Enum schemas
// OrderItem object schema
export const OrderItemSchema = z.object({
  id: z.string().uuid(),
  orderId: z.string().uuid(),
  createdAt: z.string(),
  productId: z.string().uuid(),
  variantId: z.string().uuid(),
  productName: z.string(),
  variantName: z.string(),
  quantity: z.number(),
  unitPrice: z.number(),
  subtotal: z.number(),
  productType: z.string(),
  productMetadata: z.record(z.any()),
})

// Input schemas for each CRUD operation
export const OrderItemCrudSchema = z.discriminatedUnion('action', [
  // List order_items
  z.object({
    action: z.literal('list'),
    filters: z.object({
      orderId: z.string().uuid().optional(),
    }).optional(),
    limit: z.number().int().positive().max(100).optional(),
  }),
  // Get order_item by ID
  z.object({
    action: z.literal('get'),
    id: z.string().uuid(),
  }),
  // Create order_item
  z.object({
    action: z.literal('create'),
    data: z.object({
      orderId: z.string().uuid(),
      productId: z.string().uuid().optional(),
      variantId: z.string().uuid().optional(),
      productName: z.string(),
      variantName: z.string().optional(),
      quantity: z.number(),
      unitPrice: z.number(),
      subtotal: z.number(),
      productType: z.string(),
      productMetadata: z.record(z.any()).optional(),
    }),
  }),
])

export type OrderItemCrudInput = z.infer<typeof OrderItemCrudSchema>