/**
 * OrderItems Demo Card
 * Auto-generated by HEADLESS API Generator
 *
 * Usage in ExamplesPage.tsx:
 *   import { OrderItemsDemo } from '../components/features/order_items/OrderItemsDemo'
 *   <OrderItemsDemo />
 */

import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../ui/card'
import { Button } from '../../ui/button'
import { Input } from '../../ui/input'
import { Textarea } from '../../ui/textarea'
import { Badge } from '../../ui/badge'
import { useOrderItems } from '../../../hooks/useOrderItems'
import type { OrderItem } from '../../../models/OrderItem'

export function OrderItemsDemo() {
  const [orderId, setOrderId] = useState<string>(null)
  const [productId, setProductId] = useState<string>(null)
  const [variantId, setVariantId] = useState<string>(null)
  const [productName, setProductName] = useState<string>('')
  const [variantName, setVariantName] = useState<string>(null)
  const [quantity, setQuantity] = useState<number>(0)
  const [unitPrice, setUnitPrice] = useState<number>(0)
  const [subtotal, setSubtotal] = useState<number>(0)
  const [productType, setProductType] = useState<string>('')
  const [productMetadata, setProductMetadata] = useState<Record<string, any>>(null)
  const [editingId, setEditingId] = useState<string | null>(null)

  const {
    orderitems,
    isLoading,
    createOrderItem,
    isCreating,
    updateOrderItem,
    isUpdating,
    deleteOrderItem,
    isDeleting,
  } = useOrderItems({ mine: true })

  const resetForm = () => {
    setOrderId(null)
    setProductId(null)
    setVariantId(null)
    setProductName('')
    setVariantName(null)
    setQuantity(0)
    setUnitPrice(0)
    setSubtotal(0)
    setProductType('')
    setProductMetadata(null)
    setEditingId(null)
  }

  const handleCreate = () => {
    createOrderItem({
      orderId,
      productId,
      variantId,
      productName,
      variantName,
      quantity,
      unitPrice,
      subtotal,
      productType,
      productMetadata,
    })
    resetForm()
  }

  const handleEdit = (item: OrderItem) => {
    setEditingId(item.id)
    setOrderId(item.orderId)
    setProductId(item.productId ?? null)
    setVariantId(item.variantId ?? null)
    setProductName(item.productName)
    setVariantName(item.variantName ?? null)
    setQuantity(item.quantity)
    setUnitPrice(item.unitPrice)
    setSubtotal(item.subtotal)
    setProductType(item.productType)
    setProductMetadata(item.productMetadata ?? null)
  }

  const handleUpdate = () => {
    if (!editingId) return
    updateOrderItem(editingId, {
      orderId,
      productId,
      variantId,
      productName,
      variantName,
      quantity,
      unitPrice,
      subtotal,
      productType,
      productMetadata,
    })
    resetForm()
  }

  const itemCount = orderitems?.length ?? 0

  return (
    <Card className="border-green-200 bg-gradient-to-br from-green-50 to-emerald-50">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <span className="text-2xl">📝</span>
          OrderItems CRUD (HEADLESS API)
        </CardTitle>
        <CardDescription>
          Edge Function + React Query - Full CRUD with RLS
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Code Example */}
        <pre className="bg-gray-50 p-3 rounded-lg text-xs font-mono overflow-x-auto">
          <code>{`// Frontend: React Query Hook
const { orderitems, createOrderItem, updateOrderItem } = useOrderItems()
createOrderItem({ orderId: '...', productId: '...', variantId: '...', productName: '...', variantName: '...', quantity: '...', unitPrice: '...', subtotal: '...', productType: '...', productMetadata: '...' })`}</code>
        </pre>

        {/* Create/Edit Form */}
        <div className="bg-white p-4 rounded-lg space-y-3">
          <h3 className="font-semibold text-gray-700">
            {editingId ? '✏️ Edit OrderItem' : '➕ Create OrderItem'}
          </h3>

          <Input
            placeholder="ProductName"
            value={ productName ?? ''}
            onChange={(e) => setProductName(e.target.value)}
          />

          <Input
            placeholder="VariantName"
            value={ variantName ?? ''}
            onChange={(e) => setVariantName(e.target.value)}
          />

          <Input
            placeholder="ProductType"
            value={ productType ?? ''}
            onChange={(e) => setProductType(e.target.value)}
          />

          <div className="flex gap-2">
            {editingId ? (
              <>
                <Button onClick={handleUpdate} disabled={isUpdating}>
                  {isUpdating ? 'Updating...' : 'Update'}
                </Button>
                <Button variant="outline" onClick={resetForm}>
                  Cancel
                </Button>
              </>
            ) : (
              <Button onClick={handleCreate} disabled={isCreating}>
                {isCreating ? 'Creating...' : 'Create OrderItem'}
              </Button>
            )}
          </div>
        </div>

        {/* List */}
        <div className="bg-white p-4 rounded-lg space-y-3">
          <h3 className="font-semibold text-gray-700">📚 Your OrderItems ({itemCount})</h3>

          {isLoading && (
            <p className="text-sm text-gray-500">Loading orderitems...</p>
          )}

          {!isLoading && itemCount === 0 && (
            <p className="text-sm text-gray-500">No orderitems yet. Create your first one!</p>
          )}

          <div className="space-y-2">
            { orderitems?.map((item) => (
              <div
                key={item.id}
                className="border rounded-lg p-3 space-y-2 hover:bg-gray-50 transition-colors"
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="flex-1 min-w-0">
                    <h4 className="font-medium text-gray-900 truncate">
                      {item.orderId}
                    </h4>
                  </div>
                </div>

                <div className="flex gap-2 flex-wrap">
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => handleEdit(item)}
                  >
                    Edit
                  </Button>

                  <Button
                    size="sm"
                    variant="destructive"
                    onClick={() => {
                      if (confirm('Delete this orderitem?')) {
                        deleteOrderItem(item.id!)
                      }
                    }}
                    disabled={isDeleting}
                  >
                    Delete
                  </Button>
                </div>

                {item.createdAt && (
                  <p className="text-xs text-gray-400">
                    Created: {new Date(item.createdAt).toLocaleDateString()}
                  </p>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Info */}
        <div className="bg-blue-50 p-3 rounded-lg text-sm text-gray-700">
          <p className="font-semibold mb-2">🎯 Features:</p>
          <ul className="list-disc list-inside space-y-1 text-xs">
            <li>✅ Full CRUD operations (Create, Read, Update, Delete)</li>
            <li>✅ RLS Security (Row Level Security)</li>
            <li>✅ Edge Function (createAkatsukiHandler)</li>
            <li>✅ React Query (Automatic cache & invalidation)</li>
            <li>✅ Type-safe (TypeScript + Zod)</li>
          </ul>
        </div>
      </CardContent>
    </Card>
  )
}