/**
 * Orders Demo Card
 * Auto-generated by HEADLESS API Generator
 *
 * Usage in ExamplesPage.tsx:
 *   import { OrdersDemo } from '../components/features/orders/OrdersDemo'
 *   <OrdersDemo />
 */

import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../ui/card'
import { Button } from '../../ui/button'
import { Input } from '../../ui/input'
import { Textarea } from '../../ui/textarea'
import { Badge } from '../../ui/badge'
import { useOrders } from '../../../hooks/useOrders'
import type { Order } from '../../../models/Order'

export function OrdersDemo() {
  const [stripeCheckoutSessionId, setStripeCheckoutSessionId] = useState<string>(null)
  const [stripePaymentIntentId, setStripePaymentIntentId] = useState<string>(null)
  const [status, setStatus] = useState<'pending' | 'paid' | 'fulfilled' | 'cancelled' | 'refunded'>('pending')
  const [totalAmount, setTotalAmount] = useState<number>(0)
  const [currency, setCurrency] = useState<string>('')
  const [metadata, setMetadata] = useState<Record<string, any>>(null)
  const [fulfilledAt, setFulfilledAt] = useState<string>(null)
  const [editingId, setEditingId] = useState<string | null>(null)

  const {
    orders,
    isLoading,
    createOrder,
    isCreating,
    updateOrder,
    isUpdating,
    deleteOrder,
    isDeleting,
    setStatusPaid,
    setStatusPending,
  } = useOrders({ mine: true })

  const resetForm = () => {
    setStripeCheckoutSessionId(null)
    setStripePaymentIntentId(null)
    setStatus('pending')
    setTotalAmount(0)
    setCurrency('')
    setMetadata(null)
    setFulfilledAt(null)
    setEditingId(null)
  }

  const handleCreate = () => {
    createOrder({
      stripeCheckoutSessionId,
      stripePaymentIntentId,
      status,
      totalAmount,
      currency,
      metadata,
      fulfilledAt,
    })
    resetForm()
  }

  const handleEdit = (item: Order) => {
    setEditingId(item.id)
    setStripeCheckoutSessionId(item.stripeCheckoutSessionId ?? null)
    setStripePaymentIntentId(item.stripePaymentIntentId ?? null)
    setStatus(item.status)
    setTotalAmount(item.totalAmount)
    setCurrency(item.currency)
    setMetadata(item.metadata ?? null)
    setFulfilledAt(item.fulfilledAt ?? null)
  }

  const handleUpdate = () => {
    if (!editingId) return
    updateOrder(editingId, {
      stripeCheckoutSessionId,
      stripePaymentIntentId,
      status,
      totalAmount,
      currency,
      metadata,
      fulfilledAt,
    })
    resetForm()
  }

  const itemCount = orders?.length ?? 0

  return (
    <Card className="border-green-200 bg-gradient-to-br from-green-50 to-emerald-50">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <span className="text-2xl">📝</span>
          Orders CRUD (HEADLESS API)
        </CardTitle>
        <CardDescription>
          Edge Function + React Query - Full CRUD with RLS
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Code Example */}
        <pre className="bg-gray-50 p-3 rounded-lg text-xs font-mono overflow-x-auto">
          <code>{`// Frontend: React Query Hook
const { orders, createOrder, updateOrder } = useOrders()
createOrder({ stripeCheckoutSessionId: '...', stripePaymentIntentId: '...', status: '...', totalAmount: '...', currency: '...', metadata: '...', fulfilledAt: '...' })`}</code>
        </pre>

        {/* Create/Edit Form */}
        <div className="bg-white p-4 rounded-lg space-y-3">
          <h3 className="font-semibold text-gray-700">
            {editingId ? '✏️ Edit Order' : '➕ Create Order'}
          </h3>

          <Input
            placeholder="StripeCheckoutSessionId"
            value={ stripeCheckoutSessionId ?? ''}
            onChange={(e) => setStripeCheckoutSessionId(e.target.value)}
          />

          <Input
            placeholder="StripePaymentIntentId"
            value={ stripePaymentIntentId ?? ''}
            onChange={(e) => setStripePaymentIntentId(e.target.value)}
          />

          <select
            className="w-full border rounded-md p-2"
            value={ status ?? ''}
            onChange={(e) => setStatus(e.target.value as any)}
          >
            <option value="pending">pending</option>
            <option value="paid">paid</option>
            <option value="fulfilled">fulfilled</option>
            <option value="cancelled">cancelled</option>
            <option value="refunded">refunded</option>
          </select>

          <Input
            placeholder="Currency"
            value={ currency ?? ''}
            onChange={(e) => setCurrency(e.target.value)}
          />

          <div className="flex gap-2">
            {editingId ? (
              <>
                <Button onClick={handleUpdate} disabled={isUpdating}>
                  {isUpdating ? 'Updating...' : 'Update'}
                </Button>
                <Button variant="outline" onClick={resetForm}>
                  Cancel
                </Button>
              </>
            ) : (
              <Button onClick={handleCreate} disabled={isCreating}>
                {isCreating ? 'Creating...' : 'Create Order'}
              </Button>
            )}
          </div>
        </div>

        {/* List */}
        <div className="bg-white p-4 rounded-lg space-y-3">
          <h3 className="font-semibold text-gray-700">📚 Your Orders ({itemCount})</h3>

          {isLoading && (
            <p className="text-sm text-gray-500">Loading orders...</p>
          )}

          {!isLoading && itemCount === 0 && (
            <p className="text-sm text-gray-500">No orders yet. Create your first one!</p>
          )}

          <div className="space-y-2">
            { orders?.map((item) => (
              <div
                key={item.id}
                className="border rounded-lg p-3 space-y-2 hover:bg-gray-50 transition-colors"
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="flex-1 min-w-0">
                    <h4 className="font-medium text-gray-900 truncate">
                      {item.stripeCheckoutSessionId}
                    </h4>
                    <p className="text-sm text-gray-600 line-clamp-2 mt-1">
                      {item.stripePaymentIntentId}
                    </p>
                  </div>
                  <Badge variant={item.status === 'pending' ? 'secondary' : 'default'}>
                    {item.status}
                  </Badge>
                </div>

                <div className="flex gap-2 flex-wrap">
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => handleEdit(item)}
                  >
                    Edit
                  </Button>

                  <Button
                    size="sm"
                    variant="secondary"
                    onClick={() => {
                      if (item.status === 'pending') {
                        setStatusPaid(item.id!)
                      } else {
                        setStatusPending(item.id!)
                      }
                    }}
                  >
                    Toggle Status
                  </Button>

                  <Button
                    size="sm"
                    variant="destructive"
                    onClick={() => {
                      if (confirm('Delete this order?')) {
                        deleteOrder(item.id!)
                      }
                    }}
                    disabled={isDeleting}
                  >
                    Delete
                  </Button>
                </div>

                {item.createdAt && (
                  <p className="text-xs text-gray-400">
                    Created: {new Date(item.createdAt).toLocaleDateString()}
                  </p>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Info */}
        <div className="bg-blue-50 p-3 rounded-lg text-sm text-gray-700">
          <p className="font-semibold mb-2">🎯 Features:</p>
          <ul className="list-disc list-inside space-y-1 text-xs">
            <li>✅ Full CRUD operations (Create, Read, Update, Delete)</li>
            <li>✅ RLS Security (Row Level Security)</li>
            <li>✅ Edge Function (createAkatsukiHandler)</li>
            <li>✅ React Query (Automatic cache & invalidation)</li>
            <li>✅ Type-safe (TypeScript + Zod)</li>
          </ul>
        </div>
      </CardContent>
    </Card>
  )
}