/**
 * Product CRUD Edge Function
 *
 * Auto-generated by HEADLESS API Generator
 * - VibeCoding標準パターン (createAkatsukiHandler)
 * - Zod Validation
 * - Repository DI
 * - RLS対応
 *
 * Supported Actions:
 * - list
 * - get
 * - create
 * - update
 * - delete
 * - custom (active): Get all active products
 */

import { createAkatsukiHandler } from '../_shared/handler.ts'
import { ProductRepository } from '../_shared/repositories/ProductRepository.ts'
import { ProductCrudSchema, type ProductCrudInput } from './schema.ts'

Deno.serve(async (req) => {
  return createAkatsukiHandler<ProductCrudInput, any>(req, {
    inputSchema: ProductCrudSchema,
    logic: async ({ input, userClient, adminClient, repos }) => {
      // Create Repository with userClient (RLS enabled)
      const productRepo = new ProductRepository(userClient)

      switch (input.action) {
        case 'list': {
          // Get products with filters
          return productRepo.findAll({
            productType: input.filters?.productType,
            isActive: input.filters?.isActive,
            limit: input.limit || 20,
          })
        }
        case 'get': {
          // Get product by ID
          const product = await productRepo.findById(input.id)
          if (!product) {
            throw Object.assign(new Error('Product not found'), {
              status: 404,
              code: 'PRODUCT_NOT_FOUND',
            })
          }
          return product
        }
        case 'create': {
          // Create new product
          const user = await productRepo.getCurrentUser()
          return productRepo.create({
            user_id: user.id,
            name: input.data.name,
            description: input.data.description || null,
            product_type: input.data.productType,
            stripe_product_id: input.data.stripeProductId || null,
            metadata: input.data.metadata || null,
            image_url: input.data.imageUrl || null,
            display_order: input.data.displayOrder || null,
            is_active: input.data.isActive,
          })
        }
        case 'update': {
          // Update product
          const product = await productRepo.findById(input.id)
          if (!product) {
            throw Object.assign(new Error('Product not found'), {
              status: 404,
              code: 'PRODUCT_NOT_FOUND',
            })
          }

          return productRepo.update(input.id, input.data)
        }
        case 'delete': {
          // Delete product
          const product = await productRepo.findById(input.id)
          if (!product) {
            throw Object.assign(new Error('Product not found'), {
              status: 404,
              code: 'PRODUCT_NOT_FOUND',
            })
          }

          await productRepo.delete(input.id)
          return { success: true, message: 'Product deleted' }
        }
        case 'active': {
          // Get all active products
          return productRepo.active({
              productType: input.filters?.productType,
            }
          )
        }

        default:
          throw Object.assign(new Error('Invalid action'), {
            status: 400,
            code: 'INVALID_ACTION',
          })
      }
    },
  })
})

/* To invoke locally:

  1. Run `supabase start`
  2. Make an HTTP request:
  # List products
  curl -i --location --request POST 'http://127.0.0.1:54321/functions/v1/products-crud' \
    --header 'Authorization: Bearer YOUR_JWT_TOKEN' \
    --header 'Content-Type: application/json' \
    --data '{"action":"list","limit":10}'

  # Create product
  curl -i --location --request POST 'http://127.0.0.1:54321/functions/v1/products-crud' \
    --header 'Authorization: Bearer YOUR_JWT_TOKEN' \
    --header 'Content-Type: application/json' \
    --data '{"action":"create","data":{"title":"Example","content":"Content here"}}'

*/