import { z } from 'https://deno.land/x/zod@v3.23.8/mod.ts'

/**
 * Product Schema for CRUD operations
 * Auto-generated by HEADLESS API Generator
 */

// Enum schemas
export const productTypeSchema = z.enum(['token_pack', 'digital', 'feature', 'physical'])

// Product object schema
export const ProductSchema = z.object({
  id: z.string().uuid(),
  createdAt: z.string(),
  updatedAt: z.string(),
  name: z.string().min(1).max(200),
  description: z.string(),
  productType: z.enum(['token_pack', 'digital', 'feature', 'physical']),
  stripeProductId: z.string(),
  metadata: z.record(z.any()),
  imageUrl: z.string(),
  displayOrder: z.number(),
  isActive: z.boolean(),
})

// Input schemas for each CRUD operation
export const ProductCrudSchema = z.discriminatedUnion('action', [
  // List products
  z.object({
    action: z.literal('list'),
    filters: z.object({
      isActive: z.boolean().optional(),
    }).optional(),
    limit: z.number().int().positive().max(100).optional(),
  }),
  // Get product by ID
  z.object({
    action: z.literal('get'),
    id: z.string().uuid(),
  }),
  // Create product
  z.object({
    action: z.literal('create'),
    data: z.object({
      name: z.string().min(1).max(200),
      description: z.string().optional(),
      productType: z.enum(['token_pack', 'digital', 'feature', 'physical']),
      stripeProductId: z.string().optional(),
      metadata: z.record(z.any()).optional(),
      imageUrl: z.string().optional(),
      displayOrder: z.number().optional(),
      isActive: z.boolean(),
    }),
  }),
  // Update product
  z.object({
    action: z.literal('update'),
    id: z.string().uuid(),
    data: z.object({
      name: z.string().min(1).max(200).optional(),
      description: z.string().optional(),
      productType: z.enum(['token_pack', 'digital', 'feature', 'physical']).optional(),
      stripeProductId: z.string().optional(),
      metadata: z.record(z.any()).optional(),
      imageUrl: z.string().optional(),
      displayOrder: z.number().optional(),
      isActive: z.boolean().optional(),
    }),
  }),
  // Delete product
  z.object({
    action: z.literal('delete'),
    id: z.string().uuid(),
  }),
  // Get all active products
  z.object({
    action: z.literal('active'),
  }),
])

export type ProductCrudInput = z.infer<typeof ProductCrudSchema>
export type productType = z.infer<typeof productTypeSchema>