/**
 * Articles API Client (app-cli)
 * Auto-generated by HEADLESS API Generator
 *
 * Usage:
 * ```typescript
 * import { AkatsukiClient } from '../client.js'
 * import { ArticlesClient } from './ArticlesClient.js'
 *
 * const client = new AkatsukiClient()
 * await client.login(email, password)
 *
 * const articlesClient = new ArticlesClient(client)
 * const articles = await articlesClient.list()
 * ```
 */

import { AkatsukiClient } from '../client.js'

/**
 * Article type
 */
export interface Article {
  id: string
  user_id: string
  title: string
  content: string
  status: 'draft' | 'published'
  tags: string[]
  created_at: string
  updated_at: string
}

/**
 * Article create input
 */
export interface ArticleCreateInput {
  title: string
  content: string
  status?: 'draft' | 'published'
  tags?: string[]
}

/**
 * Article update input
 */
export interface ArticleUpdateInput {
  title?: string
  content?: string
  status?: 'draft' | 'published'
  tags?: string[]
}

/**
 * Articles API Client
 */
export class ArticlesClient {
  constructor(private client: AkatsukiClient) {}

  /**
   * Get my articles with filters
   */
  async getMyArticles(filters: { status?: 'draft' | 'published' } = {}): Promise<Article[]> {
    return this.client.invoke<Article[]>('articles-crud', {
      action: 'my',
      filters,
    })
  }

  /**
   * Get published articles
   */
  async getPublished(limit: number = 20): Promise<Article[]> {
    return this.client.invoke<Article[]>('articles-crud', {
      action: 'published',
      limit,
    })
  }

  /**
   * Get article by ID
   */
  async getById(id: string): Promise<Article> {
    return this.client.invoke<Article>('articles-crud', {
      action: 'get',
      id,
    })
  }

  /**
   * Create article
   */
  async create(data: ArticleCreateInput): Promise<Article> {
    return this.client.invoke<Article>('articles-crud', {
      action: 'create',
      data,
    })
  }

  /**
   * Update article
   */
  async update(id: string, data: ArticleUpdateInput): Promise<Article> {
    return this.client.invoke<Article>('articles-crud', {
      action: 'update',
      id,
      data,
    })
  }

  /**
   * Delete article
   */
  async delete(id: string): Promise<{ deleted: boolean }> {
    return this.client.invoke<{ deleted: boolean }>('articles-crud', {
      action: 'delete',
      id,
    })
  }

  /**
   * Publish article
   */
  async publish(id: string): Promise<Article> {
    return this.update(id, { status: 'published' })
  }

  /**
   * Unpublish article (set to draft)
   */
  async unpublish(id: string): Promise<Article> {
    return this.update(id, { status: 'draft' })
  }
}
