/**
 * Fulfillments API Client (app-cli)
 * Auto-generated by HEADLESS API Generator
 *
 * Convenience wrapper for fulfillments-crud Edge Function
 * - Supabase Auth integrated
 * - AkatsukiResponse parsing
 * - Full TypeScript support
 *
 * Usage:
 * ```typescript
 * import { AkatsukiClient } from '../client.js'
 * import { FulfillmentsClient } from './FulfillmentsClient.js'
 *
 * const client = new AkatsukiClient()
 * await client.login(email, password)
 *
 * const fulfillmentsClient = new FulfillmentsClient(client)
 * const fulfillments = await fulfillmentsClient.list()
 * ```
 */

import { AkatsukiClient } from '../client.js'

/**
 * Fulfillment type
 */
export interface Fulfillment {
  id: string
  user_id: string
  order_item_id: string
  fulfillment_type: string
  status: 'pending' | 'completed' | 'failed'
  result: Record<string, any> | null
  error_message: string | null
  completed_at: string | null
  created_at: string
  updated_at: string
}

/**
 * Fulfillment create input
 */
export interface FulfillmentCreateInput {
  orderItemId: string
  fulfillmentType: string
  status: 'pending' | 'completed' | 'failed'
  result?: Record<string, any>
  errorMessage?: string
  completedAt?: string
}

/**
 * Fulfillment update input
 */
export interface FulfillmentUpdateInput {
  orderItemId?: string
  fulfillmentType?: string
  status?: 'pending' | 'completed' | 'failed'
  result?: Record<string, any>
  errorMessage?: string
  completedAt?: string
}

/**
 * Fulfillments API Client
 */
export class FulfillmentsClient {
  constructor(private client: AkatsukiClient) {}

  /**
   * Get fulfillments with filters
   */
  async list(
    filters: { status?: string, fulfillmentType?: string } = {},
    limit: number = 20
  ): Promise<Fulfillment[]> {
    return this.client.invoke<Fulfillment[]>('fulfillments-crud', {
      action: 'list',
      filters,
      limit,
    })
  }

  /**
   * Get fulfillment by ID
   */
  async getById(id: string): Promise<Fulfillment> {
    return this.client.invoke<Fulfillment>('fulfillments-crud', {
      action: 'get',
      id,
    })
  }

  /**
   * Create fulfillment
   */
  async create(data: FulfillmentCreateInput): Promise<Fulfillment> {
    return this.client.invoke<Fulfillment>('fulfillments-crud', {
      action: 'create',
      data,
    })
  }

  /**
   * Update fulfillment
   */
  async update(id: string, data: FulfillmentUpdateInput): Promise<Fulfillment> {
    return this.client.invoke<Fulfillment>('fulfillments-crud', {
      action: 'update',
      id,
      data,
    })
  }

  /**
   * Set fulfillment status to 'completed'
   */
  async completed(id: string): Promise<Fulfillment> {
    return this.update(id, { status: 'completed' })
  }

  /**
   * Set fulfillment status to 'pending'
   */
  async uncompleted(id: string): Promise<Fulfillment> {
    return this.update(id, { status: 'pending' })
  }
}