/**
 * OrderItems API Client (app-cli)
 * Auto-generated by HEADLESS API Generator
 *
 * Convenience wrapper for order_items-crud Edge Function
 * - Supabase Auth integrated
 * - AkatsukiResponse parsing
 * - Full TypeScript support
 *
 * Usage:
 * ```typescript
 * import { AkatsukiClient } from '../client.js'
 * import { OrderItemsClient } from './OrderItemsClient.js'
 *
 * const client = new AkatsukiClient()
 * await client.login(email, password)
 *
 * const orderitemsClient = new OrderItemsClient(client)
 * const orderitems = await orderitemsClient.list()
 * ```
 */

import { AkatsukiClient } from '../client.js'

/**
 * OrderItem type
 */
export interface OrderItem {
  id: string
  user_id: string
  order_id: string
  product_id: string | null
  variant_id: string | null
  product_name: string
  variant_name: string | null
  quantity: number
  unit_price: number
  subtotal: number
  product_type: string
  product_metadata: Record<string, any> | null
  created_at: string
  updated_at: string
}

/**
 * OrderItem create input
 */
export interface OrderItemCreateInput {
  orderId: string
  productId?: string
  variantId?: string
  productName: string
  variantName?: string
  quantity: number
  unitPrice: number
  subtotal: number
  productType: string
  productMetadata?: Record<string, any>
}

/**
 * OrderItem update input
 */
export interface OrderItemUpdateInput {
  orderId?: string
  productId?: string
  variantId?: string
  productName?: string
  variantName?: string
  quantity?: number
  unitPrice?: number
  subtotal?: number
  productType?: string
  productMetadata?: Record<string, any>
}

/**
 * OrderItems API Client
 */
export class OrderItemsClient {
  constructor(private client: AkatsukiClient) {}

  /**
   * Get orderitems with filters
   */
  async list(
    filters: { orderId?: string } = {},
    limit: number = 20
  ): Promise<OrderItem[]> {
    return this.client.invoke<OrderItem[]>('order_items-crud', {
      action: 'list',
      filters,
      limit,
    })
  }

  /**
   * Get orderitem by ID
   */
  async getById(id: string): Promise<OrderItem> {
    return this.client.invoke<OrderItem>('order_items-crud', {
      action: 'get',
      id,
    })
  }

  /**
   * Create orderitem
   */
  async create(data: OrderItemCreateInput): Promise<OrderItem> {
    return this.client.invoke<OrderItem>('order_items-crud', {
      action: 'create',
      data,
    })
  }
}