/**
 * Orders API Client (app-cli)
 * Auto-generated by HEADLESS API Generator
 *
 * Convenience wrapper for orders-crud Edge Function
 * - Supabase Auth integrated
 * - AkatsukiResponse parsing
 * - Full TypeScript support
 *
 * Usage:
 * ```typescript
 * import { AkatsukiClient } from '../client.js'
 * import { OrdersClient } from './OrdersClient.js'
 *
 * const client = new AkatsukiClient()
 * await client.login(email, password)
 *
 * const ordersClient = new OrdersClient(client)
 * const orders = await ordersClient.list()
 * ```
 */

import { AkatsukiClient } from '../client.js'

/**
 * Order type
 */
export interface Order {
  id: string
  user_id: string
  stripe_checkout_session_id: string | null
  stripe_payment_intent_id: string | null
  status: 'pending' | 'paid' | 'fulfilled' | 'cancelled' | 'refunded'
  total_amount: number
  currency: string
  metadata: Record<string, any> | null
  fulfilled_at: string | null
  created_at: string
  updated_at: string
}

/**
 * Order create input
 */
export interface OrderCreateInput {
  stripeCheckoutSessionId?: string
  stripePaymentIntentId?: string
  status: 'pending' | 'paid' | 'fulfilled' | 'cancelled' | 'refunded'
  totalAmount: number
  currency: string
  metadata?: Record<string, any>
  fulfilledAt?: string
}

/**
 * Order update input
 */
export interface OrderUpdateInput {
  stripeCheckoutSessionId?: string
  stripePaymentIntentId?: string
  status?: 'pending' | 'paid' | 'fulfilled' | 'cancelled' | 'refunded'
  totalAmount?: number
  currency?: string
  metadata?: Record<string, any>
  fulfilledAt?: string
}

/**
 * Orders API Client
 */
export class OrdersClient {
  constructor(private client: AkatsukiClient) {}

  /**
   * Get orders with filters
   */
  async list(
    filters: { status?: string, userId?: string } = {},
    limit: number = 20
  ): Promise<Order[]> {
    return this.client.invoke<Order[]>('orders-crud', {
      action: 'list',
      filters,
      limit,
    })
  }

  /**
   * Get order by ID
   */
  async getById(id: string): Promise<Order> {
    return this.client.invoke<Order>('orders-crud', {
      action: 'get',
      id,
    })
  }

  /**
   * Create order
   */
  async create(data: OrderCreateInput): Promise<Order> {
    return this.client.invoke<Order>('orders-crud', {
      action: 'create',
      data,
    })
  }

  /**
   * Update order
   */
  async update(id: string, data: OrderUpdateInput): Promise<Order> {
    return this.client.invoke<Order>('orders-crud', {
      action: 'update',
      id,
      data,
    })
  }

  /**
   * Get current user's orders
   */
  async my(filters: { status?: string } = {}): Promise<Order[]> {
    return this.client.invoke<Order[]>('orders-crud', {
      action: 'my',
      filters,
    })
  }

  /**
   * Set order status to 'paid'
   */
  async paid(id: string): Promise<Order> {
    return this.update(id, { status: 'paid' })
  }

  /**
   * Set order status to 'pending'
   */
  async unpaid(id: string): Promise<Order> {
    return this.update(id, { status: 'pending' })
  }
}