/**
 * Products API Client (app-cli)
 * Auto-generated by HEADLESS API Generator
 *
 * Convenience wrapper for products-crud Edge Function
 * - Supabase Auth integrated
 * - AkatsukiResponse parsing
 * - Full TypeScript support
 *
 * Usage:
 * ```typescript
 * import { AkatsukiClient } from '../client.js'
 * import { ProductsClient } from './ProductsClient.js'
 *
 * const client = new AkatsukiClient()
 * await client.login(email, password)
 *
 * const productsClient = new ProductsClient(client)
 * const products = await productsClient.list()
 * ```
 */

import { AkatsukiClient } from '../client.js'

/**
 * Product type
 */
export interface Product {
  id: string
  user_id: string
  name: string
  description: string | null
  product_type: 'token_pack' | 'digital' | 'feature' | 'physical'
  stripe_product_id: string | null
  metadata: Record<string, any> | null
  image_url: string | null
  display_order: number | null
  is_active: boolean
  created_at: string
  updated_at: string
}

/**
 * Product create input
 */
export interface ProductCreateInput {
  name: string
  description?: string
  productType: 'token_pack' | 'digital' | 'feature' | 'physical'
  stripeProductId?: string
  metadata?: Record<string, any>
  imageUrl?: string
  displayOrder?: number
  isActive: boolean
}

/**
 * Product update input
 */
export interface ProductUpdateInput {
  name?: string
  description?: string
  productType?: 'token_pack' | 'digital' | 'feature' | 'physical'
  stripeProductId?: string
  metadata?: Record<string, any>
  imageUrl?: string
  displayOrder?: number
  isActive?: boolean
}

/**
 * Products API Client
 */
export class ProductsClient {
  constructor(private client: AkatsukiClient) {}

  /**
   * Get products with filters
   */
  async list(
    filters: { productType?: string, isActive?: string } = {},
    limit: number = 20
  ): Promise<Product[]> {
    return this.client.invoke<Product[]>('products-crud', {
      action: 'list',
      filters,
      limit,
    })
  }

  /**
   * Get product by ID
   */
  async getById(id: string): Promise<Product> {
    return this.client.invoke<Product>('products-crud', {
      action: 'get',
      id,
    })
  }

  /**
   * Create product
   */
  async create(data: ProductCreateInput): Promise<Product> {
    return this.client.invoke<Product>('products-crud', {
      action: 'create',
      data,
    })
  }

  /**
   * Update product
   */
  async update(id: string, data: ProductUpdateInput): Promise<Product> {
    return this.client.invoke<Product>('products-crud', {
      action: 'update',
      id,
      data,
    })
  }

  /**
   * Delete product
   */
  async delete(id: string): Promise<{ deleted: boolean }> {
    return this.client.invoke<{ deleted: boolean }>('products-crud', {
      action: 'delete',
      id,
    })
  }

  /**
   * Get all active products
   */
  async active(filters: { productType?: string } = {}): Promise<Product[]> {
    return this.client.invoke<Product[]>('products-crud', {
      action: 'active',
      filters,
    })
  }

  /**
   * Set product productType to 'digital'
   */
  async digital(id: string): Promise<Product> {
    return this.update(id, { productType: 'digital' })
  }

  /**
   * Set product productType to 'token_pack'
   */
  async undigital(id: string): Promise<Product> {
    return this.update(id, { productType: 'token_pack' })
  }
}