/**
 * ProductVariants API Client (app-cli)
 * Auto-generated by HEADLESS API Generator
 *
 * Convenience wrapper for product_variants-crud Edge Function
 * - Supabase Auth integrated
 * - AkatsukiResponse parsing
 * - Full TypeScript support
 *
 * Usage:
 * ```typescript
 * import { AkatsukiClient } from '../client.js'
 * import { ProductVariantsClient } from './ProductVariantsClient.js'
 *
 * const client = new AkatsukiClient()
 * await client.login(email, password)
 *
 * const productvariantsClient = new ProductVariantsClient(client)
 * const productvariants = await productvariantsClient.list()
 * ```
 */

import { AkatsukiClient } from '../client.js'

/**
 * ProductVariant type
 */
export interface ProductVariant {
  id: string
  user_id: string
  product_id: string
  name: string
  price_amount: number
  currency: string
  stripe_price_id: string | null
  metadata: Record<string, any> | null
  is_default: boolean
  is_active: boolean
  display_order: number | null
  created_at: string
  updated_at: string
}

/**
 * ProductVariant create input
 */
export interface ProductVariantCreateInput {
  productId: string
  name: string
  priceAmount: number
  currency: string
  stripePriceId?: string
  metadata?: Record<string, any>
  isDefault: boolean
  isActive: boolean
  displayOrder?: number
}

/**
 * ProductVariant update input
 */
export interface ProductVariantUpdateInput {
  productId?: string
  name?: string
  priceAmount?: number
  currency?: string
  stripePriceId?: string
  metadata?: Record<string, any>
  isDefault?: boolean
  isActive?: boolean
  displayOrder?: number
}

/**
 * ProductVariants API Client
 */
export class ProductVariantsClient {
  constructor(private client: AkatsukiClient) {}

  /**
   * Get productvariants with filters
   */
  async list(
    filters: { productId?: string, isActive?: string } = {},
    limit: number = 20
  ): Promise<ProductVariant[]> {
    return this.client.invoke<ProductVariant[]>('product_variants-crud', {
      action: 'list',
      filters,
      limit,
    })
  }

  /**
   * Get productvariant by ID
   */
  async getById(id: string): Promise<ProductVariant> {
    return this.client.invoke<ProductVariant>('product_variants-crud', {
      action: 'get',
      id,
    })
  }

  /**
   * Create productvariant
   */
  async create(data: ProductVariantCreateInput): Promise<ProductVariant> {
    return this.client.invoke<ProductVariant>('product_variants-crud', {
      action: 'create',
      data,
    })
  }

  /**
   * Update productvariant
   */
  async update(id: string, data: ProductVariantUpdateInput): Promise<ProductVariant> {
    return this.client.invoke<ProductVariant>('product_variants-crud', {
      action: 'update',
      id,
      data,
    })
  }

  /**
   * Delete productvariant
   */
  async delete(id: string): Promise<{ deleted: boolean }> {
    return this.client.invoke<{ deleted: boolean }>('product_variants-crud', {
      action: 'delete',
      id,
    })
  }

  /**
   * Get variants for a specific product
   */
  async byProduct(filters: { isActive?: string } = {}): Promise<ProductVariant[]> {
    return this.client.invoke<ProductVariant[]>('product_variants-crud', {
      action: 'byProduct',
      filters,
    })
  }
}