/**
 * ProductVariant CRUD Edge Function
 *
 * Auto-generated by HEADLESS API Generator
 * - VibeCoding標準パターン (createAkatsukiHandler)
 * - Zod Validation
 * - Repository DI
 * - RLS対応
 *
 * Supported Actions:
 * - list
 * - get
 * - create
 * - update
 * - delete
 * - custom (byProduct): Get variants for a specific product
 */

import { createAkatsukiHandler } from '../_shared/handler.ts'
import { ProductVariantRepository } from '../_shared/repositories/ProductVariantRepository.ts'
import { ProductVariantCrudSchema, type ProductVariantCrudInput } from './schema.ts'

Deno.serve(async (req) => {
  return createAkatsukiHandler<ProductVariantCrudInput, any>(req, {
    inputSchema: ProductVariantCrudSchema,
    logic: async ({ input, userClient, adminClient, repos }) => {
      // Create Repository with userClient (RLS enabled)
      const product_variantRepo = new ProductVariantRepository(userClient)

      switch (input.action) {
        case 'list': {
          // Get product_variants with filters
          return product_variantRepo.findAll({
            productId: input.filters?.productId,
            isActive: input.filters?.isActive,
            limit: input.limit || 20,
          })
        }
        case 'get': {
          // Get product_variant by ID
          const product_variant = await product_variantRepo.findById(input.id)
          if (!product_variant) {
            throw Object.assign(new Error('ProductVariant not found'), {
              status: 404,
              code: 'PRODUCT_VARIANT_NOT_FOUND',
            })
          }
          return product_variant
        }
        case 'create': {
          // Create new product_variant
          const user = await product_variantRepo.getCurrentUser()
          return product_variantRepo.create({
            user_id: user.id,
            product_id: input.data.productId,
            name: input.data.name,
            price_amount: input.data.priceAmount,
            currency: input.data.currency,
            stripe_price_id: input.data.stripePriceId || null,
            metadata: input.data.metadata || null,
            is_default: input.data.isDefault,
            is_active: input.data.isActive,
            display_order: input.data.displayOrder || null,
          })
        }
        case 'update': {
          // Update product_variant
          const product_variant = await product_variantRepo.findById(input.id)
          if (!product_variant) {
            throw Object.assign(new Error('ProductVariant not found'), {
              status: 404,
              code: 'PRODUCT_VARIANT_NOT_FOUND',
            })
          }

          return product_variantRepo.update(input.id, input.data)
        }
        case 'delete': {
          // Delete product_variant
          const product_variant = await product_variantRepo.findById(input.id)
          if (!product_variant) {
            throw Object.assign(new Error('ProductVariant not found'), {
              status: 404,
              code: 'PRODUCT_VARIANT_NOT_FOUND',
            })
          }

          await product_variantRepo.delete(input.id)
          return { success: true, message: 'ProductVariant deleted' }
        }
        case 'byProduct': {
          // Get variants for a specific product
          return product_variantRepo.byProduct({
              isActive: input.filters?.isActive,
            }
          )
        }

        default:
          throw Object.assign(new Error('Invalid action'), {
            status: 400,
            code: 'INVALID_ACTION',
          })
      }
    },
  })
})

/* To invoke locally:

  1. Run `supabase start`
  2. Make an HTTP request:
  # List product_variants
  curl -i --location --request POST 'http://127.0.0.1:54321/functions/v1/product_variants-crud' \
    --header 'Authorization: Bearer YOUR_JWT_TOKEN' \
    --header 'Content-Type: application/json' \
    --data '{"action":"list","limit":10}'

  # Create product_variant
  curl -i --location --request POST 'http://127.0.0.1:54321/functions/v1/product_variants-crud' \
    --header 'Authorization: Bearer YOUR_JWT_TOKEN' \
    --header 'Content-Type: application/json' \
    --data '{"action":"create","data":{"title":"Example","content":"Content here"}}'

*/