import { z } from 'https://deno.land/x/zod@v3.23.8/mod.ts'

/**
 * ProductVariant Schema for CRUD operations
 * Auto-generated by HEADLESS API Generator
 */

// Enum schemas
// ProductVariant object schema
export const ProductVariantSchema = z.object({
  id: z.string().uuid(),
  productId: z.string().uuid(),
  createdAt: z.string(),
  updatedAt: z.string(),
  name: z.string().min(1).max(200),
  priceAmount: z.number(),
  currency: z.string(),
  stripePriceId: z.string(),
  metadata: z.record(z.any()),
  isDefault: z.boolean(),
  isActive: z.boolean(),
  displayOrder: z.number(),
})

// Input schemas for each CRUD operation
export const ProductVariantCrudSchema = z.discriminatedUnion('action', [
  // List product_variants
  z.object({
    action: z.literal('list'),
    filters: z.object({
      productId: z.string().uuid().optional(),
      isActive: z.boolean().optional(),
    }).optional(),
    limit: z.number().int().positive().max(100).optional(),
  }),
  // Get product_variant by ID
  z.object({
    action: z.literal('get'),
    id: z.string().uuid(),
  }),
  // Create product_variant
  z.object({
    action: z.literal('create'),
    data: z.object({
      productId: z.string().uuid(),
      name: z.string().min(1).max(200),
      priceAmount: z.number(),
      currency: z.string(),
      stripePriceId: z.string().optional(),
      metadata: z.record(z.any()).optional(),
      isDefault: z.boolean(),
      isActive: z.boolean(),
      displayOrder: z.number().optional(),
    }),
  }),
  // Update product_variant
  z.object({
    action: z.literal('update'),
    id: z.string().uuid(),
    data: z.object({
      productId: z.string().uuid().optional(),
      name: z.string().min(1).max(200).optional(),
      priceAmount: z.number().optional(),
      currency: z.string().optional(),
      stripePriceId: z.string().optional(),
      metadata: z.record(z.any()).optional(),
      isDefault: z.boolean().optional(),
      isActive: z.boolean().optional(),
      displayOrder: z.number().optional(),
    }),
  }),
  // Delete product_variant
  z.object({
    action: z.literal('delete'),
    id: z.string().uuid(),
  }),
  // Get variants for a specific product
  z.object({
    action: z.literal('byProduct'),
    filters: z.object({
      isActive: z.boolean().optional(),
    }).optional(),
  }),
])

export type ProductVariantCrudInput = z.infer<typeof ProductVariantCrudSchema>