/**
 * Fulfillment Service
 * Auto-generated by HEADLESS API Generator
 *
 * fulfillments-crud Edge Function の呼び出しを管理
 * - EdgeFunctionService wrapper
 * - Type-safe API calls
 * - AkatsukiResponse対応
 */

import { EdgeFunctionService } from './EdgeFunctionService'
import type { FulfillmentDatabaseRecord } from '../models/Fulfillment'

export class FulfillmentService {

  /**
   * Get fulfillments with filters
   */
  static async list(filters?: {
    status?: string
    fulfillmentType?: string
    limit?: number
  }) {
    return EdgeFunctionService.invoke<FulfillmentDatabaseRecord[]>('fulfillments-crud', {
      action: 'list',
      filters,
      limit: filters?.limit,
    })
  }

  /**
   * Get fulfillment by ID
   */
  static async getById(id: string) {
    return EdgeFunctionService.invoke<FulfillmentDatabaseRecord>('fulfillments-crud', {
      action: 'get',
      id,
    })
  }

  /**
   * Create new fulfillment
   */
  static async create(data: {
    orderItemId: string
    fulfillmentType: string
    status: 'pending' | 'completed' | 'failed'
    result?: Record<string, any>
    errorMessage?: string
    completedAt?: string
  }) {
    return EdgeFunctionService.invoke<FulfillmentDatabaseRecord>('fulfillments-crud', {
      action: 'create',
      data,
    })
  }

  /**
   * Update fulfillment
   */
  static async update(
    id: string,
    data: {
      orderItemId?: string
      fulfillmentType?: string
      status?: 'pending' | 'completed' | 'failed'
      result?: Record<string, any>
      errorMessage?: string
      completedAt?: string
    }
  ) {
    return EdgeFunctionService.invoke<FulfillmentDatabaseRecord>('fulfillments-crud', {
      action: 'update',
      id,
      data,
    })
  }

  /**
   * Set fulfillment status to 'completed'
   */
  static async setStatusCompleted(id: string) {
    return this.update(id, { status: 'completed' })
  }

  /**
   * Set fulfillment status to 'pending'
   */
  static async setStatusPending(id: string) {
    return this.update(id, { status: 'pending' })
  }
}