/**
 * OrderItem Service
 * Auto-generated by HEADLESS API Generator
 *
 * order_items-crud Edge Function の呼び出しを管理
 * - EdgeFunctionService wrapper
 * - Type-safe API calls
 * - AkatsukiResponse対応
 */

import { EdgeFunctionService } from './EdgeFunctionService'
import type { OrderItemDatabaseRecord } from '../models/OrderItem'

export class OrderItemService {

  /**
   * Get orderitems with filters
   */
  static async list(filters?: {
    orderId?: string
    limit?: number
  }) {
    return EdgeFunctionService.invoke<OrderItemDatabaseRecord[]>('order_items-crud', {
      action: 'list',
      filters,
      limit: filters?.limit,
    })
  }

  /**
   * Get orderitem by ID
   */
  static async getById(id: string) {
    return EdgeFunctionService.invoke<OrderItemDatabaseRecord>('order_items-crud', {
      action: 'get',
      id,
    })
  }

  /**
   * Create new orderitem
   */
  static async create(data: {
    orderId: string
    productId?: string
    variantId?: string
    productName: string
    variantName?: string
    quantity: number
    unitPrice: number
    subtotal: number
    productType: string
    productMetadata?: Record<string, any>
  }) {
    return EdgeFunctionService.invoke<OrderItemDatabaseRecord>('order_items-crud', {
      action: 'create',
      data,
    })
  }
}