/**
 * Order Service
 * Auto-generated by HEADLESS API Generator
 *
 * orders-crud Edge Function の呼び出しを管理
 * - EdgeFunctionService wrapper
 * - Type-safe API calls
 * - AkatsukiResponse対応
 */

import { EdgeFunctionService } from './EdgeFunctionService'
import type { OrderDatabaseRecord } from '../models/Order'

export class OrderService {

  /**
   * Get orders with filters
   */
  static async list(filters?: {
    status?: string
    userId?: string
    limit?: number
  }) {
    return EdgeFunctionService.invoke<OrderDatabaseRecord[]>('orders-crud', {
      action: 'list',
      filters,
      limit: filters?.limit,
    })
  }

  /**
   * Get order by ID
   */
  static async getById(id: string) {
    return EdgeFunctionService.invoke<OrderDatabaseRecord>('orders-crud', {
      action: 'get',
      id,
    })
  }

  /**
   * Create new order
   */
  static async create(data: {
    stripeCheckoutSessionId?: string
    stripePaymentIntentId?: string
    status: 'pending' | 'paid' | 'fulfilled' | 'cancelled' | 'refunded'
    totalAmount: number
    currency: string
    metadata?: Record<string, any>
    fulfilledAt?: string
  }) {
    return EdgeFunctionService.invoke<OrderDatabaseRecord>('orders-crud', {
      action: 'create',
      data,
    })
  }

  /**
   * Update order
   */
  static async update(
    id: string,
    data: {
      stripeCheckoutSessionId?: string
      stripePaymentIntentId?: string
      status?: 'pending' | 'paid' | 'fulfilled' | 'cancelled' | 'refunded'
      totalAmount?: number
      currency?: string
      metadata?: Record<string, any>
      fulfilledAt?: string
    }
  ) {
    return EdgeFunctionService.invoke<OrderDatabaseRecord>('orders-crud', {
      action: 'update',
      id,
      data,
    })
  }

  /**
   * Get current user's orders
   */
  static async my(filters?: {
    status?: string
  }) {
    return EdgeFunctionService.invoke<OrderDatabaseRecord[]>('orders-crud', {
      action: 'my',
      filters,
    })
  }

  /**
   * Set order status to 'paid'
   */
  static async setStatusPaid(id: string) {
    return this.update(id, { status: 'paid' })
  }

  /**
   * Set order status to 'pending'
   */
  static async setStatusPending(id: string) {
    return this.update(id, { status: 'pending' })
  }
}