/**
 * Product Service
 * Auto-generated by HEADLESS API Generator
 *
 * products-crud Edge Function の呼び出しを管理
 * - EdgeFunctionService wrapper
 * - Type-safe API calls
 * - AkatsukiResponse対応
 */

import { EdgeFunctionService } from './EdgeFunctionService'
import type { ProductDatabaseRecord } from '../models/Product'

export class ProductService {

  /**
   * Get products with filters
   */
  static async list(filters?: {
    productType?: string
    isActive?: string
    limit?: number
  }) {
    return EdgeFunctionService.invoke<ProductDatabaseRecord[]>('products-crud', {
      action: 'list',
      filters,
      limit: filters?.limit,
    })
  }

  /**
   * Get product by ID
   */
  static async getById(id: string) {
    return EdgeFunctionService.invoke<ProductDatabaseRecord>('products-crud', {
      action: 'get',
      id,
    })
  }

  /**
   * Create new product
   */
  static async create(data: {
    name: string
    description?: string
    productType: 'token_pack' | 'digital' | 'feature' | 'physical'
    stripeProductId?: string
    metadata?: Record<string, any>
    imageUrl?: string
    displayOrder?: number
    isActive: boolean
  }) {
    return EdgeFunctionService.invoke<ProductDatabaseRecord>('products-crud', {
      action: 'create',
      data,
    })
  }

  /**
   * Update product
   */
  static async update(
    id: string,
    data: {
      name?: string
      description?: string
      productType?: 'token_pack' | 'digital' | 'feature' | 'physical'
      stripeProductId?: string
      metadata?: Record<string, any>
      imageUrl?: string
      displayOrder?: number
      isActive?: boolean
    }
  ) {
    return EdgeFunctionService.invoke<ProductDatabaseRecord>('products-crud', {
      action: 'update',
      id,
      data,
    })
  }

  /**
   * Delete product
   */
  static async delete(id: string) {
    return EdgeFunctionService.invoke<{ success: boolean; message: string }>('products-crud', {
      action: 'delete',
      id,
    })
  }

  /**
   * Get all active products
   */
  static async active(filters?: {
    productType?: string
  }) {
    return EdgeFunctionService.invoke<ProductDatabaseRecord[]>('products-crud', {
      action: 'active',
      filters,
    })
  }

  /**
   * Set product productType to 'digital'
   */
  static async setProductTypeDigital(id: string) {
    return this.update(id, { productType: 'digital' })
  }

  /**
   * Set product productType to 'token_pack'
   */
  static async setProductTypeTokenPack(id: string) {
    return this.update(id, { productType: 'token_pack' })
  }
}