/**
 * ProductVariant Service
 * Auto-generated by HEADLESS API Generator
 *
 * product_variants-crud Edge Function の呼び出しを管理
 * - EdgeFunctionService wrapper
 * - Type-safe API calls
 * - AkatsukiResponse対応
 */

import { EdgeFunctionService } from './EdgeFunctionService'
import type { ProductVariantDatabaseRecord } from '../models/ProductVariant'

export class ProductVariantService {

  /**
   * Get productvariants with filters
   */
  static async list(filters?: {
    productId?: string
    isActive?: string
    limit?: number
  }) {
    return EdgeFunctionService.invoke<ProductVariantDatabaseRecord[]>('product_variants-crud', {
      action: 'list',
      filters,
      limit: filters?.limit,
    })
  }

  /**
   * Get productvariant by ID
   */
  static async getById(id: string) {
    return EdgeFunctionService.invoke<ProductVariantDatabaseRecord>('product_variants-crud', {
      action: 'get',
      id,
    })
  }

  /**
   * Create new productvariant
   */
  static async create(data: {
    productId: string
    name: string
    priceAmount: number
    currency: string
    stripePriceId?: string
    metadata?: Record<string, any>
    isDefault: boolean
    isActive: boolean
    displayOrder?: number
  }) {
    return EdgeFunctionService.invoke<ProductVariantDatabaseRecord>('product_variants-crud', {
      action: 'create',
      data,
    })
  }

  /**
   * Update productvariant
   */
  static async update(
    id: string,
    data: {
      productId?: string
      name?: string
      priceAmount?: number
      currency?: string
      stripePriceId?: string
      metadata?: Record<string, any>
      isDefault?: boolean
      isActive?: boolean
      displayOrder?: number
    }
  ) {
    return EdgeFunctionService.invoke<ProductVariantDatabaseRecord>('product_variants-crud', {
      action: 'update',
      id,
      data,
    })
  }

  /**
   * Delete productvariant
   */
  static async delete(id: string) {
    return EdgeFunctionService.invoke<{ success: boolean; message: string }>('product_variants-crud', {
      action: 'delete',
      id,
    })
  }

  /**
   * Get variants for a specific product
   */
  static async byProduct(filters?: {
    isActive?: string
  }) {
    return EdgeFunctionService.invoke<ProductVariantDatabaseRecord[]>('product_variants-crud', {
      action: 'byProduct',
      filters,
    })
  }
}