/**
 * Fulfillments Demo Card
 * Auto-generated by HEADLESS API Generator
 *
 * Usage in ExamplesPage.tsx:
 *   import { FulfillmentsDemo } from '../components/features/fulfillments/FulfillmentsDemo'
 *   <FulfillmentsDemo />
 */

import { useState } from 'react'
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from '../../ui/card'
import { Button } from '../../ui/button'
import { Input } from '../../ui/input'
import { Textarea } from '../../ui/textarea'
import { Badge } from '../../ui/badge'
import { useFulfillments } from '../../../hooks/useFulfillments'
import type { Fulfillment } from '../../../models/Fulfillment'

export function FulfillmentsDemo() {
  const [orderItemId, setOrderItemId] = useState<string>(null)
  const [fulfillmentType, setFulfillmentType] = useState<string>('')
  const [status, setStatus] = useState<'pending' | 'completed' | 'failed'>('pending')
  const [result, setResult] = useState<Record<string, any>>(null)
  const [errorMessage, setErrorMessage] = useState<string>(null)
  const [completedAt, setCompletedAt] = useState<string>(null)
  const [editingId, setEditingId] = useState<string | null>(null)

  const {
    fulfillments,
    isLoading,
    createFulfillment,
    isCreating,
    updateFulfillment,
    isUpdating,
    deleteFulfillment,
    isDeleting,
    setStatusCompleted,
    setStatusPending,
  } = useFulfillments({ mine: true })

  const resetForm = () => {
    setOrderItemId(null)
    setFulfillmentType('')
    setStatus('pending')
    setResult(null)
    setErrorMessage(null)
    setCompletedAt(null)
    setEditingId(null)
  }

  const handleCreate = () => {
    createFulfillment({
      orderItemId,
      fulfillmentType,
      status,
      result,
      errorMessage,
      completedAt,
    })
    resetForm()
  }

  const handleEdit = (item: Fulfillment) => {
    setEditingId(item.id)
    setOrderItemId(item.orderItemId)
    setFulfillmentType(item.fulfillmentType)
    setStatus(item.status)
    setResult(item.result ?? null)
    setErrorMessage(item.errorMessage ?? null)
    setCompletedAt(item.completedAt ?? null)
  }

  const handleUpdate = () => {
    if (!editingId) return
    updateFulfillment(editingId, {
      orderItemId,
      fulfillmentType,
      status,
      result,
      errorMessage,
      completedAt,
    })
    resetForm()
  }

  const itemCount = fulfillments?.length ?? 0

  return (
    <Card className="border-green-200 bg-gradient-to-br from-green-50 to-emerald-50">
      <CardHeader>
        <CardTitle className="flex items-center gap-2">
          <span className="text-2xl">📝</span>
          Fulfillments CRUD (HEADLESS API)
        </CardTitle>
        <CardDescription>
          Edge Function + React Query - Full CRUD with RLS
        </CardDescription>
      </CardHeader>
      <CardContent className="space-y-4">
        {/* Code Example */}
        <pre className="bg-gray-50 p-3 rounded-lg text-xs font-mono overflow-x-auto">
          <code>{`// Frontend: React Query Hook
const { fulfillments, createFulfillment, updateFulfillment } = useFulfillments()
createFulfillment({ orderItemId: '...', fulfillmentType: '...', status: '...', result: '...', errorMessage: '...', completedAt: '...' })`}</code>
        </pre>

        {/* Create/Edit Form */}
        <div className="bg-white p-4 rounded-lg space-y-3">
          <h3 className="font-semibold text-gray-700">
            {editingId ? '✏️ Edit Fulfillment' : '➕ Create Fulfillment'}
          </h3>

          <Input
            placeholder="FulfillmentType"
            value={ fulfillmentType ?? ''}
            onChange={(e) => setFulfillmentType(e.target.value)}
          />

          <select
            className="w-full border rounded-md p-2"
            value={ status ?? ''}
            onChange={(e) => setStatus(e.target.value as any)}
          >
            <option value="pending">pending</option>
            <option value="completed">completed</option>
            <option value="failed">failed</option>
          </select>

          <Input
            placeholder="ErrorMessage"
            value={ errorMessage ?? ''}
            onChange={(e) => setErrorMessage(e.target.value)}
          />

          <div className="flex gap-2">
            {editingId ? (
              <>
                <Button onClick={handleUpdate} disabled={isUpdating}>
                  {isUpdating ? 'Updating...' : 'Update'}
                </Button>
                <Button variant="outline" onClick={resetForm}>
                  Cancel
                </Button>
              </>
            ) : (
              <Button onClick={handleCreate} disabled={isCreating}>
                {isCreating ? 'Creating...' : 'Create Fulfillment'}
              </Button>
            )}
          </div>
        </div>

        {/* List */}
        <div className="bg-white p-4 rounded-lg space-y-3">
          <h3 className="font-semibold text-gray-700">📚 Your Fulfillments ({itemCount})</h3>

          {isLoading && (
            <p className="text-sm text-gray-500">Loading fulfillments...</p>
          )}

          {!isLoading && itemCount === 0 && (
            <p className="text-sm text-gray-500">No fulfillments yet. Create your first one!</p>
          )}

          <div className="space-y-2">
            { fulfillments?.map((item) => (
              <div
                key={item.id}
                className="border rounded-lg p-3 space-y-2 hover:bg-gray-50 transition-colors"
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="flex-1 min-w-0">
                    <h4 className="font-medium text-gray-900 truncate">
                      {item.orderItemId}
                    </h4>
                    <p className="text-sm text-gray-600 line-clamp-2 mt-1">
                      {item.fulfillmentType}
                    </p>
                  </div>
                  <Badge variant={item.status === 'pending' ? 'secondary' : 'default'}>
                    {item.status}
                  </Badge>
                </div>

                <div className="flex gap-2 flex-wrap">
                  <Button
                    size="sm"
                    variant="outline"
                    onClick={() => handleEdit(item)}
                  >
                    Edit
                  </Button>

                  <Button
                    size="sm"
                    variant="secondary"
                    onClick={() => {
                      if (item.status === 'pending') {
                        setStatusCompleted(item.id!)
                      } else {
                        setStatusPending(item.id!)
                      }
                    }}
                  >
                    Toggle Status
                  </Button>

                  <Button
                    size="sm"
                    variant="destructive"
                    onClick={() => {
                      if (confirm('Delete this fulfillment?')) {
                        deleteFulfillment(item.id!)
                      }
                    }}
                    disabled={isDeleting}
                  >
                    Delete
                  </Button>
                </div>

                {item.createdAt && (
                  <p className="text-xs text-gray-400">
                    Created: {new Date(item.createdAt).toLocaleDateString()}
                  </p>
                )}
              </div>
            ))}
          </div>
        </div>

        {/* Info */}
        <div className="bg-blue-50 p-3 rounded-lg text-sm text-gray-700">
          <p className="font-semibold mb-2">🎯 Features:</p>
          <ul className="list-disc list-inside space-y-1 text-xs">
            <li>✅ Full CRUD operations (Create, Read, Update, Delete)</li>
            <li>✅ RLS Security (Row Level Security)</li>
            <li>✅ Edge Function (createAkatsukiHandler)</li>
            <li>✅ React Query (Automatic cache & invalidation)</li>
            <li>✅ Type-safe (TypeScript + Zod)</li>
          </ul>
        </div>
      </CardContent>
    </Card>
  )
}